### ISSUE TITLE
Radition shield no longer works with newest Atomic Science 

### ISSUE THREAD

**Issue by wiilover22** [MachineMuse/MachineMusePowersuits#476]
Simply put, along the way with the Atomic Science updates lately, the radiation shielding no longer works. I skipped from Atomic Science version 55->77, so I'm unable to give you the exact version it changed. But I have tried version 65 as well, and the issue persisted even then.

To repeat: Install radiation shielding on modular powersuit, and hold a fissile fuel rod. 

Using:
Minecraft 1.6.4
Atomic-Science-1.2.0.77-core
Calclavia-Core-Development-1.2.0.23-main
Universal-Electricity-3.1.0.74-core
ModularPowersuits-1.6.4-0.10.0-100
Numina-1.6.2-0.1.2-57
slick-util (latest version, not sure on number)

**Comment by MachineMuse** [comment]
Seems to have disappeared so closing this
