### ISSUE TITLE
Aesthetics: hi-poly armor doesn't hook properly to Galacticraft animations

### ISSUE THREAD

**Issue by EzerArch** [MachineMuse/MachineMusePowersuits#488]
Minecraft Version: 1.6.4
Forge Version: 9.11.1.965-MCPatcher
MPS Version: 0.10.0-100 or earlier
Numina Version:0.1.2-57 or earlier

Not game-breaking. Low priority.

The hi-poly armor doesn't hook properly to Galacticraft animations, this is quite noticeable with the running airborne in low gravity.

![2013-12-10_00 16 59](https://cloud.githubusercontent.com/assets/6743303/2625789/7721a138-bda9-11e3-8960-53b23b570edb.png)

**Video:** http://youtu.be/u0nn6q-4keM?t=22m30s

I reported it to @Micdoodle8/[Galacticraft/issue 321](https://github.com/micdoodle8/Galacticraft/issues/321). He said:

> It's up to the MPS dev to solve this issue, since their armor needs to be rotated based on the player limbs. I approached MachineMuse about this a long time ago, and she said that there's no way to access the player instance while rendering the armor, therefore it's not possible to rotate it dynamically.

If it's still not possible to fix this issue on your end, no problem. I'm asking here so I can close the issue in the Galacticraft repos.

I think there should be some sort of basic PlayerAnim API that could be used along the mods with no worry something will break or be fixed per-mod basis.

**Comment by EzerArch** [comment]
IT HAPPENED!

![mps](https://cloud.githubusercontent.com/assets/6743303/12534124/05bf70da-c232-11e5-9fae-50ee6aa345b3.gif)

(Many thanks to @radfast and @micdoodle8 for making it possible in Galacticraft with SmartMoving)

Sorry for bumping this long-dead issue, but I wanted to let you know. :D

**Comment by radfast** [comment]
Nice animated GIF :)  Can you tweet it?

I think this means @MachineMuse added SmartMoving ... I [think she did that](https://github.com/MachineMuse/MachineMusePowersuits/commit/968764d79e51d2bad9d7c28359b281520beb66cb#diff-414531cc2a1d07f8a3df76b5ca6f689d) in August when I was taking a break from modding.  I'm pleased we finally have 100% SmartMoving compatibility on the Galacticraft side as well.

Your video showcases the reason why it was worth doing :)

**Comment by EzerArch** [comment]
@radfast, I did: https://twitter.com/EzerArch/status/691438781635915777

I knew MachineMuse had added SM long time ago, but the animations back then were broken as seen in the 1st post. Likewise in GC, there are still a few minor issues left I may report or not, but the improvement is big. :+1:

**Comment by flowtender** [comment]
great, I'm glad this got resolved!

**Comment by radfast** [comment]
@MachineMuse  :)  Any future compatibility issues between Galacticraft and MMMPS which are reported to you, please do let me know, I am aiming for full compatibility if possible.

(I know there may currently be an issue with Jet Boots / Jetpack not moving the player correctly when the player is in freefall.  Still working on that one.)

**Comment by flowtender** [comment]
ok :)
