### ISSUE TITLE
MPS tickhandler consuming large amounts of CPU

### ISSUE THREAD

**Issue by Cozza38** [MachineMuse/MachineMusePowersuits#492]
Hi MM,

We have discussed this in the past but didn't get very far.

The following is a warmroast JVM profile taken over the course of ~1 hour showing the MPS tickhandler consuming ~36% total CPU time.

In this profile there was an average of 15 players online using the Yogscast Complete Pack.

https://dl.dropboxusercontent.com/u/82904851/WarmRoast.htm

If there's anything I can do to help you diagnose further, let me know.

**Comment by MachineMuse** [comment]
so, there have been quite a few internal changes including but not limited to the change to 1.7.10, and after running a profiler on a server with 12-15 players as well as on my client, I wasn't able to find any MPS-related bottlenecks anymore. So I'm tentatively closing this. If anyone does find a bottleneck and has a profile from an up-to-date version, I welcome them to post it.
