### ISSUE TITLE
Hologram emitter not craftable

### ISSUE THREAD

**Issue by Marx1** [MachineMuse/MachineMusePowersuits#497]
Hologram emitter is not craft able using TE or Vanilla recipes. It DOES work if you enable UE recipes, but I don't want those in my pack.

Version info:

MPS: 1.6.4-0.10.0-91 and 1.6.4-0.10.0-118 (tested)
Numa: 0.1.2-59 and  0.3.0.80 (tested)
Recipe version: Downloaded off of Jenkins at the same time the MPS was downloaded, no changes made.
TE: 3.0.0.2

**Comment by xorinzor** [comment]
gonna have to go with @marx1 here, that wasn't quite the appropriate response from Machinemuse.

the JSON format is easy to understand, but for some odd reason the game just won't recognize the recipe, as if the item name is wrong.
