### ISSUE TITLE
Radiation Shielding not existent anymore, or unable to craft?

### ISSUE THREAD

**Issue by jangofett890** [MachineMuse/MachineMusePowersuits#501]
I have these mods installed that add Radiation type objects, also I'm using Modular Power Suits addons

ModularPowersuits-1.6.4-0.10.0-118
powersuitaddons-1.6.4-887
Resonant-Engine-Development-1.2.0.254-universal
Resonant-Induction-Development-0.3.1.316-atomic
Resonant-Induction-Development-0.3.1.316-Resonant-Induction Core
industrialcraft-2_2.0.397-experimental

![screenshot 2014-06-18 18 20 33](https://cloud.githubusercontent.com/assets/2407092/3322663/08568170-f750-11e3-91dc-057b5e6fb637.png)

If it has to do with one of the mods installed, let me know instead of just closing the issue, thanks

**Comment by MachineMuse** [comment]
RI seems to no longer be maintained so closing this

**Comment by jangofett890** [comment]
Anyway to incorporate it for IC2?
