### ISSUE TITLE
Improve localization

### ISSUE THREAD

**Issue by Adaptivity** [MachineMuse/MachineMusePowersuits#516]
Tooltips, guis are hardcoded. Move them all into .lang file.

**Comment by Korynkai** [comment]
Will be addressed in 0.11.0.6-QMX.

**Comment by Adaptivity** [comment]
ping me when it's will be done.

**Comment by Korynkai** [comment]
Not released yet, but you can find the links to the lang files here if you're interested in helping with the translation effort: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293401-modular-powersuits-addons-mpsa-requires-modular?comment=525

**Comment by MachineMuse** [comment]
ok, got descriptions into localization files. Now just the GUI stuff.

**Comment by MachineMuse** [comment]
ok, I think I got everything except the chat messages (module enabled/disabled.) I have a different solution in mind for that.

**Comment by aionys** [comment]
About that- does your different solution involve not flooding the chat log? Like maybe having an HUD icon for active modules?

**Comment by Adaptivity** [comment]
@MachineMuse https://github.com/MachineMuse/MachineMusePowersuits/blob/experimental/src/main/scala/net/machinemuse/powersuits/item/ModularItemBase.scala#L68 hardcoded. Also, would it possible to translate 'g' in Weight string? Also, many other gui elements hardcoded in Tinker Table. And item tooltips hardcoded too. Still a lot of stuff should be done :)
