### ISSUE TITLE
Server crash when adding recipe files to config. Assertion exception

### ISSUE THREAD

**Issue by Oninaig** [MachineMuse/MachineMusePowersuits#527]
Server crashes when I added the two .recipe files to the config folder under machinemuse/recipes.

Adding the latest .recipe files from jenkins.

Heres the crash log: http://pastebin.com/SRaPnBen

**Comment by MCAeolus** [comment]
I just used @MrMetric 's fix, and it seems his fix still works for 1.7.10 (Direwolf20). I don't know why it wouldn't work for you, @charles7926 .

**Comment by MachineMuse** [comment]
Well I can't reproduce this, so I'm going to assume it's fixed, but even if it is still an issue it belongs on the Numina tracker.

**Comment by MachineMuse** [comment]
nvm, actually fixed now
