### ISSUE TITLE
Numina Error

### ISSUE THREAD

**Issue by AnonymousPuppy** [MachineMuse/MachineMusePowersuits#539]
Using a custom modpack, Forge .1217, MPS 0.11.0.172, numina 0.4.0.98, and slick util. I got this error in my console when I loaded up a world, I didn't crash or anything, just thought this would be important. 

http://pastebin.com/HmSpztkC

**Comment by MachineMuse** [comment]
Hm, I see, it's due to changes in how mods are loaded. Oh well. The custom font was neat but it caused more headaches than it was worth. I've removed slick util entirely.
