### ISSUE TITLE
Power Fist's Picaxe Module does not mine 1.7 Minecraft blocks and custom blocks

### ISSUE THREAD

**Issue by EzerArch** [MachineMuse/MachineMusePowersuits#541]
Minecraft Version: 1.7.10
Forge Version: 1217
MPS Version: 0.11.0.172
Numina Version: 0.4.0.98

The Picaxe Module doesn't mine the new minecraft blocks, such as quartz blocks, stained clay blocks, and custom/mod blocks, such as Tinker Table, Galacticraft's machines etc.

EDIT:
This may be a duplicate of #540. But on the other hand, I can break stones. Different issues?

**Comment by not4u2kno** [comment]
This issue effectively makes the powerfist useless. *sadface*

**Comment by ssotangkur** [comment]
Can you check your logs and see if you have any errors related to CoFH parserGenerator or a .DS_store file? I did, and simply removed the .DS_store file and restarted the game and now everything with powerfist works.

**Comment by laurencedv** [comment]
MC 1.7.10
Forge 10.13.2.1272
MPS 0.11.0.176
Numina 0.4.0.100

We can't break stone brick, hardened dirt, furnace, Tinker smeltery, etc...
Deleted all .DS_store file from any location in the FTB folder.
No error in the log at the time of the block breaking try.

**Comment by ssotangkur** [comment]
It might have been just a derp on my part but I later realized I was in Adventure mode not Survival mode and when I switched to Survival I could mine again.

**Comment by creeperraper1337** [comment]
oops lol glad you figured it out :smile:
