### ISSUE TITLE
Armor Durability

### ISSUE THREAD

**Issue by HideAwayDk** [MachineMuse/MachineMusePowersuits#545]
Hey :)
I dont know if this is a bug, but i can't find anything aboudt it, and it wassent there in the 1.6.4 version.
Armor now have durability even tho my suite have prenty of power, armor still break.

On the image i just repaired chest and lags, boots are damage and my head is gone corse i didden made it to the anvil in time :(
![skaermbillede 2014-10-30 19 17 56](https://cloud.githubusercontent.com/assets/7749454/4849380/5ac05916-6061-11e4-8a5c-978c44e0d531.png)

**Comment by Pinkbyte** [comment]
Probably Forge problem. Industrial Craft 2 armor(uncharged) was dropped, while taking damage too. Now - it's fine. Not reproduceable with Forge 10.13.2.1307.

**Comment by MachineMuse** [comment]
should be fixed now
