### ISSUE TITLE
Broken Thermal Expansion Recipies

### ISSUE THREAD

**Issue by mathwizi2005** [MachineMuse/MachineMusePowersuits#547]
Currently using the most recent stable 1.7.10 build and recipies list as of this post (MPS 0.11.0.175 and Numia 0.4.0.99), any recipe using Hardened Glass, Filled Tesseract Frames, Filled Energy Cell Frames, Empty Redstone Energy Conduit and Machine Frames are broken and not being assigned to the respective items (MV and HV Caps, Tinker Table, Glider Wing, and Force Field Emitter)

I'd have fixed this myself but since TE blocks got obfuscated this version, I am unable to find the internal names for these recipies
Using TE 4.0.0B5 and TF 1.0.0B3

Edit: Now using TE 4.0.0B6-16 and TF 1.0.0B3-8, no change

**Comment by MachineMuse** [comment]
cool - do you mind if I replace the 'official' file with your updated one?

**Comment by KasimAhmic** [comment]
Nah go right ahead! I made a pull request for it as well.

**Comment by MachineMuse** [comment]
thank you :>
