### ISSUE TITLE
IC2 charging uses RF energy ratio

### ISSUE THREAD

**Issue by kieranmenor** [MachineMuse/MachineMusePowersuits#551]
Using MC 1.7.10 with MMMP 0.11.0.175, IC2-exp 2.2.652 and TE 4.0.0B6-16.

Changing the EU energy ratio has no effect on the IC2 (tested with BatBox) charge rate. The RF ratio affects both IC2 and TE charge rate.

I can't see anything in the MMMP source that should cause this (but then again, I'm not very experienced with MC mod coding or Scala), so I'm thinking the IC2 chargers are somehow using the Thermal Expansion interface?

**Comment by Pinkbyte** [comment]
You can try QMXTech fork(https://github.com/QMXTech/MachineMusePowersuits) or just grab changes from this pull request #568
