### ISSUE TITLE
Unable to cycle power tools

### ISSUE THREAD

**Issue by politician** [MachineMuse/MachineMusePowersuits#553]
The default, shift+scroll doesn't work, so I disabled that in the config file and setup "," and "." keybindings.  After disabling all conflicting keybindings, it still doesn't cycle.  

* Zoom doesn't work either
* But the keybinding for opening the GUI keybinding menu does work - even when I change the keybindings, so it's not like all of the MPS keybinding code is broken
* None of the log files contain any helpful information.

My UI shows 3 copies of the Lux tool when I equip the Power Fist.  I have the pickaxe, shovel, and lux modules installed, so I would've expected it to show those icons.

It occurred to me that the scroll might be working, but because the mode wheel contains all of the same icon, I might not notice.  Nevertheless, I couldn't dig Stone even with the Diamond Pickaxe Upgrade and full power, so I'm guessing that's an unrelated bug.

I'm running 0.11.0.175 from the Direwolf20 1.0.2 FTB pack.

**Comment by MachineMuse** [comment]
ok, looks like all the issues in this thread were resolved so closing it
