### ISSUE TITLE
Smart Moving Armor Hooks Broken Once again but for 1.7.10.. lol

### ISSUE THREAD

**Issue by Razorskills** [MachineMuse/MachineMusePowersuits#555]
Well, here are the links to the threads.. I think it should all be mostly the same, but I know he restructured the files, renamed them, and made them neater. I don't code, but I remember last time he had moved some files to a different location from where you were looking for them, maybe he did that again. Something seems to happen every minecraft versions though..

Smart Moving: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1274224
Player API: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1277996
Render Player API: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1283669

**Comment by Korynkai** [comment]
Fixed in QMXTech/MachineMusePowersuits@0031ba886d31b5dba93a16cbd28accbad59497a8

**Comment by MachineMuse** [comment]
well, that ended up being simpler than it looked. If only the RenderPlayerAPI instructions were intelligible...

**Comment by EzerArch** [comment]
Now I finally got my hands on the official release, I tried SM with MPS:

http://www.youtube.com/watch?v=xPoSqmWK_Os

*If* I had to complain about something, probably depending on Divisor, it would be:
* Alternative Flying animation only possible in Creative mode.
* Animation speed directly tied to momentum, e.g. Walking at high-speed midair.

**Comment by Biocraft125** [comment]
the armor gets a little glitched out when you modify the suit to have the shoulder pads

**Comment by EzerArch** [comment]
@Biocraft125, I'm afraid it is on SmartMoving's side due to how the arms pivot.
