### ISSUE TITLE
Problem with recipe in recipe folder and nei interaction

### ISSUE THREAD

**Issue by HadesDurin** [MachineMuse/MachineMusePowersuits#556]
when i have vanilla.recipe ind the recipe folder and want to review a recipe inside of minecraft i got this error:
http://pastebin.com/8KRfP5C7

using latest forge
Launched Version: 1.7.10-Forge10.13.2.1264
and powersuitsbuild

**Comment by Korynkai** [comment]
This crash is in Numina and is probably related to #565, QMXTech/MachineMusePowersuits#17 and QMXTech/Numina#2. As such this issue is already on my queue and should be taken care of in the next QMX release.
Excuse the "canned response", seems there are alot of similar if not duplicate JSON issues.
