### ISSUE TITLE
Ilegal annotation combination on ItemPowerArmorHelmet

### ISSUE THREAD

**Issue by boq** [MachineMuse/MachineMusePowersuits#561]
Class ItemPowerArmorHelmet is annotated with multiple annotations of same type. It's not valid in JVM and breaks reflection calls like `Class.getAnnotation` (see OpenMods/OpenBlocks#568). Though it does not affect interface stripping, since FML bypasses checks by operating directly on bytecode.

Looks like multiple `Interface` annotations should be grouped with `InterfaceList`.

**Comment by Korynkai** [comment]
I'll look into this with the next QMX build, seems like it's probably a simple fix.

**Comment by MachineMuse** [comment]
closed by 4515caa8ae56da90d3120481af4dbb506f12eaef
