### ISSUE TITLE
Powersuits completely draining power

### ISSUE THREAD

**Issue by TheReturningVoid** [MachineMuse/MachineMusePowersuits#562]
Hey,

On a server and I just installed the jetpack module on my chestplate. I have MV Capacitors on all pieces of armor. However, my power is at 0. No power gets generated, and if I try to charge one manually in something like an EnderIO Capacitor Bank, it all gets immediately drained when I put it back in my inventory. Removing Jetpack module does not solve the issue.

Using the Resonant RIse 3 modpack with version 1.7.10-0.11.0.176 installed
Numina 0.4.0.100 installed
Powersuit Addons 1.7.10-901 installed

If you need more information, let me know and I'll try to supply.

EDIT: Nerer mind, got it fixed. Someone close report as it was just my mechanical assistance :P

**Comment by melekaiah** [comment]
This is confirmed to be caused by mechanical assitance. it is pulling 500 rf per tick. as per config. 
which means 10k a second.

reducing this to 25 in the config. make it pull 500 per second, which i believe is what was intended.
