### ISSUE TITLE
Reboot Loop on GSON Assertion

### ISSUE THREAD

**Issue by CandiceJoy** [MachineMuse/MachineMusePowersuits#565]
<Candice> new crash, this time not mpsaddons.  http://pastebin.com/JDrqxJgW
<Candice> thermalexpansion.recipes http://pastebin.com/wxhWg62r
<Candice> vanilla.recipes http://pastebin.com/QdBV4xiy
<Candice> its causing the server to go into a reboot loop with that crash every time

**Comment by Korynkai** [comment]
This crash is in Numina and is related to [QMXTech/MachineMusePowersuits#17](https://github.com/QMXTech/MachineMusePowersuits/issues/17) and [QMXTech/Numina#2](https://github.com/QMXTech/Numina/issues/2). As such this issue is already on my queue and should be taken care of in the next QMX release.

**Comment by MachineMuse** [comment]
hello, I merged the QMX changes into numina at least and the pastes seem to have expired so I'm closing this. please give me a few days then open a new issue if it still isn't fixed. thanks for your help Korynkai :>
