### ISSUE TITLE
permision to upload it on curse

### ISSUE THREAD

**Issue by bigpodgurc** [MachineMuse/MachineMusePowersuits#569]
i have been seeing that you havent uploaded the mod to curse i was thinking if i can do that because i will be uploading my take on addons i can also handle that

**Comment by Razorskills** [comment]
... Shouldn't Muse upload it so she gets the rewards? And not someone else? That is if she wants to upload it. It makes curse modpacks possible though.

**Comment by bigpodgurc** [comment]
i would do it just becuase of curse modpacks becuase is sad that almost no modpacks use powersuits anymore and even those who would wouldnt becuase it isnt on curse

**Comment by Badcholo** [comment]
I would appreciate a download link please. i don't know how to compile the files.

**Comment by gigabit101** [comment]
http://build.technicpack.net/job/ModularPowersuits/

**Comment by MachineMuse** [comment]
I didn't want to upload it to Curse until I fixed all the crash bugs. I would rather not have someone else doing it!
