### ISSUE TITLE
GregTech recipes does not work

### ISSUE THREAD

**Issue by florian96** [MachineMuse/MachineMusePowersuits#571]
Hey i have a Server with GregTech 5 (1.7.10) but no recipes are available. Please Fix this bug.

**Comment by MachineMuse** [comment]
It's not a bug. You have to set the recipes up yourself. You can install one of the pre-made recipe files or you can make your own. I don't have one for Gregtech at the moment so if someone wants to make one and send it to me or make a pull request, I'd appreciate it :)
