### ISSUE TITLE
No Crafting recipes for any MPS item

### ISSUE THREAD

**Issue by ajthemacboy** [MachineMuse/MachineMusePowersuits#572]
Hi! I'm having an issue with crafting in my modpack.

NEI doesn't show any recipes for any MPS item. When I look up the recipes online, it still doesn't work. 

I downloaded the latest version from the beta/jenkins website, though I can't seem to find that website now. This was a few days ago.

Thanks!

**Comment by Pinkbyte** [comment]
Did you put recipe file in config/machinemuse/recipes ?

**Comment by ajthemacboy** [comment]
No, where can I find them?

**Comment by Pinkbyte** [comment]
On official Jenkins - http://build.technicpack.net/job/ModularPowersuits/

**Comment by ajthemacboy** [comment]
Thanks! Is it possible to use both vanilla recipes and MPS recipes by just putting them together in the folder? I'd test myself but I can't right now.

**Comment by Pinkbyte** [comment]
What do you mean "MPS recipes"? Recipes on that link are only for MPS. vanilla.recipes uses only vanilla items to craft powersuit components and ThermalExpansion.recipes uses items(obviously) from Thermal Expansion. They are in no way will override other recipes, not related to Modular Powersuits

**Comment by ajthemacboy** [comment]
Sorry, I meant Thermal Expansion recipes, not MPS recipes. What I meant to say was, can I have both vanilla and TE recipes active at the same time? It doesn't matter though, I can test myself. Thanks!
