### ISSUE TITLE
Feature Request: Configurable addInitialCost

### ISSUE THREAD

**Issue by Pinaz9** [MachineMuse/MachineMusePowersuits#574]
As part of a modpack/map I am making, I wish to change what different modules cost in terms of items. I cannot write a mod to do this, but I am able to use configs. (Writing a mod to do this would require hacking into your code, correct?) 

Specifically, I wish to make heat sink modules require blocks of invar and cryotheum. This change is crucial to the balance of the pack. There are other, less crucial changes that I wish to make.

I could always just modify your code directly and distribute a copy, but that feels wrong, as most of the code is yours.

Thank you for your consideration, 
Patrick

**Comment by MachineMuse** [comment]
Hello,

Sorry for my inactivity. I needed to de-stress! Anyway, you should be able to configure it indirectly using the recipes files, but the need for components to be configurable is definitely on the table.

**Comment by MachineMuse** [comment]
Added in c3b2ab36bdc8f00e1c9dc8cfd98575a12c990ca1 !  :)
