### ISSUE TITLE
Camouflage Armor Bug

### ISSUE THREAD

**Issue by werkamsus** [MachineMuse/MachineMusePowersuits#578]
When you activate camouflage, the invisibility works properly but it still displays a white leather tunic armor. Is there a fix available for this? The situation is quite desperate.

**Comment by werkamsus** [comment]
The modpack is Direwolf20 v1.5.0 (mc 1.7.10)

**Comment by MachineMuse** [comment]
fixed by 41bd2aa687dc79fc4dc6796f5fde915da9cd97df
