### ISSUE TITLE
Power Armor takes damage from special mobs

### ISSUE THREAD

**Issue by President741** [MachineMuse/MachineMusePowersuits#579]
a while ago i started playing the core zero modpack. but i have a problem with the power armor. when special mobs are hitting me, the durability of the armor decreases. I have a full battery and an active energie shield in my armor but I think it will break soon. 

here is a list of all mods that are in this modpack:
http://www.technicpack.net/modpack/enderx-core-zero.685135/mods
![e145427cf8](https://cloud.githubusercontent.com/assets/7271378/8909233/9ce89526-3480-11e5-8b5f-c75fc355aa86.jpg)

**Comment by MachineMuse** [comment]
Hello,

This is technically because of a problem with the other mods, accessing the item's durability directly instead of using the accessor methods like they're supposed to.

In any case, this keeps happening, so I'll add a workaround.

**Comment by MachineMuse** [comment]
Never mind. That used to happen, but the base has changed. Hopefully setting max damage to 0 will prevent this from happening again.
