### ISSUE TITLE
Numina : Exception in server tick loop

### ISSUE THREAD

**Issue by spannerman79** [MachineMuse/MachineMusePowersuits#581]
Builds all from http://build.technicpack.net/view/MachineMuse/job/ModularPowersuits/193/
Forge 1448
Crash - https://gist.github.com/spannerman79/2f16352ff999600659de

**Comment by MachineMuse** [comment]
can you paste the recipes file you're using

**Comment by MachineMuse** [comment]
also please try with no recipes file

**Comment by MachineMuse** [comment]
nvm I FINALLY figured out why this is happening.

PARKERRRRRRRRRRRRRRRRRRRRRRRR

**Comment by MachineMuse** [comment]
can you see if this works with build 106 of Numina please? Don't have to update MPS since it doesn't depend on any changed classes (not directly anyway)

**Comment by spannerman79** [comment]
> can you see if this works with build 107 of Numina please?

I will in (my) morning.  I'm UTC+10.

**Comment by MachineMuse** [comment]
ok, take your time lol

**Comment by spannerman79** [comment]
I grabbed the builds (obvious not dev) from http://build.technicpack.net/view/MachineMuse/job/ModularPowersuits/197/ and no issues server side.

Closing issue.

**Comment by MachineMuse** [comment]
yay thanks
