### ISSUE TITLE
Dependencies need an update

### ISSUE THREAD

**Issue by Xen1290** [MachineMuse/MachineMusePowersuits#582]
Hi @MachineMuse and welcome back!
As title says, some dependencies need ad update, because are VERY old: (from build.gradle)
getLibrary("CoFHCore-[1.7.10]3.0.0B2-dev-24.jar") ---> CoFHCore-[1.7.10]3.0.3-303-dev.jar
getLibrary("industrialcraft-2-2.2.765-experimental-api.jar") ---> Ok!
//getLibrary("Atomic-Science-1.1.0.16-api.zip") This mod no longer exists, now is merged in Resonant Induction, but for 1.7.10 isn't out yet.
//getLibrary("ThermalExpansion-API-2.3.0b.zip") ---> ThermalExpansion-[1.7.10]4.0.3B1-218-dev.jar
//getLibrary("CoFHCore-API.zip") ---> Useless, you have already CoFHCore
//getLibrary("CoFHLib-pre1.zip") ---> If you have CoFHCore installed, this is useless, because CoFHCore contains CoFHLib
getLibrary("GalacticraftCore-Dev-BETA-1.7-3.0.1.8-noassets.jar") ---> 	GalacticraftCore-Dev-1.7-3.0.12.168.jar
//getLibrary("Railcraft_API_latest.zip") ---> Railcraft_1.7.10-9.7.0.0-api.zip
//getLibrary("MFR-API-2.5.2B2-642.zip") ---> MineFactoryReloaded-[1.7.10]2.8.0-104-API.zip
getLibrary("forestry_1.7.10-3.4.0.7-api.jar") ---> Ok, maybe update to forestry_1.7.10-3.6.3.20-api.jar
getLibrary("Thaumcraft-API-4.2.0.0-Compiled.jar") ---> Thaumcraft-API-4.2.3.5-Compiled.jar
//getLibrary("MFFS2_API.zip") ---> MFFS for 1.7.10 is in Early Alpha and has no updates since Jul 6, 2014
getLibrary("SmartRender-1.7.10-2.1.jar") ---> Ok!
getLibrary("RenderPlayerAPI-1.7.10-1.4.jar") ---> Ok!

Also, the QMX fork (https://github.com/QMXTech) has done some things for ModularPowerSuit, Numina and ModularPowerSuitAddons, are you consider to merge partially or completely his changes?

P.S. in http://machinemuse.net/download.php you should add a version for 1.7.10, the page still says: "MPS itself is not updated yet."

I hope this help you.

Sorry for any english errors.

**Comment by MachineMuse** [comment]
Thanks for going through and checking them all for me. I did notice that there were some commented-out duplicates. This will make it a little quicker to update.

As to your other questions: I can't use the QMX code for various reasons: different license & copyright, different design philosophy, sometimes adding dependencies or changing/duplicating large amounts of code unnecessarily, massive numbers of commits with useless comments so I can't even cherry pick the changes that are useful.

If there are any QMX additions that you'd like me to try and replicate, and there isn't already an issue on the tracker for them, you have permission to open a ticket.

For my website: I want to fix a couple more things before I make an official 1.7.10 beta release - then I'll have it on my website and upload it to Curse as well.

**Comment by Xen1290** [comment]
@MachineMuse Thanks for your answers!
I haven't noticed QMX problems, thanks for letting me know. And you are right, QMX fork have much commits and copied code. The only things that QMX has added/fixed and for me are useful: (I don't know if you have already fixed this thing):
- Fixed OmniWrench: Now works with EnderIO (a little too much...*), MineFactoryReloaded, CoFH (ThermalExpansion & ThermalFoundation), BuildCraft, Railcraft and (should but untested) IC2!

Since you've been gone, I used QMX Fork primarily for wrench, it was very convenient for me.
Now that you are back, I immediately switched on your version.

And what about MPS Addons?  I think you should merge MPS Addons into MPS, the only version that exist, is dead. (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293401-modular-powersuits-addons-mpsa-requires-modular)

Thanks for all.

**Comment by aionys** [comment]
I started using the QMX fork because it fixed the crash with the AE2 Wireless Terminal crash in the MPSA module.

I would like to second the request to merge Andrew's addons, since it seems like nobody- including Andrew- is working on it anymore, and those addons are uber useful.

**Comment by MachineMuse** [comment]
ok, I added everything from the OpenComputers Srench to it. I might have made a typo or something but it works on everything that I've tested it with. Hopefully that should satisfy you, at least for a bit :)

**Comment by Xen1290** [comment]
Thanks !! @MachineMuse 
P.s I think you have missed two dipendencies that need an update:
CoFHCore And GalacticraftCore

**Comment by MachineMuse** [comment]
Hm, the version you gave for GalacticraftCore doesn't exist. I picked up the latest one from their website.

You're right about CoFHCore, I missed that one somehow.

**Comment by Xen1290** [comment]
@MachineMuse it is in Galacticraft jenkins, see here:
http://ci.micdoodle8.com
Under "Galacticraft3-dev" i think that the website for developer download is broken.

**Comment by Xen1290** [comment]
I've opened a ticket for that problem: https://github.com/micdoodle8/Galacticraft/issues/1829

**Comment by MachineMuse** [comment]
ok, well, got it for now anyway. Thanks for your help again :)

**Comment by Xen1290** [comment]
No problem :+1:
