### ISSUE TITLE
[Suggestion]Make the recipe file auto-extracted from the jar in the recipe folder 

### ISSUE THREAD

**Issue by Xen1290** [MachineMuse/MachineMusePowersuits#584]
Title says all! @MachineMuse 
I think is a good thing to avoid user errors

**Comment by Razorskills** [comment]
And only if it is missing, then if a user edits the files and changes recipes. It doesnt overwrite changes. 

If someone wants to disable that recipe set,  perhaps they could disable the auto extract via the config for "ic2",  etc..

**Comment by MachineMuse** [comment]
Problems with that:
- every user has a different setup. I originally had it so that it would automatically determine which recipes to use based on what mods they had installed, but people continued to surprise me with new configurations.
- auto-extracting based on what files are already in the recipes folder is not going to work because some people/packs/servers will have entirely custom recipes, some of which might not be related to MPS.

**Comment by MachineMuse** [comment]
I can maybe think of a way around this but it's not so simple :P

**Comment by Xen1290** [comment]
I think you could do a recipes file reset/config reset in the next major release (EnderIO did this when switched from MJ to RF) in this case 0.12
In practise, at first installation the mod extract the files, and regen it only if the recipes files are eliminated
I think is the best bet, maybe with this major update, add more config options(ex. Difficulty multiplayer for Items used in tinker table)or similar

**Comment by MachineMuse** [comment]
ok, it now has the following behaviour:
IF there is a config option 'Auto-extract recipes' and it is set to false, then it will not do anything.
If the config option doesn't exist, it will create one and set it to false, but still extract recipes.
If the config option is set to true, it will extract recipes every time.

Extracting recipes goes like this:
If IC2 is detected, it extracts the IC2 recipes.
If ThermalExpansion is detected, it extracts ThermalExpansion recipes. (So you can have both if you have both installed.)
If neither of them are detected, then it will extract Vanilla recipes.

That should be good enough for now. More complex behaviour might be needed if e.g. AE2, Gregtech, Mekanism recipes are added.

**Comment by Xen1290** [comment]
Awesome! Thanks a lot

**Comment by Xen1290** [comment]
One question, if I install ic2 And then after the first launch TE4 I only get ic2 recipes?

**Comment by MachineMuse** [comment]
It will only extract recipes once, unless you change the config file.

Any recipes that fail to generate simply won't be available iirc.
