### ISSUE TITLE
Merge in MPS-addons

### ISSUE THREAD

**Issue by MachineMuse** [MachineMuse/MachineMusePowersuits#586]
I would like to improve the localization and configuration options first but this is on the agenda.

**Comment by Xen1290** [comment]
I've made a list of possible addons, to help you and collect some addons suggestions, take a look and don't panic, MPSA for 1.7.10 (QMX or not has 95% of this done)!

- Kinetic Generator (Leggins)
 The Kinetic Generator is by far the most powerful generator. It generates energy based on the movement of the player. Its base stats are 1kg of weight and an energy value of "200", but these are tinkerable up to 4kg and "800".
The generator will produce the amount of its "power value" every 5 blocks the player moves. It will also generate 5 units of heat. This means that traveling too fast could leave you overheating very quickly.

- Solar Generator (Category: Energy - Helmet)
The Solar Generator, as the name suggests, will generate energy based on primarily sunlight, but also moonlight. It has base energy values of "1500" during the day and "150" during the night. Every four seconds, provided the player can see the sky and it is not raining, the module will generate either the daytime or the nighttime energy. 

- Thermal Generator (Category: Energy - Chestplate)
The Thermal Generator will generate energy based on your heat level. It has base values of 1kg and "25" energy and is tinkerable up to 2kg and "50" energy. Every second, the module will check for one of three conditions, in this order.
    The player is on fire. If so, it will generate 4x the "base energy" value.
    The player's current heat level is above 200. If so, it will generate 2x the "base energy" value.
    The player's current heat level is above 50% of the player's heat capacity. If so, it will generate the "base energy" value.
	
- Auto-Feeder(Category: Environment - Helmet)
The Auto-Feeder module will make sure that you never go hungry. If the player becomes hungry, it will "eat" the first item it finds in the player's inventory, starting from the bottom left. The excess food points that are gained from this food will be stored in the module for later use. 

- Clock (Category: Special - Helmet)
The clock module will add a clock to your HUD that will update realtime with your world. It also displays either a 12hour or 24hour time. (Editable in config, the default is a 12hour system). 

- Compass (Category: Special - Helmet)
The compass module will add a compass to your HUD that will update realtime with your world. It acts just like the compass from vanilla but will always be available to you. 

- EU Reader (Category: Energy - Power Fist)
The EU reader module is only activated if you have IndustrialCraft installed. Just like the EU Reader from IndustrialCraft, it will allow you to get energy readings on any IC2 wire or machine. 

- Flint and Steel (Category: Tool - Power Fist)
 The Flint and Steel module will act just like vanilla Flint and Steel, allowing you to create an almost infinite supply of fire.

- In Place Assembler (Category: Special - Power Fist)
The In Place Assembler allows you to carry around a 3x3 crafting table with you at all times. Whenever you want to craft something, all you have to do is activate it from your power tool. Items will drop from the inventory if you exit out of it, just like a normal crafting table. 

- Leaf Blower (Category: Tool - Power Fist)
The Leaf Blower will help clear out large areas of plants, tall grass, or leaves. Its radius is configurable from 1 to 3, (3x3 -> 9x9). This will remind some people of the sickle from Redpower 2. 

- Lightning Summoner (Category: Weapon - Power Fist)
The Lightning Summoner allows the player to spawn lightning at any position. It has a very high energy cost though and it will give you an extreme amount of heat (100), which can be deadly if you don't have any heatsinks installed.

- Magnet (Category: Special - Chestplate)
The Magnet module works just like NEI's magnet mode. It will draw and items towards the player within a 6 block radius. It has a constant energy drain though so it is suggested that you bind this module to a key for activation/deactivation. 

- Mob Repulsor (Category: Environment - Chestplate)
The Mob Repulsor will keep all mobs away from you, as well as arrows. No matter how hard they try, the mobs will never be able to touch you. Works similarly to the interdiction torch from Equivalent Exchange 2. 

- Ore Scanner (Category: Tool - Power Fist)
The Ore Scanner module will give you a detailed reading of how valuable the land is around you. It is configurable from 3x3 -> 9x9. Each block that is scanned takes 50 energy. It supports almost every mod ore. A chart for the values can be found here. This is probably my favorite and most useful modules, give it a shot! 

- Thermal Expansion Multimeter (Category: Tool - Power Fist)
Like the name suggests, this module will act just like a multimeter from Thermal Expansion. More info can be found on the Thermal Expansion wiki here. 

- Water Tank (Category: Environment - Chestplate)
The Water Tank module offers an additional option to cool your powersuit. By default, it has a capacity of 200 (we'll call it buckets but the water in this case doesn't really have a unit) buckets and 1kg of weight. It can be tinkered to 1000 buckets and 5kg max. To fill up your water tank, all you have to do is stand in water and it will fill up 20b/s (buckets per second). Now this module won't do much during your day to day activity, but if you manage to generate enough heat that you are above your maximum it will automatically turn on and beginning draining to the water to cool you down even quicker. Each unit of water translates to 1 heat unit, so when it turns on you will automatically begin losing 20b/s, but also 20heat/s. This will stop when either 1. You fall below you maximum heat level, where it returns to normal cooling methods, or 2. When you run out of water. 

- Treetap (Category: Tool - Power Fist)
The Treetap module works exactly like the treetap from IndustrialCraft. More information can be found here. 

- Dimensional Tear Generator (Category: Tool Power Fist)
Generate a tear in the space-time continuum that will teleport the player to its relative coordinates in the nether or overworld.

Components to add

- Solar Panel http://i.imgur.com/A541pzr.png
"A light sensitive device that will generate electricity from the sun." 

- Magnet http://i.imgur.com/eaKw8xS.png
"A metallic device that generates a magnetic field which pulls items towards the player." 

- Computer Chip http://i.imgur.com/lKyV7da.png
"An upgraded control circuit that contains a CPU which is capable of more advanced calculations."

- Insulated Rubber Hose (QMX/1.7.10 port)
"A heavily insulated rubber hose capable of withstanding extreme heat or cold."

- Liquid Nitrogen Bucket (QMX/1.7.10 port)
"A bucket of Liquid Nitrogen."


Those are from here: (removed useless module, torch placer)
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1290570-1-5-2-modular-powersuits-addons-mpsa-requires

Maybe new addons: (QMX Forks or similar)

- ME Wireless Terminal (Category: Tool - Power Fist - Applied Energistics)
Works like a ME Wireless Terminal

- ME Fluid Wireless Terminal (Category: Tool - Power Fist - ExtraCells2)
Works like a ME Fluid Wireless Terminal

- Personal Shrinking Device Category: Tool - Power Fist - Compact Machines)
Works like an Personal Shrinking Device

- Apiarist Armor (Category: Armor Forestry, in all armor parts)
Give Apiarist Armor effects if installed in all armor parts

- Mechanical Assistance (Chestplate)
Robotic assistance to reduce the effect of weight on the user

- Liquid Nitrogen Cooling System (Chestplate)
Cools down heat-producing modules even faster than the standard cooling system.

- High Efficiency Solar Generator(Helmet)
A solar generator with 3 times the power generation of the standard solar generator.

- Airlight Seal (Category: Environment - Helmet)
Seal the suit against hostile atmospheres for venturing to other planets.

- Engineer's Hammer functionality to wrench (Immersive Engineering)

- iWrench funcionality to wrench (Funky Locomotion)

- AppEng Network Tool (Applied Energistics 2 Category: Tool - Power Fist)
Works as Applied Energistics 2 Network Tool4

- Chisel Tool (Chisel - Category: Tool - Power Fist)

**Comment by Pinkbyte** [comment]
I like this idea. I also have one module, that i have not sent pull request on - scoop from Forestry.
A someway ready to use code can be found at my little fork, branch forestry-scoop - https://github.com/Pinkbyte/MachineMusePowersuits/commit/cf0f2d091371d1cc2ea284b2056110d863f223df

It's one commit actually and, as Forestry fixes from my fork was already merged upstream, it's not very hard to implement this module. Not sure about the balance(e.g. price of installing of the module), though.

@MachineMuse, your thoughts?

**Comment by Xen1290** [comment]
+1 For scoop module ! Very useful.

**Comment by MachineMuse** [comment]
Looks fine Pinkbyte. Want to patch it a bit with the way I changed the localization and send a pull request?

**Comment by Pinkbyte** [comment]
Okay, see https://github.com/MachineMuse/MachineMusePowersuits/pull/622

**Comment by lehjr** [comment]
For me, merging the addons seems to be easier than getting MPS to run in a dev environment. I expected things like having to disable one of the chisel mods, having to delete the outdated Buildcraft API in Railcraft, or having to add the CoFH access transformers, even the Intellij 1.4 bug (not loading resources), I just didn't expect to have to decompile, fix and recompile Smart Render because of a bug: 
if(minecraft.theWorld != null && minecraft.theWorld.isClient)  

Luckily, Galacticraft has enough of the code in their mod so that cleaning up the decompiled code wasn't necessary. Anyway, this is my progress so far (it's not pretty but it has working things like AE2 and EC2 wireless terminals): https://github.com/lehjr/MachineMusePowersuits/tree/quick-n-dirty-mpsa-merge

Please note that it should not be taken as a serious effort, and normally I wouldn't display such a mess, but I thought it might be useful since the AE2 wireless terminals and a few other things are working. I also have AE2-RV3 compatible code in a fork of QMX-MPSA that I haven't added to this experiment yet.

**Comment by Xen1290** [comment]
@lehjr make a pull request to experimental branch, so it's easier to show what you have done.
Also I agree with you for the development evironment think the old chisel compatibility can go away.
@MachineMuse

**Comment by lehjr** [comment]
@Xen1290  It's nowhere near ready for a PR. It's more of a demo at the moment. Once I get more things working and clean it up a bit I'll do a proper commit. Also, as far as I can tell, both forks of chisel are actively being worked on, so it makes picking one a bit harder.

**Comment by Xen1290** [comment]
@lehjr ah no problems, for chisel, as far as I can see, chisel 2 isn't updated since september, and 2/3 of chisel 2 team is now working in chisel.

**Comment by lehjr** [comment]
Well, pretty much done. Maybe not as good as it could be, but nearly everything works.

**Comment by flowtender** [comment]
Ok, gonna close this since it's been merged in :)
