### ISSUE TITLE
Kill MJ compatibility

### ISSUE THREAD

**Issue by Adaptivity** [MachineMuse/MachineMusePowersuits#587]
Welcome back @MachineMuse! MJ is dead as electricity system. You definitely should remove it.
Also, remove Basic Components and Omni Tools compat. These are still here: https://github.com/MachineMuse/MachineMusePowersuits/blob/experimental/src/main/scala/net/machinemuse/powersuits/common/ModCompatibility.java
https://github.com/MachineMuse/MachineMusePowersuits/blob/cd1af7e298ddbfd08211ed73f5942c370418515d/src/main/scala/net/machinemuse/powersuits/powermodule/tool/MultimeterModule.java You might want to kill this too.

**Comment by Xen1290** [comment]
Also UE (universal electricity) is dead

**Comment by MachineMuse** [comment]
Thanks!

**Comment by Adaptivity** [comment]
You are not removed MJ references. There are no mods running on MJ (Even BC switched to RF)

**Comment by MachineMuse** [comment]
ok, I nixed some more of them...did I still miss any?

**Comment by Adaptivity** [comment]
You removed all of them now. Thanks.

**Comment by MachineMuse** [comment]
cool :)
