### ISSUE TITLE
Power Fist Crash On Startup

### ISSUE THREAD

**Issue by RoloEdits** [MachineMuse/MachineMusePowersuits#588]
http://pastebin.com/W14N2n0d

**Comment by MachineMuse** [comment]
Hello,

I think this is due to a change in the EnderIO API. Can you try it with EnderIO build 408 or greater?

**Comment by 31trainman** [comment]
Im seeing this same crash with mfr version 2.8.0-104 and EnderIO v 381 with forge 1492

**Comment by MachineMuse** [comment]
Can you try it with EnderIO build 408 or greater?

**Comment by 31trainman** [comment]
I can't find that version otherwise I would

**Comment by 31trainman** [comment]
ok disabled mfr and EnderIO and it loaded

**Comment by Xen1290** [comment]
You find enderio 2.3.x on jenkins, here: 
http://ci.tterrag.com/job/EnderIO/

**Comment by RoloEdits** [comment]
Ender io builds past 393 require ender core and right now it conflicts with ttcore that other mods use and have not switched yet.

**Comment by MachineMuse** [comment]
I rolled back to version 381. The api didn't change.

**Comment by 31trainman** [comment]
still got mfr to deal with then

**Comment by MachineMuse** [comment]
if MFR causes a different crash then I need that log as well.

**Comment by 31trainman** [comment]
Looks like mfr and EnderIO together cause a crash although I'm also running other mods

**Comment by 31trainman** [comment]
Logs of crash http://pastebin.com

**Comment by 31trainman** [comment]
logs http://pastebin.com/xFuNrbDz

**Comment by RoloEdits** [comment]
still getting crash with EnderIO-1.7.10-2.3.0.408_beta

http://pastebin.com/ryAPfL24

im using versions

ModularPowersuits-0.11.0.234

Numina-0.4.0.122

**Comment by MachineMuse** [comment]
oh, I'm dumb. It's a load order issue >.<

**Comment by 31trainman** [comment]
I forgot what sleep was long ago, but I'm glad to hear you fixed the problem.

**Comment by MachineMuse** [comment]
Build 236 should fix this.

**Comment by MachineMuse** [comment]
the enderIO API did change but it was a much longer time ago. Anyway closing, please post another issue if it happens again
