### ISSUE TITLE
Crash with new Chisel fork.

### ISSUE THREAD

**Issue by ironclaw2000** [MachineMuse/MachineMusePowersuits#591]
Here is the log and list of installed mods. As I said, I am trying to run this with the new Chisel fork, and it crahes with a NoClassDefFoundError for the Chisel item. 

http://openeye.openmods.info/crashes/82ba9834e35d1c6d89b59f6595636f73

**Comment by Xen1290** [comment]
@MachineMuse 
i think that you should pass to the new fork, 2/3 of Chisel2 devs are in this fork:
http://minecraft.curseforge.com/mc-mods/235279-chisel
But this also break things, because not everybody switched to the new fork

**Comment by MachineMuse** [comment]
That's really annoying :/

**Comment by MachineMuse** [comment]
I put a try/catch around it as a temporary fix, I'll see if I can support both versions somehow.

**Comment by MachineMuse** [comment]
ok, I think I got it. Can you try build 249 for me?

**Comment by ironclaw2000** [comment]
Still crashes with the same error. http://openeye.openmods.info/crashes/bc094d690708b4f0de1b944e1c34690f

**Comment by MachineMuse** [comment]
ok, after trying a few things, build 253 seems to have done it. I tested on my end :)
