### ISSUE TITLE
Use ore dictionary in recipes as much as possible

### ISSUE THREAD

**Issue by Adaptivity** [MachineMuse/MachineMusePowersuits#594]
Just checked recipes files. There a lot of stuff which is not using oredict but could use it. Some simple things like item.ingotIron, item.diamond, item.redstone should use oredict. All stuff registered in Forge: https://github.com/MinecraftForge/MinecraftForge/blob/3331d2a496dcd69c0728539d740f6cf4bb46d98c/src/main/java/net/minecraftforge/oredict/OreDictionary.java#L59
Also, I've noticed that some TE unlocalized item names (like item.thermalexpansion.material.powerCoilGold) have missing ".name" at the end (They have ".name" in TE [en_US.lang](https://github.com/CoFH/ThermalExpansion-Localization/blob/master/en_US.lang#L300)). Are they correct?
P.S Gradle wrapper is outdated in this repository. Maybe you should update this?

**Comment by MachineMuse** [comment]
The TE items are correct; the .name is added on the end when using it for tooltips etc. However, it would be better to switch to their registry names now, as unlocalizedName is deprecated.

I patched everything in the vanilla file. IC2 and TE-specific items are still using unlocalizedNames though. Maybe I'll get to them eventually but I'd appreciate a pull request :P

**Comment by Adaptivity** [comment]
I'll take a look at other recipes files tomorrow.
