### ISSUE TITLE
Question about recipes

### ISSUE THREAD

**Issue by Xen1290** [MachineMuse/MachineMusePowersuits#597]
@MachineMuse I'm fixing recipes and adding EnderIO releated recipes.
I have one question, how I use metadata? Ex.
{ "unlocalizedName" : "item.thermalexpansion.material.powerCoilSilver" }   becomes
{ "registryName" : "ThermalExpansion:material:2" }
It's right?
If I write this, the recipe doesn't work and appear the item without metadata

**Comment by MachineMuse** [comment]
You need a separate entry inside the braces, like with quantity. Like this:

{ "registryName" : "ThermalExpansion:material", "meta" : 2 }

This is so it can apply metadata regardless of the type of item.

**Comment by Xen1290** [comment]
Thanks!

**Comment by Xen1290** [comment]
@MachineMuse last question, how I include all metadata?
Ex. the LapotronCrystal is rechargable and has 27 metadata

**Comment by MachineMuse** [comment]
If you don't specify a metadata, it will match all of them.

**Comment by Xen1290** [comment]
Ok, thanks! For the other thing?

**Comment by Xen1290** [comment]
Ok, thanks! For the other thing?

**Comment by Xen1290** [comment]
Ok, thanks! For the other thing?
