### ISSUE TITLE
[Bug]Recipes that have items with metadata don't appear on NEI

### ISSUE THREAD

**Issue by Xen1290** [MachineMuse/MachineMusePowersuits#598]
Finally I figured out that thing, related to https://github.com/MachineMuse/MachineMusePowersuits/issues/597 @MachineMuse 
Step to reproduce:
1)Modify a recipe and add an item with metadata, example:

	{
		"ingredients" : [
			[ { "registryName" : "IC2:itemCable", "meta" : 2 }, { "oredictName" : "dustRedstone" }, { "registryName" : "IC2:itemCable", "meta" : 2 } ]
		],
		"result" : {
			"oredictName" : "componentWiring",
			"quantity" : 8
		}
	},
2)Load the game
3)If you try to show the recipe in nei, it doesn't appear, but if you try to craft the recipe exist and works.

**Comment by MachineMuse** [comment]
nice catch, thank you :)

**Comment by Xen1290** [comment]
Thanks !
