### ISSUE TITLE
[Bug] Overlapping Text

### ISSUE THREAD

**Issue by Xen1290** [MachineMuse/MachineMusePowersuits#602]
This image explain itself:
![test](https://cloud.githubusercontent.com/assets/8685029/9566289/33311cee-4f00-11e5-9d7d-da0e5cd48ba2.png)
To fix this, maybe put the value in a newline or something?
@MachineMuse 
This is present in those modules:
Shovel
Axe
Shears
Lux Capacitor
Aqua Affinity
Melee Assistant
Plasma Cannon
Blade Launcher
Blink Drive
And  Energy Storage (You can see this in the image above)

**Comment by MachineMuse** [comment]
Yeah, I think I can do this dynamically. It will take a bit of work.

**Comment by MachineMuse** [comment]
All this fixed and more!

![New visuals](http://puu.sh/k3B1m/77969d92e0.jpg)

**Comment by Xen1290** [comment]
You are awesome! Thanks! @MachineMuse 
Just one thing, the word Storage(Energy Storage) is a little bit plus on the right? 
Or is my impression?

**Comment by MachineMuse** [comment]
Yes, that's on purpose, to show that it's part of the previous 'paragraph'

**Comment by Xen1290** [comment]
Ah ok, perfect, thanks !
