### ISSUE TITLE
[Bug]Wrong configs

### ISSUE THREAD

**Issue by Xen1290** [MachineMuse/MachineMusePowersuits#604]
https://github.com/MachineMuse/MachineMusePowersuits/blob/experimental/src/main/scala/net/machinemuse/powersuits/common/Config.scala#L58-L75

      if (ModCompatibility.isIndustrialCraftLoaded) {
        found=true
        //IC2
        copyRecipe("mps-vanilla.recipes")
      }
      if(!found) {
        //vanilla
        copyRecipe("mps-thermalexpansion.recipes")

IC2 and vanilla files are wrong
@MachineMuse

**Comment by MachineMuse** [comment]
wh..how did that get like that.

**Comment by MachineMuse** [comment]
I need to sleep 

9ddba86df1aee7decca36eab303fc85d94723906
