### ISSUE TITLE
[Bug]Radiation Shielding missing description

### ISSUE THREAD

**Issue by Xen1290** [MachineMuse/MachineMusePowersuits#606]
![test](https://cloud.githubusercontent.com/assets/8685029/9569614/a8f8d4e2-4f70-11e5-9356-3fa21bdf6260.png)

I hope this ticket help you with the develop of this awesome mod!

**Comment by MachineMuse** [comment]
This might be the case with any mod-specific module now that I think of it.

**Comment by MachineMuse** [comment]
Yeah, when I auto-generated the localization file it didn't include the mod-specific modules for any mod I didn't have in my dev environment >.> should be fixed now.

**Comment by Xen1290** [comment]
Thanks !
