### ISSUE TITLE
Update the NEW version of Power Suit, and Numina, and this console spam:

### ISSUE THREAD

**Issue by Sasikaa** [MachineMuse/MachineMusePowersuits#607]
[09:45:47] [Client thread/WARN] [MachineMuse]: WARNING: unlocalizedName is deprecated; please use registryName or itemStackName instead!

**Comment by aionys** [comment]
It's possible that's from the recipe files. Did you make sure to update those? The old version uses unlocalizedName, IIRC.

**Comment by Sasikaa** [comment]
ModularPowersuits-0.11.0.263.jar is not NEWEST file?

**Comment by Xen1290** [comment]
Update to latest version to have everything fixed. If you have recipes modificated, it's up to you merge your modification with the new recipes

**Comment by aionys** [comment]
Once again, check the RECIPE file(s), in your config folder, and make sure they've been updated.

**Comment by MachineMuse** [comment]
Alternatively: delete all recipes and set the auto-extract recipes config option to True

**Comment by MachineMuse** [comment]
Also, it shouldn't spam anymore
