### ISSUE TITLE
[Suggestion]Update all MPS/Numina versions to CurseForge

### ISSUE THREAD

**Issue by Xen1290** [MachineMuse/MachineMusePowersuits#611]
As title says, when the first release of MPS will be out, you could delete the betas on curseforge, and before update the release, add the old versions to curseforge(1.4.7,1.5.2,1.6.4 versions, in order), and then the 1.7.10 release? This helps the users who uses the curse launcher for creating a pack with older versions)
@MachineMuse 
Sorry for possible english mistakes, I hope you have understood

**Comment by MachineMuse** [comment]
Do people actually do that

**Comment by Razorskills** [comment]
Some do. Not alot, but its hard if there is no mods uploaded for them to use. Lol

**Comment by MachineMuse** [comment]
I guess it wouldn't be that difficult since I kept the old versions on my website

**Comment by Xen1290** [comment]
Thanks!

 P.S. the 1.6.4 on your site isn't the last,  http://build.technicpack.net/view/MachineMuse/job/ModularPowersuits/118/ this is the last, and maybe the other, so if you could check jenkins.

**Comment by MachineMuse** [comment]
The trouble with late 1.6.4 is there were so many changes in preparation for the move to 1.7.10 that the latest version might not be the most stable. But on the other hand, that's what everyone was using, idk.

Mainly I don't want people posting issues about 1.6.4 versions even though I know there were unsolved issues in those versions. :/

**Comment by Xen1290** [comment]
Oh, sorry, no problems :)
