### ISSUE TITLE
[Bug] MV and HV capacitor recipe not working

### ISSUE THREAD

**Issue by wildgift** [MachineMuse/MachineMusePowersuits#612]
Using the latest build (0.11.0.265), all capacitor crafting recipes output the LV capacitor only, as evidenced in the attached screenshots:

![image](https://cloud.githubusercontent.com/assets/14122176/9678367/6fc2edda-52b2-11e5-8091-76863df575cf.png)

![image](https://cloud.githubusercontent.com/assets/14122176/9678375/783e39b0-52b2-11e5-9df0-55b7dfd8fde8.png)

**Comment by Xen1290** [comment]
Numina version?
@wildgift

**Comment by wildgift** [comment]
Sorry about that! It's 0.4.0.128.

**Comment by Xen1290** [comment]
Yes, confirmed, but this is strange,but.. the recipe file is ok,

	{
		"ingredients" : [
			[  {"oredictName" : "componentWiring" }, { "registryName" : "EnderIO:itemBasicCapacitor" }, {"oredictName" : "componentWiring" } ],
			[  {"oredictName" : "componentWiring" }, null, {"oredictName" : "componentWiring" } ]
		],
		"result" : {
			"oredictName" : "componentLVCapacitor"
		}
	},
	{
		"ingredients" : [
			[  {"oredictName" : "componentWiring" }, { "registryName" : "EnderIO:itemBasicCapacitor", "meta" : 1 }, {"oredictName" : "componentWiring" } ],
			[  {"oredictName" : "componentWiring" }, null, {"oredictName" : "componentWiring" } ]
		],
		"result" : {
			"oredictName" : "componentMVCapacitor"
		}
	},
	{
		"ingredients" : [
			[  {"oredictName" : "componentWiring" }, { "registryName" : "EnderIO:itemBasicCapacitor", "meta" : 2 }, {"oredictName" : "componentWiring" } ],
			[  {"oredictName" : "componentWiring" }, null, {"oredictName" : "componentWiring" } ]
		],
		"result" : {
			"oredictName" : "componentHVCapacitor"
		}
	},

I think is a problem with json reader or something, @MachineMuse ? Other recipes work, only this with capacitors, an in NEI the recipe appear right.

**Comment by MachineMuse** [comment]
whoops, that's an important aspect of Numina's item matching: if it doesn't include a metadata value, it will match any metadata value. So you need to specify "meta" : 0 if there are other meta values for that item.

In any case, I fixed this in the EnderIO recipes. They will have to be re-generated. If it happens with other recipes, please let me know!
