### ISSUE TITLE
[Bug] Omni wrench module issues

### ISSUE THREAD

**Issue by wildgift** [MachineMuse/MachineMusePowersuits#613]
The wrench module doesn't currently dismantle placed machines, it only turns them. Is this a bug or a feature? I've also found that it doesn't work at all with my Mekanism machines, only TE and EnderIO. I'm using MPS version 0.11.0.265 and Numina 0.4.0.128.

Edit: I just checked it on a Mekanism machine again, and it does work to turn those. The first problem still stands though. :)

**Comment by Xen1290** [comment]
Confirmed, thanks for report, but for me only the dismantle thing doesn't work. @MachineMuse

**Comment by MachineMuse** [comment]
ok, I ripped off the CoFH Redstone Arsenal wrench code to make it functional for now.
