### ISSUE TITLE
Power Tool scrolling not working?

### ISSUE THREAD

**Issue by Stalkstalks** [MachineMuse/MachineMusePowersuits#615]
The power tool displays a scroll arrow at the bottom, unlike the armor parts. The top of the ender teleportation function is visible, and can be clicked on, and functions. However, nothing I do seems to actually scroll the list down any further. 

(I am not sure if this is because, without MMPS addons, there aren't any components below the ender teleportation anymore, or there are some more that I just don't remember that I haven't been able to install because the list won't scroll.)

The list should either scroll to where the last item is fully visible and then stop displaying the scroll arrow, or the scroll arrow should not be visible to begin with.

**Comment by MachineMuse** [comment]
Mousewheel over the item scroll frame

**Comment by MachineMuse** [comment]
good point though, I had code in there for when you click on the button, but it wasn't being used. So that's fixed now. thanks for the catch!

**Comment by Stalkstalks** [comment]
I did actually mousewheel over it, because that's what I remembered working in earlier versions and the unofficial QMX port. It didn't work, which surprised and confused me.

Is the ender teleportation module the last one on the list in the current releases?

**Comment by MachineMuse** [comment]
Yeah.

Mousewheel not working either? It is for me (both on a server with lots of mods, and in my test environment). Can you test with the latest build on Jenkins? Also try (left)clicking on the arrow as that functionality was just fixed.
