### ISSUE TITLE
Cloaking component not visible in keybinds?

### ISSUE THREAD

**Issue by Stalkstalks** [MachineMuse/MachineMusePowersuits#616]
I was tooling around with the new official release in creative mode and installed more or less everything. The cloaking component was working - I was invisible - but it did not show up among the many other components on the keybind menu. It just ran all the time with no way to turn it off other than to uninstall it.

**Comment by MachineMuse** [comment]
It shows up for me?
![screenshot](http://puu.sh/k3oK2/e45e652d1f.jpg)
(attached to K)

You can hold shift with your mouse over modules to get tooltips. I should probably make that part of the instructions.
