### ISSUE TITLE
Cannot charge power suit battery (EU)

### ISSUE THREAD

**Issue by musznik** [MachineMuse/MachineMusePowersuits#617]
Symptom : batteries are full, but indicator (on right side) doesn't seem to verify this and is showing capacity from nowhere? I have to replace battery every time.

I can charge suit using Energetic Infuser
Modpack : Resonant Rise + industrialcraft-2-2.2.770-experimental

Video : https://www.youtube.com/watch?v=xRVb8--RCmA

**Comment by MachineMuse** [comment]
strange, I might have messed up the IC2 compat since I didn't check it too carefully.

**Comment by Pinkbyte** [comment]
I have workarounded that by partially reverting 15cedba, see Pinkbyte/MachineMusePowersuits@5222f3b2af43f3e8fc7345f992bf42ee066fe9bc

Basicly - if item does not have IElectricItem interface(or ISpecialElectricItem in our case) - it can not be charged in BatBoxes,MFUs and so on...

**Comment by MachineMuse** [comment]
oh, yeah I forgot, please don't post issues with versions in modpacks that aren't the latest experimental
