### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Ashen44** [MachineMuse/MachineMusePowersuits#618]
I'm trying to use this mod, I'm on mac, yet whenever I start up my minecraft with this mod, it crashes and the crash log says the error is within the mod. I have tested it with no other mods installed and it still crashes. I am using Forge 10.13.4.1448, with Numina version 0.4.0.119 and powersuits 0.11.0.265.
Crash Log: http://pastebin.com/u6fibRpp

**Comment by Xen1290** [comment]
Update Numina to latest beta version. Also a crash report is needed to figure out the causes of crash

**Comment by Ashen44** [comment]
sorry, forgot to add that, will put it in, and also forgot to add, already tested it with the latest version of numina, still crashes

**Comment by MachineMuse** [comment]
That's a Java7 function. It makes things a lot less complicated on my end.

Make sure you are using an up to date JVM. Java 8 is better for security reasons, but Java 6 is deprecated at this point and lots of mods require minimum Java 7.
