### ISSUE TITLE
Player gets hit by Plasma Cannon if he fires a small plasm ball upwards

### ISSUE THREAD

**Issue by EzerArch** [MachineMuse/MachineMusePowersuits#619]
If the player aims at a vertical rotation between -60 and -90 (towards the head) and fires a small plasma ball, the projectile hits the player.

![2015-01-09_03 13 18](https://cloud.githubusercontent.com/assets/6743303/9722580/31d3711c-5586-11e5-99ad-46a37c216eba.png)

It seems the game understands that the projectile overlaps the player hitbox at such angle, hurting the player, but firing a full charge plasma ball won't hit the player.

**Comment by MachineMuse** [comment]
ok, I just added a check to see if the entity collision is the one who fired it.

I originally tried to work around this issue because I thought it was a good idea to let players run into their own plasma bolts if they're running too fast, but it's simpler and less annoying to do it this way.
