### ISSUE TITLE
recipes shown do not work

### ISSUE THREAD

**Issue by tekman123** [MachineMuse/MachineMusePowersuits#626]
I'm using the latest version of MPS and the following recipes that show up in NEI don't work at all.  LV, MV, HV Capacitors, Servo Motor, Parachute, Forcefield Emitter and Control circuit.  A lot of the recipes for these items either show up as the same recipe for me and others on my server or if they look right they don't work.  The recipes show up correctly in the .recipes file shipped with the mod but they don't show up in game the same way

**Comment by Razorskills** [comment]
Please provide mod versions for, MPS and Numina

Then check if your versions are up to date. If thet are not, then do an update, if your still having issues with recipes after that, make sure mincraft is closed, delete the recipes and go to the mps config and set generate configs to true and relaunch. 

If it is still a problem after that, then post that you tried this here and someone will help find the cause.

**Comment by MachineMuse** [comment]
Please configure your server correctly
