### ISSUE TITLE
OmniWrenchModule crash with IC2 Tile

### ISSUE THREAD

**Issue by leagris** [MachineMuse/MachineMusePowersuits#627]
Attempt to wrench (right click) an IC2 Energy-O-mat with an Omniwrench module caused a client crash:
[crash-2015-09-20_16.44.26-client.txt](https://gist.github.com/leagris/6e204ef5a0d49e03474e)

**Comment by flowtender** [comment]
Crashlog has been taken down - sorry it too me so long to get to it :( I'll try to reproduce but if I can't then I will close this unless I get another one from someone

**Comment by leagris** [comment]
Here is another one new:
[crash-2015-11-21_14.29.39-client.txt](https://gist.github.com/leagris/80b93d00a2c70f6ebe95#file-crash-2015-11-21_14-29-39-client-txt)

**Comment by flowtender** [comment]
thanks!

**Comment by leagris** [comment]
Is it fixed now?

**Comment by lehjr** [comment]
It may or may not be. The issue is well over a year old with no further input and 1.7.10 support is coming to an end. There currently is no OmniWrench module in 1.10.2 builds due to dependency on Buildcraft.
