### ISSUE TITLE
Armor can't be charged in EnderIO Capacitor bank

### ISSUE THREAD

**Issue by bence98** [MachineMuse/MachineMusePowersuits#629]
First off: I'm using MPS 0.11.0.283, Numina 0.4.0.119, EnderIO 2.2.8.381
Second off: I can't charge my chestplate. It has an elite battery installed with battery size tinkered to max. It seems to have come with 50% charge but it won't last long. I can't insert it into EIO's capacitor banks' charge slots. I also couldn't (with MPS .281) charge it with IC2, it showed EU going in, but was not converted to actual charge of armor, it just said something like:
Energy: 2.2M/5M
1.25M/1.25M EU
on the tooltip. I'm guessing it became "stuck" in the armor's EU conversion buffer?
Thanks in advance.

**Comment by cornytrace** [comment]
Just want to say I have the same problem, the energy which is being charged isn't the same energy that is actually being used by the suit.

**Comment by japherwocky** [comment]
We're also having this problem in our server pack - ender IO seems unable to charge the power suit items.

**Comment by mathwizi2005** [comment]
Just wanna leave this here that the QMX build of MPS works in all charging stations (yes, even Ender IO caps
(specifically, DW20 1.7.0 and the latest QMX build. Should help identify the issue)

**Comment by Xen1290** [comment]
I think this is fixed with MSPA Merged
@MachineMuse

**Comment by flowtender** [comment]
ok, thanks!
