### ISSUE TITLE
Radiation Shielding does not work with ic2 radiation for 1.7.10 when gregtech is installed

### ISSUE THREAD

**Issue by spacebuilder2020** [MachineMuse/MachineMusePowersuits#631]
Holding a mox fuel cell will still poison you with power armor on and radiation shielding enabled.

**Comment by Xen1290** [comment]
What gregtech are you using?
- GregTech 5
- GregTech 6
- TechReborn (GT2-4 port)

**Comment by spacebuilder2020** [comment]
Gregtech 5 Unofficial on the Beyond Reality Modpack V 1.3.4

**Comment by Xen1290** [comment]
And IC2 Version?

**Comment by spacebuilder2020** [comment]
gregtech_1.7.10-5.08.27
industrialcraft-2-2.2.766-experimental
Numina-0.4.0.128
ModularPowersuits-0.11.0.265

**Comment by spacebuilder2020** [comment]
Any progress?

**Comment by flowtender** [comment]
Hello,

Since Gregtech is not opensource and does weird things, I can't really afford to invest the time to dig into how it determines radiation damage, and lehjr is busy porting to 1.8, so I think this is not going to get fixed unless someone else submits a PR. Sorry :(

**Comment by spacebuilder2020** [comment]
Gregtech 1.7.10 Unofficial is on github https://github.com/Blood-Asp/GT5-Unofficial

That is the current version I am using now.

I will see if the bug still exists in the most recent version and let you know.
