### ISSUE TITLE
NEI registration of registryName ingredients not working

### ISSUE THREAD

**Issue by allaryin** [MachineMuse/MachineMusePowersuits#638]
It seems that (at least while using the vanilla material set), any 'registryName' entry in the json is failing to work correctly with NEI. The recipes still work - but NEI does not understand any of the non-oredict vanilla ingredients.

Verified on SSP and SMP.

![2015-11-09_13 21 40](https://cloud.githubusercontent.com/assets/56085/11044161/ceb97ca2-86e5-11e5-8abb-10b1992241be.png)
![2015-11-09_13 22 23](https://cloud.githubusercontent.com/assets/56085/11044157/ceb5669e-86e5-11e5-8354-608e410482ac.png)
![2015-11-09_13 22 32](https://cloud.githubusercontent.com/assets/56085/11044159/ceb8e314-86e5-11e5-9b03-46abe87c4c2d.png)
![2015-11-09_13 26 15](https://cloud.githubusercontent.com/assets/56085/11044160/ceb8f552-86e5-11e5-9858-0701aa49ac7f.png)
![2015-11-09_13 27 18](https://cloud.githubusercontent.com/assets/56085/11044158/ceb5a8f2-86e5-11e5-8739-2a5d67c8786d.png)

**Comment by lehjr** [comment]
What version of Numina are you using?

**Comment by allaryin** [comment]
```
$ md5sum Numina-*jar
eb663b21cfd32b034389b9cde314477e  Numina-0.4.0.119.jar
```

**Comment by lehjr** [comment]
Yeah, that version is broken. The newer versions are on curseforge. 
http://minecraft.curseforge.com/projects/numina/files

**Comment by allaryin** [comment]
Should probably push a working build out to curse then ;) Making sure update to 0.4.0.131 fixes it.

**Comment by allaryin** [comment]
Verified to work in both SSP and SMP, thanks.
