### ISSUE TITLE
Crafting with IC2 + EnderIO

### ISSUE THREAD

**Issue by Morketh** [MachineMuse/MachineMusePowersuits#639]
50% of the recipes are missing/broken and the other half are displayed however they are usable.
 i have tried in both Logistics Pipes Request table and a regular vanilla crafting table.
screen shots of this are available: 
http://ci-main.no-ip.org/PowerSuits/

**Comment by Razorskills** [comment]
http://minecraft.curseforge.com/projects/numina/files

**Comment by Xen1290** [comment]
Please update MPS and numina from. curseforge with latest version, and then, backup and reset the machinemuse config folder, this should work.

**Comment by Morketh** [comment]
Numina in modPack: Numina-0.4.0.119.jar
Numina from Curse forge: Numina-0.4.0.131.jar

MPS version from Curse forge: ModularPowersuits-0.11.0.283.jar
MPS in currant Mod Pack: ModularPowersuits-0.11.0.283.jar

Updating Numina and trying this again thank you guys, also as per #641 a minimum required version error would be a really good idea.

**Comment by Xen1290** [comment]
Fixed the issue @Morketh ?

**Comment by Morketh** [comment]
So far so good @Xen1290 items are craftiable
