### ISSUE TITLE
Adding Key bind to gui crash

### ISSUE THREAD

**Issue by Morketh** [MachineMuse/MachineMusePowersuits#640]
Attempting to add a key bind to the gui (in hopes of seeing what it did) caused a crashed in SMP. As githb doesnt have a spoiler tag i have uploaded the crash log to my private Web Server
http://ci-main.no-ip.org/PowerSuits/crash-2015-11-10_23.00.19-client.txt

**Comment by Razorskills** [comment]
perhaps try updating numina: http://minecraft.curseforge.com/projects/numina/files
even though I think it mostly deals just with the recipes, but worth a quick test just in case since Ive heard of some odd bugs in 119.

then if the problem persists report back?

**Comment by flowtender** [comment]
yeah a nosuchfielderror is definitely a version mismatch. I'm gonna mark this as resolved; if nothing else, adding a minimum required numina version should help.
