### ISSUE TITLE
[Suggestion] Add minimum Numina version 

### ISSUE THREAD

**Issue by lehjr** [MachineMuse/MachineMusePowersuits#641]
I would suggest setting a minimum Numina version as a dependency to minimize reports of bugs already fixed. Might also be a good idea to add a link to readme pointing to the Curseforge builds.

**Comment by lehjr** [comment]
OK, so it looks like the readme for the experimental branch has the link, but since it isn't set as the default branch, it's not the one that people see

**Comment by Xen1290** [comment]
Yeah, good suggestion.

**Comment by flowtender** [comment]
Problem with this is it's hard to put in something that will allow a build script to insert build numbers while not gumming up a development environment. If you know of other mods which have a system to automate this, I would be interested to see them.

**Comment by flowtender** [comment]
lehjr's solution is ok for now. I just wish I could automate it because I am forgetful.

**Comment by lehjr** [comment]
I'd have to experiment with it a little bit, but I'm pretty sure that it's possible to set the minimum version from an environmental variable and have a default as a fallback when not set.

**Comment by lehjr** [comment]
It would probably look something like:

```
@Mod(modid = "powersuits", modLanguage = "scala", dependencies = "required-after:numina@[" + ModularPowersuits.NuminaVersion + ",)")
object ModularPowersuits {
  val NuminaVersion = "${numina_version}"
```

Edit: that should be `final val NuminaVersion = "${numina_version}"`

**Comment by lehjr** [comment]
There's also some stuff that would be in **build.gradle**, but that's the general idea anyway

**Comment by lehjr** [comment]
yeah, turns out it was pretty easy

in build.gradle:

```
archivesBaseName = "${config.mod_id}"
def numina_version = (System.getenv("NUMINA_VERSION") ?:"0.4.0.131")

minecraft {
    version = "${config.minecraft_version}-${config.forge_version}"
    replace "@numina_version@", numina_version
    runDir = "run"
}
```

Then in ModularPowersuits.scala:

```
@Mod(modid = "powersuits", modLanguage = "scala", dependencies = "required-after:numina@[" + ModularPowersuits.NuminaVersion + ",)")
object ModularPowersuits {
  final val NuminaVersion = "@numina_version@"
```

with that, you can set the version from the build environment and have a fallback version just in case it isn't set
