### ISSUE TITLE
[Suggestion] switch default branch to experimental, or update master branch.

### ISSUE THREAD

**Issue by lehjr** [MachineMuse/MachineMusePowersuits#642]
All of the information regarding new builds is in the readme for the experimental branch, as that is where the work is being done, but because this is not set as the default branch, this is not the readme that people land on when visiting the project's page. Instead, users land on a page where the readme  contains no useful information and the last commit was months ago.

**Comment by Xen1290** [comment]
I think that switch the default branch to experimental is better. Master branch is for releases

**Comment by flowtender** [comment]
Good idea! I changed the default branch for the repo to Experimental. Hopefully this won't have any dire consequences!
