### ISSUE TITLE
Ore dic broken - Forge 1558

### ISSUE THREAD

**Issue by spannerman79** [MachineMuse/MachineMusePowersuits#643]
Forge recommended is now 1558 for MC 1.7.10

    [Server thread/WARN] [FML/powersuits]: * A broken ore dictionary registration with name componentArtificialMuscle has occurred. It adds an item (type: class net.machinemuse.powersuits.item.ItemComponent) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
    TO USERS: YES this is a BUG in the mod MachineMuse's Modular Powersuits report it to them!

**Comment by lehjr** [comment]
Was that the only one?

**Comment by spannerman79** [comment]
No there are several more, let me pull my server logs

http://pastebin.com/BvH5vKkD

**Comment by lehjr** [comment]
Thanks. I'll see what I can do later today.

**Comment by lehjr** [comment]
Here's a fixed version: https://github.com/lehjr/MachineMusePowersuits/releases/tag/283d

**Comment by flowtender** [comment]
Closing this since it is apparently fixed in lehjr's mega-PR. We can tackle any issues that arise from that in a new thread :P
