### ISSUE TITLE
Airtight Seal module and some small suggestions?

### ISSUE THREAD

**Issue by Korvynus** [MachineMuse/MachineMusePowersuits#644]
Mods:
ModularPowersuits-0.11.0.283
GalacticraftCore-1.7-3.0.12.402

Forge version:
forge-1.7.10-10.13.4.1517-1.7.10-universal

Issue:
Simply going in space, moon or anything that doesn't have breathable air! The Airtight Seal module doesn't do his job...

Suggestions:
Is it possible to add a new module to replace the Thermal Padding from Galacticraft? Adding magnetic/gravity boot module also would help while in space ...

EDIT 1:
Ok, while looking at the code of both Galacticraft and MPS and doing some other tests ingame. I found that I can go in space without the Oxygen Mask but not the Gear or Tanks. Is it intended behaviour of the Airtight Seal module? Isn't it better to drain energy from MPS batteries instead to make us breath? Idk if it's possible or not but that would be cool to fix that.

**Comment by Korvynus** [comment]
Ok, while looking at the code of both Galacticraft and MPS and doing some other tests ingame. I found that I can go in space without the Oxygen Mask but not the Gear or Tanks. Is it intended behaviour of the Airtight Seal module? Isn't it better to drain energy from MPS batteries instead to make us breath? Idk if it's possible or not but that would be cool to fix that.

**Comment by EzerArch** [comment]
>  Is it intended behaviour of the Airtight Seal module?

It's likely intended. If MPS armor provided infinite oxygen (*) it would simply kill the main goal of Galacticraft: survive in the space. Also, using the GC oxygen mask along with MPS helmet is just abysmally ugly.

* _ unless MPS gets an internal inventory to place oxygen tanks, but this goes beyond MPS scope.

**Comment by Korvynus** [comment]
Ok then, maybe adding an "internal/hidden" oxygen tank inside the MPS armor while showing the remaining oxygen using the oxygen gauges on the hud. Putting the MPS chest inside Oxygen Compressor slot would allow to refill the internal O² tank. Probably hard to do but it would be very fun and cool !

What about the other ideas? Btw there is a visual bug where we can see some part through the MPS armor of the Thermal Padding set. Is there a way in GC config to show/hide the Thermal Padding set?

**Comment by flowtender** [comment]
adding more awful item-manipulation GUIs is counter to my design goals and currently the airtight seal module does its job, which is to allow the player to use the MPS helmet in the place of other modded helmets, not replace any functionality that can be achieved in another way. Sorry :(

When I implemented it, Galacticraft had a separate slot in your inventory for oxygen tanks, so there was no competition for other modded items. Has that changed? If not, then this is a case of working as intended.

If you want more functionality from Galacticraft then you should try to contribute to that project instead. I can't even keep up with MPS by itself without contributing to other mods!
