### ISSUE TITLE
Fix swirly circle selectors in tinker UI

### ISSUE THREAD

**Issue by Xen1290** [MachineMuse/MachineMusePowersuits#645]
See here:
![2015-11-14_14 52 25](https://cloud.githubusercontent.com/assets/8685029/11247724/968ec49c-8e1d-11e5-8fec-a850f9fabfb9.png)

**Comment by flowtender** [comment]
Is 1.4.7 the last version this was working in? O_O I noticed it was missing but I couldn't remember when it stopped working.

This is definitely something worth fixing.

**Comment by Xen1290** [comment]
Last time I saw this thing was in FTBUltimate 1.4.7

**Comment by lehjr** [comment]
Doesn't look like the swirly circle code itself changed, other than being moved into an external lib. Could it be related to changes in LWJGL?

**Comment by flowtender** [comment]
I don't think it's a LWJGL change. More likely something to do with rendering changes in MPS and in core Minecraft

**Comment by lehjr** [comment]
I was messing with this in the 1.8.9 port. Looks like a parameter somewhere isn't right. I got this by changing the alpha setting for one of the color parameters but it doesn't match the pic. The circles do rotate , but it's almost like every other pixel rather than what's in the original setup:

![2016-02-09_19 47 20](https://cloud.githubusercontent.com/assets/1084367/12935763/68869f40-cf66-11e5-9bc1-12375dad74e9.png)

**Comment by flowtender** [comment]
It is kind of a terrible idea in the first place. We may want to replace it with a rastered swirly circle instead of constructing one from GL lines :P

**Comment by lehjr** [comment]
found a video with the swirly circle. At least I know what the animation looks like now: https://youtu.be/BXTL6oEXLeg?t=2m51s

**Comment by seijinshu** [comment]
We have lots of things that stopped working after 1.4.7. I never noticed the swirly circle missing. After implementing the Cosmetic Menu, you could no longer color the power tool.

I'm probably going to fork MPS 1.7.10 and getting things fixed up.

**Comment by lehjr** [comment]
This was fixed today. 
![2017-03-26_19 06 34](https://cloud.githubusercontent.com/assets/1084367/24336129/b1240320-1257-11e7-99ec-a0ef4a90c40d.png)
