### ISSUE TITLE
Broken Ore-Dictionary Registration (as reported by FML 1566)

### ISSUE THREAD

**Issue by Morketh** [MachineMuse/MachineMusePowersuits#647]
A detailed report can be found here: http://ci-main.no-ip.org/minecraft/crashreports/MPS-OreDictionary.txt

**Comment by Xen1290** [comment]
Already fixed when #632 will be merged

**Comment by Morketh** [comment]
does this also include #635? would be a shame to loose that support.

**Comment by Xen1290** [comment]
Yes

**Comment by lehjr** [comment]
Duplicate of https://github.com/MachineMuse/MachineMusePowersuits/issues/643

As far as the IC2 power issue goes, yes, the IC2 power does work on that code there, although I don't know if that will be left or not as I'm not entirely sure why it was disabled in the first place.

**Comment by Morketh** [comment]
@lehjr that issue is for forge 1558 im running 1566 is that still covered under the same problem?

**Comment by lehjr** [comment]
yes.

**Comment by flowtender** [comment]
see #643
