### ISSUE TITLE
Remove the zoom keybind from the game controls

### ISSUE THREAD

**Issue by EzerArch** [MachineMuse/MachineMusePowersuits#649]
From https://github.com/MachineMuse/MachineMusePowersuits/issues/636#issuecomment-158847524:

> There is a something else I think is worth pointing out: you can set a keybind for "Zoom (MPS)" on game controls (default "Y", I've never got it to work) and a keybind for Binoculars at the TInker Table's keybind window. I'd remove the "Zoom (MPS)" from game controls to free up a key.

Please, remove "Zoom (MPS)" from the game controls once it is possible to assign a keybind at the Tinker Table's keybinder to the Binoculars module.

**Comment by EzerArch** [comment]
_New information:_ The "Zoom (MPS)" [default Y] in the game controls is no longer necessary as it doesn't do anything, but still the mod will yell "TAKEN" in the Tinker Table's keybinder if you attempt to use the key assigned to that control.

**Comment by flowtender** [comment]
yep that's definitely an issue! I'm not going to claim it since I don't currently have any time set aside to work on these things but it's a pretty small change to make I think.

**Comment by lehjr** [comment]
fixed in current code. Will be released in next alpha for 1.10.2
