### ISSUE TITLE
[Critical] Fix compiling issue

### ISSUE THREAD

**Issue by Xen1290** [MachineMuse/MachineMusePowersuits#651]
[ModularPowersuits] $ /var/lib/jenkins/workspace/ModularPowersuits/gradlew *******\* build curse -PcurseForgeApiKey=********

FAILURE: Build failed with an exception.
- Where:
  Build file '/var/lib/jenkins/workspace/ModularPowersuits/build.gradle' line: 49
- What went wrong:
  A problem occurred evaluating root project 'ModularPowersuits'.
  
  > http://machinemuse.minecraftforge.net/ExtraCells-deobf-1.7.10-2.3.0b142.jar
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output

<strong>You can find this thing here: http://shadowcity.net:8080/job/ecrv2/ , you should update to 2.3.1, the stable release.</strong>
@MachineMuse

**Comment by lehjr** [comment]
There's also a missing dependency for compact machines (for the personal shirinking device module). There isn't an official dev build, so I built one. https://www.dropbox.com/s/3iq50g2p6m7stow/compactmachines-1.7.10-1.20-dev.jar?dl=0

It might be a good time to look at the list of dependencies and update those if needed.

**Comment by lehjr** [comment]
@Xen1290 I'll probably work on this later today. To me it looks like this :
- 2 missing libs for the build environment (extra cells2 builds seem to be only keeping a couple of versions and dropping old, so pointing to the latest seems to be the best solution; compact machines does not have a dev build so one has to be created and uploaded.)
- missing several other libs for dev environment
- solutions to the above cannot break the Jenkins builds. I have no experience with the Jenkins build system, so I can only assume it's more or less the same as building on any other system.

**Comment by Xen1290** [comment]
The easy way to fix, is to include the Libs directy in the repository, because now it uses a server to download libraries. So with a simple pull request things get fixed.

**Comment by lehjr** [comment]
That would work as long as just the dependencies for building are includied. Including all of the libs for the entire dev environment might be an issue. The other option would be to just change "getLibrary" to allow links to the the dependencies. Currently, the download location is set in project.properties as  `apisource_url=http://machinemuse.minecraftforge.net/`

**Comment by lehjr** [comment]
I was thinking something like this (formatting gets butchered here):

 `def getLibrary(filename, def lib_url=config.apisource_url) {
    def f = new File(config.libs_dir + filename)
    if (!f.exists()) {
        new URL(lib_url + filename).withInputStream{ i -> f.withOutputStream{ it << i }}
    }
    dependencies {
        compile files(config.libs_dir + filename)
    }
}`

**Comment by lehjr** [comment]
I think the best thing here is ask @MachineMuse how she wants to handle this. It would be simple to just include the 2 missing libs in a PR in ./libs and be done with it. The other option is like I mentioned above and just stash them somewhere. As for the missing dependencies for the dev environment, that could be left for another time. The big thing is to get the build dependency issue fixed and get a new official build out there in order to deal with issues in the current code rather than addressing issues that have already been fixed.

**Comment by flowtender** [comment]
relax I can just upload them to my server gimme a min

**Comment by flowtender** [comment]
k should be building now :)

**Comment by flowtender** [comment]
oops I'm dumb :-1:

**Comment by lehjr** [comment]
Great! Looks like a new build made it through. Hopefully that helps cut down the bug reports for outdated versions of Numina and MPS.

**Comment by Xen1290** [comment]
Fixed, thanks!
