### ISSUE TITLE
Recip not work in NEI

### ISSUE THREAD

**Issue by ghost** [MachineMuse/MachineMusePowersuits#652]
Repport bug : http://hastebin.com/tifumeguri.vbs
Thanks !

**Comment by Xen1290** [comment]
This bug is fixed, you need to wait until #651 will be fixed.

**Comment by ghost** [comment]
Don't work :/
http://hastebin.com/mewepenaye.avrasm
With "ExtraCells-deobf-1.7.10-2.3.1b144.jar"

**Comment by lehjr** [comment]
The title "Recip not work in NEI" really doesn't have much to do with the log segment in the first comment. If you're having recipe issues, then you're probably using an outdated version of Numina.

The second issue would be easier to see the problem with the whole log instead of just a few lines.

**Comment by lehjr** [comment]
Also, the "deobf" in "ExtraCells-deobf-1.7.10-2.3.1b144.jar"  means deobfuscated, and is only used in a dev environment

**Comment by ghost** [comment]
Solved, i have used Numina 131 ^^'
