### ISSUE TITLE
PowerSuits crash on item get.

### ISSUE THREAD

**Issue by zaza7** [MachineMuse/MachineMusePowersuits#656]
After updating MMPS to ModularPowersuits-0.11.0.284 and Numina to Numina-0.4.0.131 I was no longer able to get onto my server. I did a test with just these two mods on forge 1492 and a clean world. 
As soon as I get a Power Armor Helmet from the Creative tab into my inventory I experience a half crash where I get kicked and the console logs an error related to powersuits. 
The server log is here https://paste.lemonmc.com/protgakqg but I was not able to replicate this under single player.

**Comment by Razorskills** [comment]
284 is a bad build. either upgrade to 289, or got back to 283.

But really, that build should be removed from curse @MachineMuse

**Comment by zaza7** [comment]
I'd like to add that I updated to 289 and everything works as it should but my issue stemmed from the Tekkit Legends modpack,  I would also like to apologize for this non-issue as it does appear this was fixed.
