### ISSUE TITLE
[Suggestion]New railgun sound

### ISSUE THREAD

**Issue by Gambigobilla** [MachineMuse/MachineMusePowersuits#657]
Current railgun is sounds too weak for this powerful weapon. Could you please change it or externalize in anyway so i can use a sound of my choice.

**Comment by Xen1290** [comment]
Could you list a good sounds for the railgun ? So machinemuse can choose, if she want to change it.

**Comment by EzerArch** [comment]
I have some suggestions, most public domain:

https://www.freesound.org/people/klangfabrik/sounds/211947/
https://www.freesound.org/people/klangfabrik/sounds/232936/
https://www.freesound.org/people/aust_paul/sounds/30935/
https://www.freesound.org/people/peridactyloptrix/sounds/214990/
https://www.freesound.org/people/Supraliminal/sounds/77087/
https://www.freesound.org/people/kafokafo/sounds/128229/
https://www.freesound.org/people/Supraliminal/sounds/77087/
https://www.freesound.org/people/Ch0cchi/sounds/15350/ (CC-BY)
https://www.freesound.org/people/ejfortin/sounds/49693/
https://www.freesound.org/people/klangfabrik/sounds/211439/

And if someone wants, I can edit/sample them on Audacity.

**Comment by eyeonus** [comment]
It's a railgun, not a laser. Nor a plasma gun. If it's going to be changed, it should be based on the sound a railgun actually makes:

https://www.youtube.com/watch?v=y54aLcC3G74

Or this (the sound made at 0:01 - 0:02):
https://www.youtube.com/watch?v=O2QqOvFMG_A

Railguns are actually very quiet weapons.

**Comment by EzerArch** [comment]
> It's a railgun, not a laser. 

Oh yes. I searched "railgun", but they sounded just like ordinary guns and none of them satisfied me. And I tend not to stick to realism, especially when most of Minecraft sounds barely resemble those from reality and are rather cartoonish.

Something like the railgun from Quake would fit better in my opinion ([Link 1](https://www.youtube.com/watch?v=h07hMlU3cM8), [Link 2](https://www.youtube.com/watch?v=SX1xGOdmIb4)).

I have this one too http://freesound.org/people/roper1911/sounds/155790/ but it feels quite off.

> Railguns are actually very quiet weapons.

B-but...those videos you posted say otherwise. :<

**Comment by Alaberti** [comment]
Realism or Rule of Cool. I pick rule of cool myself. If you want realism you might be playing the wrong game lol. Give it some presence, let it sound visceral!

**Comment by eyeonus** [comment]
Never choose black or white when you can choose a shade of grey, Alaberti. Very few things in life are a binary choice.

**Comment by Alaberti** [comment]
Good thing in video games you can change your mind or make your own choices. Land of infinite possibility as they say.

**Comment by lehjr** [comment]
The current sound is "random.bow" from Minecraft, and I do have to agree that it is a bit odd, maybe even a little goofy, just not as goofy as this: https://www.youtube.com/watch?v=CVdzbC4MI8c

**Comment by flowtender** [comment]
I didn't have a sound for the railgun at the time; all of the sound effects in MPS have either been hand-crafted by fans or are from the vanilla assets. Using a free open source sound effect would probably be fine.

**Comment by lehjr** [comment]
This will probably become a thing in one of the betas for 1.10.2.

**Comment by lehjr** [comment]
Implemented in 1.12.2 for direct hit while a miss still uses the same sound.

**Comment by eyeonus** [comment]
> > Railguns are actually very quiet weapons.
> 
> B-but...those videos you posted say otherwise. :<

In both of the videos, the extremely loud noise you hear is the sound of the projectile hitting its target. The actually noise the railgun makes is the tiny "poof" right before the giant noise.

**Comment by lehjr** [comment]
depends on the size and velocity. https://www.youtube.com/watch?v=8UKk84wjBw0

**Comment by eyeonus** [comment]
Yes, more powerful railguns will result in more noise when firing than smaller ones, my point is that the actual railgun _itself_ doesn't make any noise at all (except for possibly the buzzing of extremely high voltage wires), it's the acceleration of the projectile through the air that makes any noise you hear, which means that railguns would be totally quiet in a vacuum, and that the loudest they can be is the loudness of a sonic boom.

(Not trying to start an argument, it's just that I was recently reminded of this issue that I'd completely forgotten about, and upon reviewing it, noticed there was a point I failed to raise many years ago.)

**Comment by lehjr** [comment]
You're right about the projectile and the sound, but keep in mind that for the sake of entertainment the laws of physics in Minecraft are written in crayon, similar to scifi movies/shows with laser's making that pew pew sound in space.

**Comment by eyeonus** [comment]
Agreed. Entertainment should always beat out reality when it comes to a game.
