### ISSUE TITLE
Chunk errors wherever I go.

### ISSUE THREAD

**Issue by the-monch** [MachineMuse/MachineMusePowersuits#658]
Whenever I adventure a few chunks I see that i've been walled off by chunk errors. After a few minutes, the lighting underground refuses to work. It happened in Direwolf20 pack so I moved to Infinity Evolved. It didn't happen in Evolved so I added MPS and Numina and the chunk errors start happening again. I can live with the chunk errors for a while, but then it just tears my whole house in half.

I have a full Modular Powersuit hanging on a Bibliocraft armor stand in my home.I was wondering if that could cause the problem or not. All I know is, chunk errors everywhere.

**Comment by Xen1290** [comment]
MPS and Numina versions?

**Comment by flowtender** [comment]
what is a 'chunk error'

**Comment by EzerArch** [comment]
Screenshots might help.

**Comment by lehjr** [comment]
For completeness, a chunk error in this context is usually where the chunk fails to load, leaving holes in the world requiring the player to log out of the world and back in. Usually, it isn't a single chunk, but a strip of them. Most of the time, using F3-A does not work. I've had a few instances where I was hosting a lan game and the chunk failed to load on my side, but not on other player's side. Here's a not so good example. The hole on the left of the pic is the chunks failing to load. 
![2016-01-25_22 04 54](https://cloud.githubusercontent.com/assets/1084367/12614869/69edc958-c4d0-11e5-8db7-7041a82f3573.png)

**Comment by flowtender** [comment]
ok. That's weird since we don't do much to mess with chunks or blocks at all.

**Comment by flowtender** [comment]
I'm gonna close this since #700 has a better OP and is probably the same issue.
