### ISSUE TITLE
ModularPowersuits-0.11.0.284 & isound issue on server?

### ISSUE THREAD

**Issue by djoveryde** [MachineMuse/MachineMusePowersuits#660]
I'm currently running a Tekkit Legends Server. None of the players can hold any of the power items without crashing. I've taken a look and the server is throwing the following error.

http://pastebin.com/1GCuYS9v

**Comment by Xen1290** [comment]
@djoveryde Please, Update to 290, Please tell to Modpack creator to update as soon as possible and tell to reset the configs. 284 is very buggy!

**Comment by djoveryde** [comment]
Is there any way that I can update the server to 290 and still allow players running the official pack to load in? As i cant change the pack itself only the server

**Comment by Razorskills** [comment]
284 is a bad build. Not going to work. Again it should be removed from curse so people can't download it anymore. Also should check what version of numina is in the pack, the latest recommended build(119) is bugged. The latest numina version should be bumped to recommended aswell.
@MachineMuse 
That at least might help with all the posts about 284 plus the recipes problem for numina 119.

**Comment by LemADEC** [comment]
@CannibalVox please update Tekkit Legends to fix that derp

**Comment by flowtender** [comment]
I tried to delete the file from CurseForge but not sure if it worked. It is not exactly clear about the process.

Either way, Tekkit is not my problem. I'll bug CanVox anyway.
