### ISSUE TITLE
Dimension Change resets Sprint/walk boost

### ISSUE THREAD

**Issue by Keridos** [MachineMuse/MachineMusePowersuits#663]
On Dimension change via RFTools matter transmitter the speed boost and walk boosts are not synced, they need to be turned on again. Using ModularPowersuits-0.11.0.290

**Comment by flowtender** [comment]
This is technically a vanilla bug since it necessarily also occurs with speed-enchanted items. However we can probably do better by catching some event related to teleportation or dimension changes and forcing a re-calculation of the new player object's properties.
