### ISSUE TITLE
Recipes not correctly showing up in the NEI, or just don't work at all

### ISSUE THREAD

**Issue by Emiel1000111** [MachineMuse/MachineMusePowersuits#665]
The recipes on certain items wont show up completely or just dont work at all.
Some of these are the HV Capacitor and the Force Field Emitter.
Using ModularPowersuits-0.11.0.291

**Comment by Xen1290** [comment]
Numina version?

**Comment by Emiel1000111** [comment]
Numina-0.4.0.119

**Comment by lehjr** [comment]
Outdated Numina version
http://minecraft.curseforge.com/projects/numina/files

**Comment by Emiel1000111** [comment]
Thank You

**Comment by Xen1290** [comment]
@MachineMuse could you delete all numina versions and leave only the latest?

**Comment by lehjr** [comment]
I think the problem is that only releases show up on curse while curse
forge shows all versions regardless of type label. Of course this was
supposed to be solved already. I'll have to see why this can still run with
older versions.
