### ISSUE TITLE
Water tank for cooling does not fill when small unless completely submerged.

### ISSUE THREAD

**Issue by eyeonus** [MachineMuse/MachineMusePowersuits#669]
MPSA has two cooling modules, the lower tier of which uses a refillable water tank, which is refilled by standing in water.

The bug is easily reproducible, but requires a mod that alters player size, such as Morph. Make the player 1-block or less tall, then go stand in water no more than 1 deep. The tank will not fill.

**Comment by lehjr** [comment]
Unfortunately, that has to do with how Minecraft checks if a player is in water.

**Comment by lehjr** [comment]
https://github.com/MachineMuse/MachineMusePowersuits/blob/experimental/src/main/scala/net/machinemuse/powersuits/powermodule/armor/WaterTankModule.java#L79

**Comment by flowtender** [comment]
we can check if the block at the player's feet is water. that could make it have the desired behaviour.

**Comment by eyeonus** [comment]
That should work. Let me know when it does that and I'll test it out. :)

**Comment by flowtender** [comment]
seems to be fixed by #670. open a new ticket if there are issues with this fix please :heart:
