### ISSUE TITLE
Power Fist Lightning Summoner Issue

### ISSUE THREAD

**Issue by thegoogleguy** [MachineMuse/MachineMusePowersuits#671]
Up to the latest 294 builds, you can install any tool (such as the Plasma Cannon), and then install the Lightning Summoner. Then, exit the tinker table and use sneak + scroll to select the Lightning Summoner. Now open up the Tinker Table, and remove the Lightning Summoner module from the Power Fist, and it'll still be installed even though you got the modules back. You can also fire the Lightning Summoner at this point without using any energy from your armor, nor creating any heat. I'm not sure if this works in Survival Mode, but I have successfully done it in Creative.

**Comment by flowtender** [comment]
The parts aren't consumed in the first place if you're in creative mode.

**Comment by flowtender** [comment]
The fact that it can remain active after removing it is worth looking into though. I don't remember putting in any safeguards against that.

**Comment by thegoogleguy** [comment]
Yes I can try it out in survival and report back. A friend of mine actually discovered this same glitch in MPS for 1.6.4, and as it turns out it still works in 1.7.10.

**Comment by thegoogleguy** [comment]
This glitch does indeed work in survival mode too, as you can see in this screenshot, the Lightning module is still selected on the power fist even though it's not installed in the Tinker Table: http://i.imgur.com/6pEHFv2.png

**Comment by flowtender** [comment]
it probably works with any other right-click module too. The right-click module selector looks at the list of what's installed when you go to change it, but it doesn't force the module to be one that's installed.

We can solve this a couple of ways - either cycle the selected module when removing a module, or check every tick to make sure the module that's selected is one that's installed. The latter is more robust but potentially more cpu cycles. The former will work with no performance impact at all, but could still be circumvented some way or another.

**Comment by thegoogleguy** [comment]
To be honest I've never done mod development, but I understand what you're saying. I know with said glitch you can still scroll through the modules and the lightning summoner will stick around, so I'm not sure if the first solution would work, otherwise correct me if I'm wrong.

**Comment by Slitty** [comment]
Wouldnt it be possible for it to fire a module check when the right click event w/ power fist occurs? Seems a much less cpu intensive solution

**Comment by flowtender** [comment]
hm, interesting observations. thanks.

**Comment by lehjr** [comment]
Closing for now. If the issue persists in 1.10.2 we can revisit.
