### ISSUE TITLE
MPS Startup Crash

### ISSUE THREAD

**Issue by adamcirillo** [MachineMuse/MachineMusePowersuits#672]
I tried running MPS for the 1st time in my mudpack and I get the following crash.

http://paste.ee/p/e0yzQ

it looks like it conflicts with nhave's omniwrech 2 which I have installed everything works fine if I remove MPS or Omniwrech

**Comment by Xen1290** [comment]
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/nhave/nhwrench/common/items/ItemWrench

It seems is omniwrench error. Try Update omniwrench

**Comment by adamcirillo** [comment]
I'm running the lastest version of omniwrench already I will report this issues to the dev then if it's from his side

**Comment by flowtender** [comment]
might be an api mismatch, I'll leave this open in case we can get more information

**Comment by lehjr** [comment]
I am unable to reproduce the crash in a dev environment. Seems there are a couple issues with the mod crashing: http://minecraft.curseforge.com/projects/nhaves-omniwrench-2/issues

**Comment by nhave** [comment]
Ive started with GitHub heres the link to my source if you can help figure it out.
https://github.com/nhave/nhwrench

And i cant even reproduce the crash in my dev environment, could there be some code in your mod that could provent my mod from loading if powersuits is loaded first?

Update:
Forcing my mod to load before the powersuits mod seems to do it.

**Comment by flowtender** [comment]
Are you doing that on your end, nhave, or do you need us to add an "after:" clause for nhwrench in MPS?

**Comment by nhave** [comment]
Its fixed om my end, Ive just added "before powersuits" in the @mod function.

**Comment by flowtender** [comment]
cool :) Thanks!
