### ISSUE TITLE
Axe module is too slow with Treecapitator Mod

### ISSUE THREAD

**Issue by lehjr** [MachineMuse/MachineMusePowersuits#674]
Issue is best described here as " it takes forever to chop through a tree. It's like chopping a tree down with your hand": http://forums.technicpack.net/topic/60300-mps-axe-and-treecapitator/

I'm not yet sure why this doesn't work properly, but it's due for a fix.

**Comment by lehjr** [comment]
The issue seems to be in breakspeed handling. 
In the axe moudle with max overclock, the breakspeed is 8.
In the Treecapitator mod, the breakspeed is reported as 1 instead of 8. From there, it is recalculated by factoring in the tree height. 
Example:

(MPS..............) Axe module break speed 8.0
(Treecapitator) Old Break Speed: 1.0
(Treecapitator) New Break Speed: 0.071428575
(Treecapitator) Tree Height    : 7
(Treecapitator) Tree Height Mod: 2.0

Edit, digging deeper, it looks like it is using "event.originalSpeed" which in the MPS module shows as 1.0

**Comment by flowtender** [comment]
Then they're using the event wrong lol. oh well. we can work around it or we can submit a bug to them.

**Comment by lehjr** [comment]
most relevant code here: https://github.com/bspkrs/Treecapitator/blob/1.7.10/src/main/java/bspkrs/treecapitator/forge/ForgeEventHandler.java#L48

**Comment by Razorskills** [comment]
But doesn't treecapitor look at how fast your pick axe is, then how many blocks of wood there is to cut down and then has an amount it divides the speed by? If the speed of the diamond axe isn't the same as the diamond axe module. Then that makes sense to be an issue.

**Comment by lehjr** [comment]
Edit:
No, it just checks to see whether or not the player is using an axe. 

The way I understand it is "BreakSpeed" would normally be roughly based on tool type and material vs block material. However, since the axe and other modules have adjustable speed and since this only mimics an axe and other tool, that can't be used so the "BreakSpeed" has to be set manually. However, "BreakSpeed" contails both originalSpeed which is the original speed at which the block was broken, and newSpeed which is the modified speed. Treecapitator looks at the original speed and sets it's own new speed, meaning that any variable speed axe is likely to suffer the same problem of being half the speed of  a wooden axe. However, I'm not aware of any other variable speed axes, so the number of affected tools may be small. 

Also, there is no diamond axe module, just a diamond drill upgrade module for the pickaxe, which does not change the speed at which the pickaxe module works, but instead allows the player to harvest blocks that would normally require a diamond pickaxe. Speed itself is individually adjustable by an overclock slider for the pickaxe, axe, and shovel modules.

**Comment by lehjr** [comment]
@MachineMuse what are you thinking in terms of a work around?

**Comment by flowtender** [comment]
Set the 'original speed' in our code. might require an accesstransformer since iirc that field was final

**Comment by lehjr** [comment]
It will since original speed is 
edit: final, not private

**Comment by lehjr** [comment]
Tested it with reflection and seems to work. Can't seem to find the obfuscated name though, so I may have to build it, run it, and get it from the crash.

Edit: tested it in a normal game. Works without a crash. Taking down a gigantic spruce now takes seconds instead of minutes! Now to try an access transformer instead.

**Comment by lehjr** [comment]
Um, yeah... I hate to ask, but is an access transformer possible to manipulate Forge code?
I can do it just fine with reflection, but access transformer I can't seem to get to work. This is my reflection code
```try {
            Field originalSpeed = BreakSpeed.class.getDeclaredField("originalSpeed");
            originalSpeed.setAccessible(true);

```
        Field modifiers = Field.class.getDeclaredField("modifiers");
        modifiers.setAccessible(true);
        modifiers.setInt(originalSpeed, originalSpeed.getModifiers() & ~Modifier.FINAL); // Remove final

        originalSpeed.set(event, new Float(ModuleManager.computeModularProperty(event.entityPlayer.getCurrentEquippedItem(), AXE_HARVEST_SPEED)));

    } catch (NoSuchFieldException e) {
        e.printStackTrace();
    } catch (IllegalAccessException e) {
        e.printStackTrace();
    }
```

```
```

**Comment by flowtender** [comment]
You may be right. Reflection it is then. Memoize the field so that it doesn't have to do the expensive lookup every tick; I think you can just put static final Field modifiers = Field.class.getDeclaredField("modifiers"); in the class by itself.

**Comment by lehjr** [comment]
Before I do that, I'll try the access transformer approach again in the hopes that I may have missed something. I'd much rather go that way since it is called so frequently.

**Comment by lehjr** [comment]
What would the correct syntax be for orignalSpeed in an Access Transformer? 
I thought it was 
`public-f net.minecraftforge.event.entity.player.PlayerEvent.BreakSpeed.originalSpeed`
also tried 
`public-f net.minecraftforge.event.entity.player.PlayerEvent.BreakSpeed originalSpeed`
but neither one works.

**Comment by flowtender** [comment]
Some people in #minecraftforge have confirmed that forge adds itself to the accesstransformer exclusion list. So it's not possible to do it that way. But I added a pull request to Treecapitator for it.

**Comment by lehjr** [comment]
Great, thanks!

**Comment by flowtender** [comment]
It looks like Treecapitator isn't being updated.

I had another idea which is to add after:Treecapitator to our loadrequirements so that our event handler comes after theirs.
