### ISSUE TITLE
Apiarist Armor Addons not showing up in Tinker Table?

### ISSUE THREAD

**Issue by SniperHauss89** [MachineMuse/MachineMusePowersuits#680]
Hello, I downloaded the latest build of MPS and went through the armor pieces to see what was new and/or implemented from the infamous MPS Addons mod, I didn't see the Apiarist armor but there was the scoop add on for the power fist. I then took a peek at the config and saw an option that was set to true for the Apiarist Armor, so my question is: is this not fully implemented or just some bug somewhere?

MPS 0.11.0.296
Numina 0.4.0.431
Forge 1614
(Note: I have many mods in the pack I added it too as I am contemplating adding this too it.)

**Comment by Xen1290** [comment]
Forestry version?

**Comment by SniperHauss89** [comment]
oh woops how did I forget that one anyway it's 4.2.4

**Comment by lehjr** [comment]
I think it has to do with MPS being built with an old version of the Forestry API (3.6.320). I just grabbed the latest dev version but I had to make changes before it would build. I'll look into it more tomorrow since it won't run with my current forge version set up in my dev environment.

**Comment by SniperHauss89** [comment]
oh ok yea that makes sense, at least you have a good idea of what's wrong.

**Comment by lehjr** [comment]
I have a fix, but need the Forestry version that MPS uses will need to be updated to 4.2.2 first (higher requires changing Forge versions again).

**Comment by lehjr** [comment]
@MachineMuse can you update the forestry version?

**Comment by Xen1290** [comment]
Update Forestry may break Forestry 3.6.x support that is the only that works with binnie mods.

**Comment by lehjr** [comment]
Lovely

**Comment by flowtender** [comment]
lmao

1.7.10 is dead I guess :( we have to update to 1.8 which will be a huge pain with all our rendering stuff

**Comment by lehjr** [comment]
I did see a 1.8.8 mod that has obj models... 
Edit:
https://github.com/hsyyid/HaloMod

**Comment by Xen1290** [comment]
Wait for 1.9, I think that 1.8.8 is useless, for me. Because as far I know, people like cofh mods, and they only update to 1.9.
And, 1.7.10 is almost dead, but a lot of people uses it, because CoFH, Tinker, galacticraft, mekanism etc...
A good thing of 1.8.8 and probably 1.9 is that Lex will merging a new  multipart api to Forge(https://github.com/amadornes/MCMultiPart), but for MPS I can see no uses.

**Comment by lehjr** [comment]
OK, all the 1.8 and beyond stuff aside, where are we with fixing this issue? Apparently fixing compatibility for newer Forestry builds breaks other mods. Leaving it breaks MPS integration with the Apiarist Armor with newer Forestry builds. 

This is what the IDE adds for compatibility with newer Forestry builds:
`override def protectEntity(entityLivingBase: EntityLivingBase, itemStack: ItemStack, s: String, b: Boolean): Boolean = ???`

This is the Forestry commit where this changed: https://github.com/ForestryMC/ForestryMC/commit/efd9cd06f6f3711e8f1851b19313f6e0443d4953

**Comment by flowtender** [comment]
the needs of the many outweigh the needs of the few

**Comment by flowtender** [comment]
sorry :(
