### ISSUE TITLE
Power fist mining not working correctly

### ISSUE THREAD

**Issue by KassWhyte** [MachineMuse/MachineMusePowersuits#682]
I have installed the pick axe, axe, and shovel function on the power fist but when ever I mine dirt, sand, dirt or gravel with it it never drops the block and then when I go to step in the place where I mined it I glitch and bounce up and down. When mining with the pick axe function it takes a few seconds for the world to recognize its gone then the block will turn drop. I don't know if its on my side or the mods and every other pick axe works just not the power fist. I am using multi mc and forge version 10.13.4.1558-1.7.10 on minecraft 1.7.10. I am also using optifine so could that be causing trouble? This is in my own custom private modpack just for me with about 95 other mods. This also with Numina version 0.4.0.131 and MPS version 0.11.0.296.

**Comment by lehjr** [comment]
Sounds like a massive amount of lag. I would check your logs for anything unusual, especially anything repetitive.

**Comment by KassWhyte** [comment]
The weird thing is that it is only the power fist having troubles. No other picks are doing this. And I cannot find anything in the logs repetitive.

**Comment by lehjr** [comment]
Do you use Waila Harvestability? 

Edit: Honestly, it would probably be easier to list the mods you are using. In my own experience, the only time I noticed any lag is with smart moving and while breaking blocks when swimming. However, I never spent a lot of time to see where the lag was coming from.

**Comment by KassWhyte** [comment]
Oh I found the problem it was the mod More Commands. I don't really need it for my own little private pack so I am fine without it.

**Comment by CarterBrehm** [comment]
I'm having this same issue and don't have More Commands, only difference is the block *never* drops and it doesn't glitch me out when I walk inside the block. I can provide a modlist if needed.
