### ISSUE TITLE
Powerfist crash on startup

### ISSUE THREAD

**Issue by zane49er2** [MachineMuse/MachineMusePowersuits#683]
I am having an issue almost identical to https://github.com/MachineMuse/MachineMusePowersuits/issues/588.
I will post a crash log anyway.
http://paste.feed-the-beast.com/view/3b1fe23d
I am using the newest ModularPowersuits, Numina, and pretty close to newest Forge.

**Comment by lehjr** [comment]
Try a version newer version of EnderIO, as that is over a year old and may have issues with newer forge builds anyway.

**Comment by zane49er2** [comment]
It did change the crash to an EnderIO one, involving incompatible RF and RailCraft I will update them.

**Comment by lehjr** [comment]
That's because Railcraft includes the RF API and your Railcraft version is also over a year old. 
Edit: You really should just go through them all and update them as needed. Mixing outdated versions of mods with new versions of Forge usually doesn't go well.

**Comment by zane49er2** [comment]
After a long chain reaction of updates, everything is fine.
