### ISSUE TITLE
Broken recipes

### ISSUE THREAD

**Issue by popcorn9499** [MachineMuse/MachineMusePowersuits#684]
I dont know if this is just me or what. I have found recipes like the tinker table and stuff to not work. Also lots of recipes appear really broken due to missing items in the recipes when viewing with nei.

NEI version 1.0.5.118
Forge Version 10.13.4.1614
Power Suits Version 0.11.0.296
Numina Version 0.4.0.119
Ender IO Version 2.3.0.423_beta
IC2 Version 2.2.810-experimental
Thermal Expansion Version 4.0.3B1-218
Thermal Foundation Version 1.2.0-102
Cofh Core Version 3.0.3-303

I would really like to get this working and help you fix so please if you need more information tell me

**Comment by lehjr** [comment]
Please use the search feature before opening a new issue. This was already fixed months ago, your Numina version is outdated. Please see the link on the main page of this repo.

**Comment by popcorn9499** [comment]
ok sorry i searched but didnt find this. The reason i didnt find the correct version of numina because i downloaded the regular version not the beta. Thank you and im sorry i caused this inconvenience
