### ISSUE TITLE
All recipes are missing/empty

### ISSUE THREAD

**Issue by Shahelion** [MachineMuse/MachineMusePowersuits#685]
The Ender IO recipe file that came with the mod does not seem to be working. NEI shows no recipes for ANYTHING in this mod.

0.4.0.131 Numina
0.11.0.296 MPS

**Comment by Shahelion** [comment]
Tried the Vanilla recipes, those don't work either.

**Comment by Shahelion** [comment]
Also, regarding the Ender IO recipes, they need to be altered/updated. Ender IO has nothing that would qualify as "circuitBasic" or "circuitAdvanced", and the Myofiber Gel and Carbon Myofiber are rather expensive, being made of several ingots of Dark Iron for a single one of each. 

Plus, itemMachinePart gives the Machine Chassis, while itemMachineChassi is invalid.

**Comment by Xen1290** [comment]
I am aware of this, but I haven't the pc so I can't fix at the moment...

**Comment by Ryius** [comment]
have the same Issue

**Comment by lehjr** [comment]
If all of the recipes are not working then you're doing something wrong. I could understand a few broken recipes, but all of them? No.

**Comment by Shahelion** [comment]
Chassis\* :P

itemMachinePart also works for the Machine Chassis block.

**Comment by lehjr** [comment]
Thanks. LOL. Maybe I'll pick up some of those wooden blocks with letters on them and practice later.
