### ISSUE TITLE
Power Armor cannot be charged in various chargers

### ISSUE THREAD

**Issue by Shahelion** [MachineMuse/MachineMusePowersuits#688]
The armor simply refuses to be put into the charging slots. Machines that don't work: Ender IO Capacitor Bank, AE2 Charger.

**Comment by Xen1290** [comment]
Numina and MPS version?

**Comment by lehjr** [comment]
Simply saying it doesn't work really isn't much to go on. Without version numbers we can't do much for you. The most likely cause is an API mismatch for RF power (outdated version of EnderIO or MPS). As far as AE2 goes, there is currently no AE2 power implementation in MPS.

**Comment by Shahelion** [comment]
0.4.0.131 Numina
0.11.0.296 MPS
2.3.0.421 Ender IO

I did say how it doesn't work, the items cannot be placed into the charging slots.

Also, the power armor items no longer draw power from non-MPS items in the inventory. Such as any Ender IO items that have been Empowered to hold RF, or Capacitor Banks in item form. It simply ignores them. Currently the only way to recharge the armor is to add a generator module, ~~or make a Wireless Charger (if that works, even)~~Wireless Charger also does not work.

**Comment by EzerArch** [comment]
Mekanism (MJ) used to charge MPS armor via Chargepads. The compatibility was lost in one of the ports (1.6.4 to 1.72?).

![2016-01-17_04 13 34](https://cloud.githubusercontent.com/assets/6743303/12376249/f8420abe-bcd0-11e5-85bf-c44b8e3dd3f1.png)

Using:
ModularPowersuits-0.11.0.296.jar
Numina-0.4.0.131.jar

**Comment by Shahelion** [comment]
Considering one of the options for recipes is Ender IO, shouldn't there be a way to charge it using only Ender IO?

**Comment by lehjr** [comment]
I use the same build of EnderIO myself without issue to charge my armor. My guess is that you have another mod providing an outdated RF-API (ruling out not having any power storage capacitors installed). Unfortunately, when mods include API's from other mods, they can override even the original mod's API causing havoc.

If you provide a list of installed mods I might be able to point out the culprit, but basically, any mod that hasn't updated in a long time that uses RF is suspect. The dead giveaway is when you see "cofh" inside the jar file.

**Comment by HenryLoenwind** [comment]
If you crash the game, e.g. be holding F3+C for 6 seconds, Ender IO will give diagnostics on the RF API in the crash log.

**Comment by lehjr** [comment]
Wow, that is an incredibly valuable time saving tip!! Thanks for sharing!!

**Comment by Shahelion** [comment]
https://gist.github.com/Zsashas/7d558d89b072ee2ac691

That's a F3+C crash, in case it says something there. I don't see anything, though. Also a list of mods so yeah...

**Comment by HenryLoenwind** [comment]
Oops, 421 was the last version before the RF diagnostics was added (nearly 2 months ago, to my defense).

Not much to say from this other than: fml doesn't report a very old (v1.0.0/.1) version of the API as loaded.

Ok, more debugging steps: Try it with the same Minecraft installation in a singleplayer world (creative is ok). If you have the same problem there, please drop in Ender IO build 422 for a moment, check that the problem is still there and make a fresh crash log. If we cannot see something from that, I can make a debug build that'd write into the log why an item is rejected. (If it is server-only, it gets more complicated...)

**Comment by lehjr** [comment]
So far looking at that list, I see a really old build of Railcraft which does include the RF API
Another one on that list would be Buildcraft (outdated and uses RF API).

**Comment by Shahelion** [comment]
This WAS in a singleplayer world, and it was even in creative mode.

~~Where can I get the 422 build? I didn't see it in the downloads.~~ Nevermind I see it. It'll be a few hours until I can report back (after work). Will try updating Railcraft as well (didn't realize there was an update).

There was a reason I couldn't update Buildcraft but hell if I can remember what that was...

**Comment by lehjr** [comment]
http://minecraft.curseforge.com/projects/ender-io/files

**Comment by Shahelion** [comment]
Ok I managed to get it before I have to leave. Crash report with updated Railcraft and Ender IO: https://gist.github.com/Zsashas/d0390e1c4225846e373e

Says there is an outdated RF thingy, but says it's unknown so...probably Buildcraft but that will have to wait until later (8h shift).

**Comment by lehjr** [comment]
Edit: yeah, that might be it. I'll see what you report back

**Comment by HenryLoenwind** [comment]
1.0.2 isn't that bad, it should still work. But yes, try to remove all RF APIs but one. You can open the jar files of the mods with any ZIP program and just delete the "cofh" folder (or "cofh/api/energy" for just RF). If that doesn't help, I can make the debug build tomorrow evening (in ~22 hours).

**Comment by Shahelion** [comment]
If I have no CoFH mods should I just delete the whole CoFH folder from each?

**Comment by lehjr** [comment]
If a mod has that then it probably relies on it. However, you can install CoFH core afterwards and they should work fine (avoid the alpha builds though, they probably aren't compatible).

**Comment by Shahelion** [comment]
But if I don't have CoFHCore already, then how can they be relying on it?

**Comment by HenryLoenwind** [comment]
They can by including the API. They are relying on the availability of the API classes, not the mod behind the API. Also, some of the API (e.g. RF API) doesn't need CoFHCore but enables mods that use it to talk to each other.

**Comment by Shahelion** [comment]
Alright so with updated Railcraft, Buildcraft, and Ender IO, I STILL can't charge anything lol. Only being able to use the generator modules to charge does not appear to be enough (except possibly combining Fire Resistance and a Heat Generator, but even that's rather slow).

Got a new forced crash, Ender IO is now reporting no problems with the API, so that's solved at least.

**Comment by lehjr** [comment]
Try a new map with just EnderIO + MPS + NUmina

**Comment by Shahelion** [comment]
Can confirm, still cannot charge using only Ender IO.

Only using the four mods:
  EnderIO-1.7.10-2.3.0.422_beta
  EnderCore-1.7.10-0.2.0.31_beta
  ModularPowersuits-0.11.0.296
  Numina-0.4.0.131

**Comment by lehjr** [comment]
And you have capacitors installed in the armor?

**Comment by Shahelion** [comment]
All tested with MV Capacitors, cranked up to maximum to make sure they had room for more power.

**Comment by lehjr** [comment]
Sorry about the hassle. Turns out the code is looking specifically for CoFH core, which you wouldn't need since the API is included in EnderIO. -_-

I'll see if I can get something out later today for this

**Comment by tterrag1098** [comment]
https://github.com/MachineMuse/MachineMusePowersuits/blob/experimental/src/main/scala/net/machinemuse/api/electricity/MuseElectricItem.scala#L18

Should be CoFHAPI|energy

**Comment by lehjr** [comment]
@tterrag1098 thanks, that did it!!

**Comment by Shahelion** [comment]
Should I try adding CoFHCore in the meantime, or would it mess up my world if I added it then removed it later?

**Comment by flowtender** [comment]
I think we fixed it! Sorry about that!
