### ISSUE TITLE
[1.10.2] Request: Vanilla Keybind option

### ISSUE THREAD

**Issue by Shahelion** [MachineMuse/MachineMusePowersuits#690]
Config option, defaulting to false, to allow for keybinds to be set in the vanilla keybinds menu. This would allow for things like using MineMenu to toggle modules.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2141720-minemenu-v1-2-0-radial-menu-nuff-said

**Comment by flowtender** [comment]
Vanilla keybinds are a mess that have been through some major changes since I last touched them, hence why I made my own system for them. This isn't a small feature request sadly. It might be possible though.

**Comment by MachineMuse** [comment]
I think we are not adding new features to 1.7 at this point though, so unless you want this in 1.8, should probably close it?

**Comment by lehjr** [comment]
this is something I still want to look at after the major issues are fixed. It should be possible.

**Comment by Shahelion** [comment]
Update?

**Comment by lehjr** [comment]
> Update?

I'll look into it after I finish the GUI redesign.

**Comment by lehjr** [comment]
This will be in the next release
