### ISSUE TITLE
Crafting not showing all the elements

### ISSUE THREAD

**Issue by NoLiver92** [MachineMuse/MachineMusePowersuits#691]
I am using thermalexpansion recipe pack and when go to craft it (using NEI for the recipie), it doesnt show the thermal expansion parts which make up the component. for example the tinker table says 1 emeraly 2 electrum ingots. I also needed 2 other components which it said in game i didnt need. this is the same for all parts. Whats going on with it

**Comment by lehjr** [comment]
Numina version?

**Comment by NoLiver92** [comment]
numia: 0.4.0.119
Powersuits: 0.11.0.296

**Comment by lehjr** [comment]
your Numina version is outdated

**Comment by NoLiver92** [comment]
ooops sorry thought I had the most up to date one. My apologies, the problem has been sorted
