### ISSUE TITLE
Power Fist Visual Bug

### ISSUE THREAD

**Issue by Shahelion** [MachineMuse/MachineMusePowersuits#693]
Power Fist module icons have a colored box behind them in the selection wheel. Every active module appears to be affected. 
![2016-01-18_03 23 08](https://cloud.githubusercontent.com/assets/6917535/12390272/495f23d8-bd93-11e5-9759-370592e8720b.png)

**Comment by flowtender** [comment]
hm, probably some mod is leaving openGL in a state with no transparency. Should be relatively trivial to wrap those. Kind of annoying to have to set every damn OpenGL flag every time we get control though.

**Comment by Shahelion** [comment]
The Power Fist item itself also has a colored box behind it, although I didn't notice this at the time.

**Comment by lehjr** [comment]
The power fist model model will be replaced with a wavefront model in 1.10.2, probably sometime before the first beta. 1.7.10 stuff probably won't be getting fixed.
