### ISSUE TITLE
Armor parts and its names in the Tinker Table's Visual Editor

### ISSUE THREAD

**Issue by EzerArch** [MachineMuse/MachineMusePowersuits#697]
While I was messing around with the Tinker Table's Visual Editor, I noticed some parts are misnamed and/or linked to the wrong name/group. Below are the parts with issues, including suggestions of new names that reflect their purpose.

**Helmet**
- mps_helm
  - Right Tube Entry -> Water Electrolyzer or Life Support module (?) - turns on/of the cylinder behind the helmet.
  - Left Tube Entry -> Tube Entries or Tube Connectors - turns on/of both left and right tube entries/connectors.
  - Helmet  -> Helmet Shell - I'm just being technically picky. ;)

**Chestplate**
- jetpack
  - Lights -> Not sure of a name as they don't look like lights, but rather "exhaust pipes" - turns on/of both "exhaust pipes" connected to the jet mufflers.
  - Main -> (unused, visibly does nothing) - probably it was meant to enable the main part (engine?).
  - Secondary -> Wings - turn on/of both wings, the main part and both jet mufflers together. I suppose the main part should be moved to "Main".

**Others**
Nothing out of ordinary.

**Comment by flowtender** [comment]
These are the names assigned in the .obj file by the artist; all of it is in the data files located in the resources section of the repository, so it should be possible for a non-coder to edit them if they want to give it a try!

**Comment by flowtender** [comment]
see this folder https://github.com/MachineMuse/MachineMusePowersuits/tree/experimental/src/main/resources/assets/powersuits/models for the data files.

**Comment by flowtender** [comment]
actually it's the XML files that contain those names - sorry, it's been a long time since I've messed with those!

**Comment by EzerArch** [comment]
Thanks for the info! Since I maintain a resource pack I could try something and make it available for whomever it may interest... when I got around to it. :)

**Comment by flowtender** [comment]
- polygroup=  refers to the tag given to the polygroup in the obj file (don't change this unless you're changing the models!)
- name= refers to the name that should appear in-game
