### ISSUE TITLE
Found The problem for Missing Recipts at the newest Version

### ISSUE THREAD

**Issue by Ryius** [MachineMuse/MachineMusePowersuits#698]
Okey i think it is zCraftingManager 0.7.5 mc1.7.10 who is causing this problem i write a comment to him or maybe you can fix that problem

**Comment by Xen1290** [comment]
Please explain better, i can't understand what you mean.

**Comment by Ryius** [comment]
i had posted that i dont can crafting anythink from that mod: modular Powersuit .And i think i have found the mod that causes that problem

**Comment by Ryius** [comment]
This mod causes that InGameConfigManager Alpha v0.1.11 mc1.7.10

**Comment by Ryius** [comment]
?

**Comment by Razorskills** [comment]
More info from you is required.
We need to know your powersuits, and numina version. 
And some way to know what other mods you have, or a log file at least.

**Comment by Ryius** [comment]
okey i have the last Numina and Modular powersuit Version i have to many mods "230" and when i add  
InGameConfigManager than i dont cann anythink from Modular powersuit and wait i send the log in a sek

**Comment by Ryius** [comment]
i just start up mc

**Comment by Ryius** [comment]
but i finde out that only that mod causes that

**Comment by Razorskills** [comment]
Still waiting on the actual mod version numbers. Saying you have the latest means nothing. And still waiting on the log file. From what I understand, you have some sort of crafting recipe issue, it somehow has something to do with you installing a mod called InGameConfigManager.

Go here: http://minecraft.curseforge.com/projects/numina/files

if you are not using Numina-0.4.0.131.jar then that is most likely the problem.

Check here: http://minecraft.curseforge.com/projects/modular-powersuits/files

to make sure you aren't using an old version of Powersuits.

Then before you launch, find config/machinemuse/recipes and delete that folder. Unless you specifically went there and made your own recipes. If you haven't then just delete the folder and it will make a new one with the right recipes.

After all of that, if something is still not working. Then you will have to explain in more detail what you are trying to do. If you don't mind saying, I was wondering if you speak another language.

**Comment by Ryius** [comment]
i speak German

**Comment by Razorskills** [comment]
Hmm your are right. I just tested this myself to better understand what you meant.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2518796-ingameconfigmanager-v0-1-11-modify-your-config

there is the link to InGameConfigManager if anyone else wants to have a look. I tested it using:
- CodeChickenCore-1.7.10-1.0.7.47-universal
- CreativeCore v1.3.21 mc1.7.10
- InGameConfigManager Alpha v0.1.11 mc1.7.10
- ModularPowersuits-0.11.0.296
- NotEnoughItems-1.7.10-1.0.5.118-universal
- Numina-0.4.0.131

and it does break the recipes, nei shows nothing for all items, and using a crafting table and testing a know recipe doesn't work. If you use InGameConfigManager to make a recipe for any of the items, it still does not work. I am not sure if there is anything that can be done on powersuits side. In my opinion, InGameConfigManager would need to add support for numina/powersuits for you to use the two together. (unless of course one of the developers here can comment about it)

Here is my fml-client log file:
https://www.dropbox.com/s/pbvdpgais5jq8s1/fml-client-latest.log.txt?dl=0&preview=fml-client-latest.log.txt

I just added the .txt to the end of the file so you can read it online instead of downloading it.

Just adding this in here to link your other issue together:
https://github.com/CreativeMD/InGameConfigManager/issues/8

**Comment by Ryius** [comment]
okey as the following i just try to get modular powersuit working. Modular Powersuit-0.11.0.296 and Numina-0.4.0.131 .I found that bug because i just take all my 231 mods out of my mods folder and just added 
CodeChickenCore-1.7.10-1.0.7.47-universal, 
CodeChickenLib-1.7.10-1.1.3.138-universal , 
NotEnoughItems-1.7.10-1.0.5.120-universal
Numina-0.4.0.131
ModularPowersuits-0.11.0.296
EnderIO-1.7.10-2.3.0.422_beta and EnderCore-1.7.10-0.2.0.31_beta and started the game .it had worked fine .Then i added InGameConfigManager Alpha v0.1.11 mc1.7.10 and CreativeCore v1.3.21 mc1.7.10. And all the crafting reciptes a gone from Modular powersuit .
I am gone send the link from that side to him that he knows the issue.

**Comment by Ryius** [comment]
key done

**Comment by CreativeMD** [comment]
Hello :D
InGameConfigManager 'graps' all crafting recipes at the FMLLoadCompleteEvent. Any recipes added after this event won't be recognized and will be lost.

Don't know why but it seems like these Powersuits recipes are added after InGameConfigManager 'grabs' all recipes. You could try to rename 'InGameConfigManager v0.1.1 mc1.7.10.zip' to 'zInGameConfigManager v0.1.1 mc1.7.10.zip'

**Comment by Ryius** [comment]
yeah that is a idea

**Comment by Razorskills** [comment]
I just tested adding a "z" in front of both
- CreativeCore v1.3.21 mc1.7.10
- InGameConfigManager Alpha v0.1.11 mc1.7.10

Still nothing, it doesn't seem to want to save any recipe you manually make for any of the powersuit items either.

**Comment by Xen1290** [comment]
Maybe move the Numina recipe register event?

**Comment by Razorskills** [comment]
A while back in 1.6.4 when I was making custom recipes for powersuits and items, I remember I could launch minecraft, then before making/joining a new world I could edit the recipe file and when I joined the world, all my changes where there. Does numina set the recipes as minecraft launches? or just when you load a world?

**Comment by lehjr** [comment]
Looks to me recipes are loaded when loading a world:
https://github.com/MachineMuse/Numina/blob/3d40db2fb9d09796e5048b6c0d70043b9d840693/src/main/scala/net/machinemuse/numina/basemod/NuminaProxy.scala#L49-L57

**Comment by CreativeMD** [comment]
Sorry, but it's not possible for me to move it back to server loading event.
The only way to fix this is to add those recipes to InGameConfigManager directly:
https://github.com/CreativeMD/InGameConfigManager/blob/master/src/main/java/com/creativemd/ingameconfigmanager/mod/ConfigManagerModLoader.java

``` java
ConfigManagerModLoader.workbench.disableBranch.allRecipes.add(YOUR RECIPE).
```

**Comment by Ryius** [comment]
Okey and that is the only solution ?

**Comment by Xen1290** [comment]
Oh, right, Numina register the recipes when you enter in a world because Numina downloads dynamically the recipes from the server for compatibility.

**Comment by Ryius** [comment]
so .then ther is no fix comming ?

**Comment by Razorskills** [comment]
Probably not, unless one of the devs actually want to spend a ton of time making a config for numina to load the recipes at startup instead of world load. But that would probably require a decent chunk of their time. Might not even solve the problem and be a waste of time.

**Comment by Ryius** [comment]
oh shit okey knows any one of you a mod that can help with reciped id duplications

**Comment by lehjr** [comment]
At this point in time, the primary focus in on 1.8.9, so anything in 1.7.10 that requires major work probably won't get much attention if any.

**Comment by flowtender** [comment]
sorry :(
