### ISSUE TITLE
Power helmet makes terrain (but not entities and torches) invisible in LAN game

### ISSUE THREAD

**Issue by Stalkstalks** [MachineMuse/MachineMusePowersuits#700]
A really strange bug:

When wearing a power armor helmet, if I open a single player game to LAN, as soon as someone else enters the world, both of us start being able to see through the terrain on random chunks. (They will often find themselves floating in an entity-and-torch filled abyss, except they can still interact with what the can't see.)

These are not normal chunk errors - the chunks are there, you can walk on them, break blocks on them, they work with WAILA, etc - they are just transparent. Sometimes buildings in the upper part of a chunk will be visible, but everything in the chunk below an arbitrary point will remain invisible. 

Sometimes getting closer to a chunk, or landing on it when flying, will make it render, though I will have to then land on each chunk around it to make them render as well. Sometimes we can crawl all over the chunk for quite a while and everything remains invisible.

The instant I take off my power armor helmet, everything near us becomes visible, with farther out invisible chunks taking maybe a second or two to become visible - but the problem disappears. If I put the helmet back on, it happens again.

Since it's a render issue related to the helmet  I suspected that it was related to the thaumometer upgrade, and to check I spawned in a fresh helmet, which seemed to not have the problem. After customizing the appearance (setting everything to off) and adding armor and apiarist modules back in, but before adding the thaumometer, I flew around and immediately the problem had re-asserted itself. At this point I assume it's related to the helmet's renderer? The other armor pieces don't appear to have this problem whether I make them completely invisible or if they have visible components.

I have attached a pair of screenshots - the first demonstrates this happening, and the second shows the problem disappearing the the instant I take off the helmet.

![withhelmet](https://cloud.githubusercontent.com/assets/8027410/12598146/2ecb9b5c-c44e-11e5-8981-864e9eaa322a.png)
![withouthelmet](https://cloud.githubusercontent.com/assets/8027410/12598151/3192cd38-c44e-11e5-97f0-9bbad223860f.png)

**Comment by lehjr** [comment]
While I can't confirm this, I suspect this is caused by https://github.com/MachineMuse/MachineMusePowersuits/issues/699
which also causes:
https://github.com/MachineMuse/MachineMusePowersuits/issues/658

Unfortunately, I won't be able to spend any time on this until work on the 1.8.9 port is done.

**Comment by flowtender** [comment]
I guarantee a loopback connection has more than 5 kb/s bandwidth, and even if it _was_ related to that, then it would occur with the other armour pieces as well.

**Comment by Stalkstalks** [comment]
Something that might help find the cause of the bug:

Since I thought the problem was helmet rendering related, I tired using Cosmetic Armor Reworked to hide the power armor completely. The result is that the behavior continues! If I am wearing the helmet, we have that problem, and when I take it off, it goes away.
