### ISSUE TITLE
Power Fist with Blade Upgrade duplicates when stopped by SafeZone

### ISSUE THREAD

**Issue by AtomicStryker** [MachineMuse/MachineMusePowersuits#701]
Version the bug was observed in: 0.11.0.293 / Dec 18, 2015 / on a dedicated server

How to reproduce: Install Blade upgrade into a Power fist, fire on block in a "claimed" area aka one that cannot be edited by the shooter due to the SafeZone (bukkit) plugin

Expected behaviour: Block edit fails, player gets his fist back

Actual behaviour: Block edit fails, player gets 2 fists back. Infinite fist duplication is possible.

I checked the other issues and the commits and it does not seem to have come up before. I would debug it myself but decompilers don't work well with scala, and i dont have scala setup in my workspace.

**Comment by flowtender** [comment]
This is waaaay too far outside the scope of MPS, sorry.
