### ISSUE TITLE
Recipes are missing pieces in NEI

### ISSUE THREAD

**Issue by andrewminer** [MachineMuse/MachineMusePowersuits#703]
I'm trying to use Powersuits in a custom mudpack, and NEI is showing me incorrect recipes for various items.  For example, the Tinker's Table recipe looks like:

![screen shot 2016-02-10 at 21 43 01](https://cloud.githubusercontent.com/assets/445000/12970121/4aeb776a-d03f-11e5-88cb-db2702e2eb00.png)

When the content of the ThermalExpansion recipes file shows:

```
    {
        "ingredients" : [
            [ null, { "oredictName" : "gemEmerald" }, null ],
            [ { "oredictName" : "ingotElectrum" }, { "registryName" : "ThermalExpansion:Frame"}, { "oredictName" : "ingotElectrum" } ],
            [ null, { "registryName" : "ThermalExpansion:material", "meta" : 2 }, null ]
        ],
        "result" : {
            "registryName" : "powersuits:tile.tinkerTable"
        }
    },
```

As I check through the rest of the recipes, it looks like every item which uses the `registryName` key in the recipe description instead of the `oredictName` key is missing in each recipe.  If I work out what item is required, the real recipe (not the one in NEI) does successfully allow me to make the affected items.

I'm using the auto-generated recipes file from version 0.11.0.300 and Numina 0.4.0.119 with Minecraft 1.7.10 and Forge 10.13.4.1556.  I've also got NotEnoughItems version 1.0.4.107, NEI Addons 1.12.11.36, NEI Integration 1.0.12, and NotEnoughResources 0.1.0.106.

**Comment by Xen1290** [comment]
Update Numina to latest beta version. This should fix the issue.
Thanks for the good report .

**Comment by Razorskills** [comment]
..that curseforge recommended build strikes again!

**Comment by lehjr** [comment]
It's probably "beta" vs "release".

**Comment by andrewminer** [comment]
Yup, that was it!  Seems like someone should go fix the default download on CurseForge...  I'll leave this issue open to track that.

**Comment by Razorskills** [comment]
yea build 131 should probably be set as release status since 119 is more beta then 131..

**Comment by flowtender** [comment]
Yeah, I archived the versions that were tagged as released. Sorry about that!

**Comment by Razorskills** [comment]
That fixed the issue. :D

**Comment by MCTyler** [comment]
Wow, Thanks! I have been looking at this issue for hours. Hopefully when I update Numina it won't break the client and give my players the Big Red X. I'll report back! 
EDIT: Yea Unless I direct all my Players to update this Mod, It breaks the Client...I'll just provide a Link to the recipe on my website....http://eodcraft.com/forum/view_topic/?tid=44

**Comment by MCTyler** [comment]
Ok, If you download the latest Numina and Powersuits Mod, and open the Jars and rename the version to the version that comes with DW20, they will work after you upload them to your server instead of it giving you the incorrect modded Client  RED X, since, I guess, it "tricks" the client into thinking the proper versions are installed. This way new players can join with the "default" client Mods then you can have them download the updated Mods so the recipes work. It's a crazy work around but it works! Hopes this helps someone! 
![screenshot from 2016-07-02 16-56-58](https://cloud.githubusercontent.com/assets/6390898/16542644/62592cec-4076-11e6-8a14-ccd185329a6d.png)
