### ISSUE TITLE
Many modules missing recipes

### ISSUE THREAD

**Issue by gmoff01** [MachineMuse/MachineMusePowersuits#704]
In the current version (0.11.0.300) and at least as far back as .293, many of the modules dont have recipes in NEI and cannot be crafted (at least with the recipes on ftbwiki).  Specifically:

Carbon Myofiber
Myofiber Gel
Artificial Muscle
Solar Panel
Magnet
Computer Chip
Insulated Rubber Hose
Liquid Nitrogen Bucket

**Comment by Xen1290** [comment]
Update Numina

**Comment by gmoff01** [comment]
Just tried, no effect.  To be specific, MPS 0.11.0.300 and numina 0.4.0.131 still have the problem.

**Comment by Xen1290** [comment]
Go to machinemuse config folder and reset all the configs in the folder and subfolder. This should work.

**Comment by gmoff01** [comment]
That worked, thank you for the prompt responses!

**Comment by Xen1290** [comment]
No problems 👍🏻

**Comment by flowtender** [comment]
Thanks for your help :)
