### ISSUE TITLE
crash when adding

### ISSUE THREAD

**Issue by matthewray11** [MachineMuse/MachineMusePowersuits#705]
a parachute and glider on the same chest piece

**Comment by lehjr** [comment]
Needs more information, including crash log.

**Comment by matthewray11** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MDECore-Core (mdecore-1.8.9-1.1.jar)
  BetterFoliageLoader (BetterFoliage-MC1.8.x-2.0.3.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)
  LoadingPlugin (FastLeaveDecay-1.2.jar)
  FMLPlugin (InventoryTweaks-1.60-beta-30.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 2/23/16 9:12 PM
Description: Ticking entity

java.lang.IllegalAccessError
    at net.machinemuse.powersuits.powermodule.movement.GliderModule.onPlayerTickActive(GliderModule.java:56)
    at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$1.apply(PlayerUpdateHandler.scala:46)
    at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$1.apply(PlayerUpdateHandler.scala:43)
    at scala.collection.Iterator$class.foreach(Iterator.scala:743)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.apply(PlayerUpdateHandler.scala:43)
    at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.apply(PlayerUpdateHandler.scala:40)
    at scala.collection.Iterator$class.foreach(Iterator.scala:743)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at net.machinemuse.powersuits.event.PlayerUpdateHandler.onPlayerUpdate(PlayerUpdateHandler.scala:40)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_347_PlayerUpdateHandler_onPlayerUpdate_LivingUpdateEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:458)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1563)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:283)
    at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:117)
    at net.minecraft.world.World.func_72866_a(World.java:1862)
    at net.minecraft.world.World.func_72870_g(World.java:1831)
    at net.minecraft.world.World.func_72939_s(World.java:1663)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2089)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.machinemuse.powersuits.powermodule.movement.GliderModule.onPlayerTickActive(GliderModule.java:56)
    at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$1.apply(PlayerUpdateHandler.scala:46)
    at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$1.apply(PlayerUpdateHandler.scala:43)
    at scala.collection.Iterator$class.foreach(Iterator.scala:743)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.apply(PlayerUpdateHandler.scala:43)
    at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.apply(PlayerUpdateHandler.scala:40)
    at scala.collection.Iterator$class.foreach(Iterator.scala:743)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at net.machinemuse.powersuits.event.PlayerUpdateHandler.onPlayerUpdate(PlayerUpdateHandler.scala:40)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_347_PlayerUpdateHandler_onPlayerUpdate_LivingUpdateEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:458)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1563)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:283)
    at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:117)
    at net.minecraft.world.World.func_72866_a(World.java:1862)
    at net.minecraft.world.World.func_72870_g(World.java:1831)

-- Entity being ticked --
Details:
    Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
    Entity ID: 344
    Entity Name: FuzzyNubbins
    Entity's Exact location: 23.07, 70.00, 611.01
    Entity's Block location: 23.00,70.00,611.00 - World: (23,70,611), Chunk: (at 7,4,3 in 1,38; contains blocks 16,0,608 to 31,255,623), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
    Entity's Momentum: 0.00, 0.00, 0.00
    Entity's Rider: ~~ERROR~~ NullPointerException: null
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1663)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['FuzzyNubbins'/344, l='MpServer', x=23.07, y=70.00, z=611.01]]
    Chunk stats: MultiplayerChunkCache: 121, 121
    Level seed: 0
    Level generator: ID 04 - customized, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: 122.00,64.00,210.00 - World: (122,64,210), Chunk: (at 10,4,2 in 7,13; contains blocks 112,0,208 to 127,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 63679 game time, 11216 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 81 total; [EntityFishCod['Cod'/384, l='MpServer', x=-39.56, y=15.00, z=638.81], EntityChicken['Chicken'/385, l='MpServer', x=-35.38, y=70.00, z=607.59], EntityChicken['Chicken'/386, l='MpServer', x=8.38, y=76.00, z=552.56], EntityChicken['Chicken'/387, l='MpServer', x=33.38, y=74.50, z=558.53], EntityChicken['Chicken'/388, l='MpServer', x=87.28, y=75.00, z=603.41], EntityItem['item.item.egg'/389, l='MpServer', x=80.06, y=75.00, z=597.41], EntityItem['item.item.egg'/390, l='MpServer', x=-17.03, y=69.00, z=667.59], EntityChicken['Chicken'/391, l='MpServer', x=-22.44, y=70.00, z=671.63], EntityChicken['Chicken'/392, l='MpServer', x=-22.44, y=69.00, z=664.59], EntityCreeper['Creeper'/1160, l='MpServer', x=11.50, y=42.00, z=666.50], EntityItem['item.item.egg'/393, l='MpServer', x=-22.22, y=69.00, z=664.22], EntityItem['item.item.feather'/394, l='MpServer', x=-23.13, y=69.00, z=664.16], EntityChicken['Chicken'/395, l='MpServer', x=73.50, y=73.00, z=562.69], EntityItem['item.item.egg'/396, l='MpServer', x=73.38, y=73.00, z=562.56], EntityChicken['Chicken'/397, l='MpServer', x=-9.38, y=69.50, z=678.50], EntityChicken['Chicken'/398, l='MpServer', x=-15.22, y=70.00, z=683.56], EntityChicken['Chicken'/401, l='MpServer', x=60.31, y=72.00, z=672.34], EntityItem['item.item.egg'/402, l='MpServer', x=59.84, y=72.00, z=672.44], EntityItem['item.item.egg'/403, l='MpServer', x=-23.34, y=70.00, z=672.19], EntityItem['item.item.feather'/404, l='MpServer', x=-22.44, y=70.00, z=672.06], EntityChicken['Chicken'/405, l='MpServer', x=-41.56, y=69.00, z=666.69], EntityChicken['Chicken'/407, l='MpServer', x=-55.63, y=70.00, z=614.41], EntityPig['Pig'/409, l='MpServer', x=26.28, y=77.00, z=536.09], EntityChicken['Chicken'/410, l='MpServer', x=29.06, y=71.00, z=688.19], EntityChicken['Chicken'/412, l='MpServer', x=2.66, y=70.00, z=691.63], EntityAuraNode['Aura Node'/413, l='MpServer', x=-59.50, y=89.50, z=632.50], EntityChicken['Chicken'/415, l='MpServer', x=-8.44, y=70.00, z=691.28], EntitySpider['Spider'/671, l='MpServer', x=-54.50, y=18.00, z=591.50], EntityAuraNode['Aura Node'/417, l='MpServer', x=-59.50, y=74.50, z=652.50], EntityChicken['Chicken'/418, l='MpServer', x=-53.59, y=69.00, z=591.56], EntityPig['Pig'/419, l='MpServer', x=-4.97, y=74.00, z=542.47], EntityCreeper['Creeper'/547, l='MpServer', x=58.50, y=20.00, z=629.50], EntityChicken['Chicken'/421, l='MpServer', x=49.41, y=77.00, z=541.63], EntityChicken['Chicken'/426, l='MpServer', x=71.47, y=77.50, z=534.63], EntityChicken['Chicken'/427, l='MpServer', x=67.75, y=78.00, z=532.28], EntityChicken['Chicken'/428, l='MpServer', x=67.34, y=78.00, z=534.63], EntityChicken['Chicken'/434, l='MpServer', x=96.59, y=75.00, z=575.34], EntityCreeper['Creeper'/1460, l='MpServer', x=-48.50, y=27.00, z=680.50], EntityAuraNode['Aura Node'/438, l='MpServer', x=-50.50, y=71.50, z=676.50], EntityZombie['Zombie'/1599, l='MpServer', x=84.50, y=20.00, z=578.50], EntityZombie['Herobrine'/346, l='MpServer', x=22.75, y=67.00, z=609.78], EntityItem['item.item.feather'/347, l='MpServer', x=26.69, y=71.00, z=621.28], EntityPlayerSP['FuzzyNubbins'/344, l='MpServer', x=23.07, y=70.00, z=611.01], EntityItem['item.item.egg'/349, l='MpServer', x=5.47, y=70.00, z=616.47], EntitySpider['Spider'/605, l='MpServer', x=17.50, y=40.00, z=657.59], EntityItem['item.item.feather'/350, l='MpServer', x=31.78, y=71.00, z=634.78], EntityChicken['Chicken'/351, l='MpServer', x=24.56, y=71.00, z=624.38], EntityFishCod['Cod'/352, l='MpServer', x=10.31, y=55.00, z=629.38], EntityItem['item.item.dyePowder.black'/353, l='MpServer', x=10.75, y=56.00, z=628.78], EntityItem['item.item.dyePowder.black'/354, l='MpServer', x=11.63, y=56.00, z=628.13], EntityChicken['Chicken'/355, l='MpServer', x=-0.47, y=70.00, z=617.28], EntityChicken['Chicken'/356, l='MpServer', x=29.28, y=71.00, z=650.59], EntityChicken['Chicken'/357, l='MpServer', x=25.69, y=71.00, z=655.75], EntityItem['item.item.egg'/358, l='MpServer', x=25.88, y=71.00, z=655.66], EntityChicken['Chicken'/359, l='MpServer', x=30.44, y=71.00, z=642.25], EntityItem['item.item.feather'/360, l='MpServer', x=30.00, y=71.00, z=642.88], EntityItem['item.item.feather'/361, l='MpServer', x=31.34, y=71.00, z=641.63], EntityItem['item.item.egg'/362, l='MpServer', x=29.97, y=71.00, z=642.25], EntityChicken['Chicken'/363, l='MpServer', x=-23.47, y=70.00, z=616.59], EntitySkeleton['Skeleton'/1259, l='MpServer', x=17.50, y=40.00, z=656.43], EntityItem['item.item.egg'/364, l='MpServer', x=-24.38, y=70.00, z=616.69], EntityAuraNode['Aura Node'/365, l='MpServer', x=-25.50, y=85.50, z=621.50], EntityChicken['Chicken'/366, l='MpServer', x=16.22, y=76.00, z=562.59], EntityItem['item.item.egg'/367, l='MpServer', x=16.53, y=76.00, z=562.53], EntityChicken['Chicken'/368, l='MpServer', x=21.59, y=70.00, z=661.38], EntityItem['item.item.egg'/369, l='MpServer', x=21.91, y=70.00, z=661.25], EntityItem['item.item.egg'/370, l='MpServer', x=28.47, y=71.00, z=671.34], EntityFishCod['Cod'/371, l='MpServer', x=11.50, y=24.06, z=664.50], EntityChicken['Chicken'/372, l='MpServer', x=-23.22, y=69.00, z=599.19], EntityItem['item.item.egg'/373, l='MpServer', x=-22.50, y=69.00, z=599.84], EntityChicken['Chicken'/374, l='MpServer', x=79.28, y=75.00, z=596.56], EntityBat['Bat'/375, l='MpServer', x=79.25, y=23.06, z=627.25], EntityChicken['Chicken'/376, l='MpServer', x=41.38, y=72.00, z=663.34], EntityChicken['Chicken'/377, l='MpServer', x=34.38, y=71.00, z=663.59], EntityItem['item.item.egg'/378, l='MpServer', x=34.16, y=71.00, z=664.06], EntityZombie['Zombie'/1402, l='MpServer', x=101.50, y=31.00, z=644.50], EntityChicken['Chicken'/379, l='MpServer', x=-15.59, y=70.00, z=671.28], EntityItem['item.item.feather'/380, l='MpServer', x=-15.00, y=70.00, z=670.34], EntityChicken['Chicken'/381, l='MpServer', x=-2.47, y=74.50, z=562.41], EntityItem['item.item.egg'/382, l='MpServer', x=-36.28, y=70.00, z=608.13], EntityChicken['Chicken'/383, l='MpServer', x=27.91, y=71.00, z=672.25]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:404)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    CPU: 4x AMD Athlon(tm) II X4 635 Processor
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1855254200 bytes (1769 MB) / 3129618432 bytes (2984 MB) up to 3132358656 bytes (2987 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3000M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 3, tcache: 84, allocated: 13, tallocated: 99
    FML: MCP 9.19 Powered by Forge 11.15.1.1761 Optifine OptiFine_1.8.9_HD_U_H2 60 mods loaded, 59 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1761.jar) 
    UCHIJAAAA   Forge{11.15.1.1761} [Minecraft Forge](forge-1.8.9-11.15.1.1761.jar) 
    UCHIJAAAA   Baubles{1.1.3.0} [Baubles](Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJAAAA   3DManeuverGear{1.7.10-@MAJOR@.@MINOR@.@REVIS@} [3D Maneuver Gear](3DManeuverGear-1.8.9-0.5.jar) 
    UCHIJAAAA   basemetals{1.6.4} [Base Metals](BaseMetals-1.6.4.jar) 
    UCHIJAAAA   bdlib{1.10.0.23} [BD Lib](bdlib-1.10.0.23-mc1.8.9.jar) 
    UCHIJAAAA   BetterFoliage{2.0.3} [Better Foliage](BetterFoliage-MC1.8.x-2.0.3.jar) 
    UCHIJAAAA   bigtrees{0.2} [The BigTrees Mod](bigtrees-0.2-1.8.9.jar) 
    UCHIJAAAA   BiomesOPlenty{3.0.0} [Biomes O' Plenty](BiomesOPlenty-1.8.9-3.0.0.1859-universal.jar) 
    UCHIJAAAA   bookshelfapi{2.3.2} [Bookshelf](Bookshelf-1.8.9-2.3.2.jar) 
    UCHIJAAAA   Thaumcraft{5.1.6} [Thaumcraft](Thaumcraft-1.8.9-5.1.6.jar) 
    UCHIJAAAA   Botania{r1.8-249} [Botania](Botania.r1.8-248-MC1.8-0.6.1.jar) 
    UCHIJAAAA   buildingbrickscompatvanilla{1.8.9-1.3.2} [Building Bricks Vanilla Compat](BuildingBricks-1.8.9-1.3.2.jar) 
    UCHIJAAAA   buildingbricks{1.8.9-1.3.2} [Building Bricks](BuildingBricks-1.8.9-1.3.2.jar) 
    UCHIJAAAA   chancecubes{@VERSION@} [Chance Cubes](ChanceCubes-1.8.9-1.6.2.76.jar) 
    UCHIJAAAA   chisel{@VERSION@} [Chisel](Chisel-MC1.8.9-0.0.2.6.jar) 
    UCHIJAAAA   CustomBackgrounds{1.0} [Custom Backgrounds](CustomBackgrounds-1.0 %281%29.jar) 
    UCHIJAAAA   customnpcs{1.8.9_beta} [CustomNPCs](CustomNpcs_1.8.9_beta%2821feb16%29.jar) 
    UCHIJAAAA   ds{1.8.9-0.0.5.1} [Decorative Styles](DecorativeStyles-1.8.9-0.0.5.1.jar) 
    UCHIJAAAA   FastLeaveDecay{1.1} [Fast Leave Decay](FastLeaveDecay-1.2.jar) 
    UCHIJAAAA   advgenerators{0.9.19.3} [Advanced Generators](generators-0.9.19.3-mc1.8.9.jar) 
    UCHIJAAAA   gravestone{1.1.3} [Gravestone](Gravestone Mod 1.1.3.jar) 
    UCHIJAAAA   immcraft{1.1.0} [Immersive Craft](immcraft-1.1.0.jar) 
    UCHIJAAAA   inventorytweaks{1.60-beta-30-48a432c} [Inventory Tweaks](InventoryTweaks-1.60-beta-30.jar) 
    UCHIJAAAA   ironbackpacks{1.8.9-2.0.5} [Iron Backpacks](IronBackpacks-1.8.9-2.0.5.jar) 
    UCHIJAAAA   ifinder{1.0} [ItemFinder](ItemFinder-1.8.9-1.0.jar) 
    UCHIJAAAA   iwomo{0.1} [The I want more Mod](iwantmore-0.0.1.jar) 
    UCHIJAAAA   JEI{2.25.11.150} [Just Enough Items](jei_1.8.9-2.25.11.150.jar) 
    UCHIJAAAA   JEIAddons{0.11.2.56} [Just Enough Items Addons](JEIAddons_1.8.9-0.11.2.56.jar) 
    UCHIJAAAA   journeymap{5.1.3} [JourneyMap](journeymap-1.8.8-5.1.3-unlimited.jar) 
    UCHIJAAAA   jaff{1.4.1_for_1.8.9} [Just a Few Fish](JustAFewFish-1.4.1_for_1.8.9.jar) 
    UCHIJAAAA   jeresources{0.3.1} [Just Enough Resources](JustEnoughResources-1.8.9-0.3.1.jar) 
    UCHIJAAAA   mantle{1.8.9-0.7.jenkins72} [Mantle](Mantle-1.8.9-0.7.jar) 
    UCHIJAAAA   RadixCore{1.8.9-2.1.0} [RadixCore](RadixCore-1.8.9-2.1.0-universal.jar) 
    UCHIJAAAA   MCA{1.8.9-5.1.1.2} [Minecraft Comes Alive](MCA-1.8.9-5.1.1.2-universal.jar) 
    UCHIJAAAA   mdecore{1.8.9-1.1} [MattDahEpic Core](mdecore-1.8.9-1.1.jar) 
    UCHIJAAAA   mineralogy{2.6.0} [Mineralogy](mineralogy-2.6.0.jar) 
    UCHIJAAAA   numina{0.4.0.131.jar} [Numina](ModularPowersuits-1.8.9-0.0.1-1.jar) 
    UCHIJAAAA   powersuits{1.0} [powersuits](ModularPowersuits-1.8.9-0.0.1-1.jar) 
    UCHIJAAAA   moneymod{1.1.0} [Money Mod](MoneyMod 1.1.0.jar) 
    UCHIJAAAA   shear{1.0} [More Shearables](MoreShearables1.0-1.8.9.jar) 
    UCHIJAAAA   MouseTweaks{2.6.0} [Mouse Tweaks](MouseTweaks-2.6.0-mc1.8.9.jar) 
    UCHIJAAAA   cfm{3.6} [MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.6.1%281.8.9%29.jar) 
    UCHIJAAAA   Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat](Neat 1.1-2.jar) 
    UCHIJAAAA   neotech{2.3.7} [NeoTech](NeoTech-1.8.9-2.3.7.jar) 
    UCHIJAAAA   samsocean{1.0.0} [Classic Oceans](OceanFloor-1.8.9-1.0.0.jar) 
    UCHIJAAAA   mrdimkaraytracelib{0.0.1} [MrDimka's Ray Trace Library](RayTraceLib_1.8.9-0.0.1.jar) 
    UCHIJAAAA   ringkydinks{1.8.9-beta2} [Ringky Dinks](ringkydinks-1.8.9-beta2.jar) 
    UCHIJAAAA   ropebridge{1.3} [Rope Bridge](RopeBridge-v1.3-mc1.8.8.jar) 
    UCHIJAAAA   rouletteores{1.1.16} [RouletteOres](RouletteOres-1.1.16.jar) 
    UCHIJAAAA   SilentGems{1.3.9b} [Silent's Gems](SilentsGems-1.8.9-1.3.9b-102.jar) 
    UCHIJAAAA   superores{1.1} [Super Ores](Super Ores V1.1 mc1.8.9.jar) 
    UCHIJAAAA   tconstruct{1.8.9-2.0.2.jenkins61} [Tinkers' Construct](TConstruct-1.8.9-2.0.2.jar) 
    UCHIJAAAA   thaumicadditions{0.39} [Thaumic Additions](Thaumic Additions - 1.8.9 - 0.39.jar) 
    UCHIJAAAA   VeinMiner{0.31.2_build.unknown} [Vein Miner](VeinMiner-1.8.9_0.31.2.unknown.jar) 
    UCHIJAAAA   VeinMinerModSupport{0.31.2_build.unknown} [Mod Support](VeinMiner-1.8.9_0.31.2.unknown.jar) 
    UCHIJAAAA   wallz{1.0} [wallz](Wallz1.0.1.jar) 
    UCHIJAAAA   WIT{1.0.6} [WIT](WIT-1.8.9-1.0.6-17.jar) 
    UD  mdecore-core{1.0} [MDE Core - ASM Tweaks](minecraft.jar) 
    Loaded coremods (and transformers): 
MDECore-Core (mdecore-1.8.9-1.1.jar)
  com.mattdahepic.mdecore.asm.TickrateTransformer
BetterFoliageLoader (BetterFoliage-MC1.8.x-2.0.3.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.6.jar)

LoadingPlugin (FastLeaveDecay-1.2.jar)
  lumien.fastleavedecay.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.60-beta-30.jar)
  invtweaks.forge.asm.ContainerTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 361.75' Renderer: 'GeForce GT 610/PCIe/SSE2'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - TinkerDebug (Enabled/Not Forced)

```
List of loaded APIs: 
    * Baubles|API (1.1.1.0) from ringkydinks-1.8.9-beta2.jar
    * BotaniaAPI (76) from Botania.r1.8-248-MC1.8-0.6.1.jar
    * ChiselAPI (0.0.1) from Chisel-MC1.8.9-0.0.2.6.jar
    * ChiselAPI|Carving (0.0.1) from Chisel-MC1.8.9-0.0.2.6.jar
    * CoFHAPI (1.7.10R1.0.2) from Thaumic Additions - 1.8.9 - 0.39.jar
    * CoFHAPI|energy (1.8.9R1.2.0B1) from Bookshelf-1.8.9-2.3.2.jar
    * Core (0.1) from CustomNpcs_1.8.9_beta(21feb16).jar
    * Core|Blocks (0.1) from CustomNpcs_1.8.9_beta(21feb16).jar
    * Core|Constants (0.1) from CustomNpcs_1.8.9_beta(21feb16).jar
    * Core|Entities (0.1) from CustomNpcs_1.8.9_beta(21feb16).jar
    * Core|Entities|Data (0.1) from CustomNpcs_1.8.9_beta(21feb16).jar
    * Core|Entities|Data|Role (0.1) from CustomNpcs_1.8.9_beta(21feb16).jar
    * Core|Events (0.1) from CustomNpcs_1.8.9_beta(21feb16).jar
    * Core|Handlers (0.1) from CustomNpcs_1.8.9_beta(21feb16).jar
    * Core|Handlers|Data (0.1) from CustomNpcs_1.8.9_beta(21feb16).jar
    * IronBackpacks|API (0.4) from IronBackpacks-1.8.9-2.0.5.jar
    * jeresources|API (0.3.1) from JustEnoughResources-1.8.9-0.3.1.jar
    * JustEnoughItemsAPI (2.10.1) from Thaumic Additions - 1.8.9 - 0.39.jar
    * ThaumAdditAPI|Master (6) from Thaumic Additions - 1.8.9 - 0.39.jar
    * Thaumcraft|API (5.1.2.0) from Thaumcraft-1.8.9-5.1.6.jar
    * VeinMinerApi (0.1) from VeinMiner-1.8.9_0.31.2.unknown.jar
Launched Version: 1.8.9-forge1.8.9-11.15.1.1761
LWJGL: 2.9.4
OpenGL: GeForce GT 610/PCIe/SSE2 GL version 4.5.0 NVIDIA 361.75, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x AMD Athlon(tm) II X4 635 Processor
```

**Comment by lehjr** [comment]
As I stated on the forums in a page or 2 back, "...  Keep in mind that it is very buggy and it is not meant for every day gameplay in a world you want to keep but rather for getting a feel for what the current state of the mod is, kinda like a tech preview or a ROM from XDA ("everything works except a long list of broken features"). Also keep in mind that we won't be accepting bug reports for early builds. Yes things are broken, we know."

**Comment by lehjr** [comment]
Meaning that we are not taking bug reports for the alpha builds yet. It is a very early work in progress

**Comment by matthewray11** [comment]
its ok I understand

**Comment by lehjr** [comment]
As I just mentioned on the forums, the armor customization screen will also crash the game as will the power fist when trying to break stone. Lot's of things are still broken or buggy. The new rendering system is taking most of the time I have to work on the mod.
