### ISSUE TITLE
Powersuits seems to crash server. 

### ISSUE THREAD

**Issue by iceman11a** [MachineMuse/MachineMusePowersuits#708]
Here's the crash log.
http://pastebin.com/vP4jr8aw

I just downloaded ModularPowersuits-0.11.0.300 and every time I start the server. It crashes. I all so added these 2 files. and they don't seem to crash the server. 

ModularPowersuitsAddons-1.7.10.zip
Numina-0.4.0.131.jar

I wish you had a Espernet IRC channel

**Comment by lehjr** [comment]
A couple things. First, there is an espernet IRC channel, #Numina
Second, the addons were merged months ago, and the version of the addons you downloaded hasn't been compatible for a long time before that.

**Comment by iceman11a** [comment]
Well then there's some thing wrong. Here's the web site for the addons. and it says version 1.7.10-900 is the current version and I have powersuitaddons-1.7.10-901, So the one I have is newer. So I'm not sure what is going on. Do you have the right URL to download the right addons for ModularPowersuits.

Here's the URL for what I downloaded. 
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293401-modular-powersuits-addons-mpsa-requires-modular

**Comment by eyeonus** [comment]
The add-ons have been integrated into the main mod months ago. Update power
suits to the latest beta and REMOVE the add-ons mod.

**Comment by iceman11a** [comment]
Thanks. I did that. and the only 2 files I have are the 
ModularPowersuits-0.11.0.300.jar
and
Numina-0.4.0.131.jar.

As far as I know. These are the newest files I can find

It crashed again. The crash report is below. 
http://pastebin.com/Q2xuNzFR

**Comment by lehjr** [comment]
update applied energistics. That version is older than dirt.

edit: and probably extra cells too

**Comment by iceman11a** [comment]
Thanks. I just check that all so. Here's the URL. http://ae-mod.info/Downloads/
The newest one that have is RV2 Build 10. All the others are only beta's and Alpha's. and they told me not to run those. Until testing is completed and they are stable.

**Comment by lehjr** [comment]
problem is their "stable" is just unchanging, not less buggy and the last RV2 update was 7 months ago. Lots of things have changed since then, and mixing old and new mods generally doesn't end well.

**Comment by iceman11a** [comment]
Yes I know what you mean. Can you tell me what version of AE2 I should download and use. How ever what does AE2 have to do with ModularPowersuits...

**Comment by lehjr** [comment]
Modular powersuits has support for the wireless terminal, specifically a module that can be added to the powerfist. Any RV3 version should work. I haven't had the chance to play in months because I have been busy porting MPS to 1.8.9, so I can't say for sure what version works. The last version I used was RV3 beta 5

**Comment by eyeonus** [comment]
The stablr rv2 works perfectly fine in my mod pack, so I'm not sure that's
the problem.

On Mon, Feb 29, 2016 at 6:37 PM, lehjr notifications@github.com wrote:

> Modular powersuits has support for the wireless terminal, specifically a
> module that can be added to the powerfist. Any RV3 version should work. I
> haven't had the chance to play in months because I have been busy porting
> MPS to 1.8.9, so I can't say for sure what version works. The last version
> I used was RV3 beta 5
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MachineMuse/MachineMusePowersuits/issues/708#issuecomment-190484473
> .

## 

mu'o mi'e .aionys.

.i.e'ucai ko cmima lo pilno be denpa bu .i doi.luk. mi patfu do zo'o
(Come to the Dot Side! Luke, I am your father. :D )

**Comment by iceman11a** [comment]
I posted the crash report above. in a earlier post. Your well come to take a look.

**Comment by lehjr** [comment]
Yeah, I read that again. You might be able to use RV2 with a newer build of extra cells, but the error is extra cells. They changed their API usage and I had to update the wireless module for that. It was months ago so I had forgotten about it.

**Comment by lehjr** [comment]
MPS has wireless terminal modules for both AE2 and EC2, but the code is somewhat version specific.

**Comment by iceman11a** [comment]
Thank you. I guess it was extracells causing the crash. I'm up and running, Thanks again.
