### ISSUE TITLE
[Crash] 1.8.9 alpha1 Putting on powersuit crashes to desktop/doesn't render

### ISSUE THREAD

**Issue by jawsawn** [MachineMuse/MachineMusePowersuits#709]
Just testing it i had problems with the armor. It is unstable, it doesn't render when on and wearing the chestplate crashes me. 
Using from the curseforge site. Is there latest downloads in a different site somewhere? like jenkins?

**Comment by Xen1290** [comment]
Crash report? Mods versions? Mod list? Without those informations we can't help you.
