### ISSUE TITLE
jetpack crash

### ISSUE THREAD

**Issue by reinder-s** [MachineMuse/MachineMusePowersuits#711]
windows 10
java 8
forge 1.8.9-forge1.8.9-11.15.1.1761
mod version 1.8.9-0.11.0-002

when i put the jetpack module on and jumped i crashed
here is the report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.8.9-0.3.0.10-beta.jar)
  LoadingPlugin (RandomThings-MC1.8.9-3.6.5.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.2.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 17-3-16 12:09
Description: Ticking entity

java.lang.IllegalAccessError
    at net.machinemuse.utils.MusePlayerUtils.thrust(MusePlayerUtils.java:195)
    at net.machinemuse.powersuits.powermodule.movement.JetPackModule.onPlayerTickActive(JetPackModule.java:77)
    at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$1.apply(PlayerUpdateHandler.scala:46)
    at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$1.apply(PlayerUpdateHandler.scala:43)
    at scala.collection.Iterator$class.foreach(Iterator.scala:743)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.apply(PlayerUpdateHandler.scala:43)
    at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.apply(PlayerUpdateHandler.scala:40)
    at scala.collection.Iterator$class.foreach(Iterator.scala:743)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at net.machinemuse.powersuits.event.PlayerUpdateHandler.onPlayerUpdate(PlayerUpdateHandler.scala:40)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_553_PlayerUpdateHandler_onPlayerUpdate_LivingUpdateEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:458)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1563)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:283)
    at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:117)
    at net.minecraft.world.World.func_72866_a(World.java:1862)
    at net.minecraft.world.World.func_72870_g(World.java:1831)
    at net.minecraft.world.World.func_72939_s(World.java:1663)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2089)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.machinemuse.utils.MusePlayerUtils.thrust(MusePlayerUtils.java:195)
    at net.machinemuse.powersuits.powermodule.movement.JetPackModule.onPlayerTickActive(JetPackModule.java:77)
    at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$1.apply(PlayerUpdateHandler.scala:46)
    at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2$$anonfun$apply$1.apply(PlayerUpdateHandler.scala:43)
    at scala.collection.Iterator$class.foreach(Iterator.scala:743)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.apply(PlayerUpdateHandler.scala:43)
    at net.machinemuse.powersuits.event.PlayerUpdateHandler$$anonfun$onPlayerUpdate$2.apply(PlayerUpdateHandler.scala:40)
    at scala.collection.Iterator$class.foreach(Iterator.scala:743)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at net.machinemuse.powersuits.event.PlayerUpdateHandler.onPlayerUpdate(PlayerUpdateHandler.scala:40)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_553_PlayerUpdateHandler_onPlayerUpdate_LivingUpdateEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:458)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1563)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:283)
    at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:117)
    at net.minecraft.world.World.func_72866_a(World.java:1862)
    at net.minecraft.world.World.func_72870_g(World.java:1831)

-- Entity being ticked --
Details:
    Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
    Entity ID: 3866
    Entity Name: reinder
    Entity's Exact location: 246,37, 63,00, -135,86
    Entity's Block location: 246,00,63,00,-136,00 - World: (246,63,-136), Chunk: (at 6,3,8 in 15,-9; contains blocks 240,0,-144 to 255,255,-129), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
    Entity's Momentum: 0,00, -0,08, 0,00
    Entity's Rider: ~~ERROR~~ NullPointerException: null
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1663)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['reinder'/3866, l='MpServer', x=246,37, y=63,00, z=-135,86]]
    Chunk stats: MultiplayerChunkCache: 441, 441
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: 228,00,64,00,148,00 - World: (228,64,148), Chunk: (at 4,4,4 in 14,9; contains blocks 224,0,144 to 239,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 10266840 game time, 6000 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 102 total; [EntityBat['Bat'/26122, l='MpServer', x=192,50, y=18,51, z=-141,40], EntityCreeper['Creeper'/38672, l='MpServer', x=266,50, y=35,00, z=-85,50], EntityCreeper['Creeper'/38673, l='MpServer', x=265,50, y=35,00, z=-85,50], EntityCreeper['Creeper'/38674, l='MpServer', x=265,50, y=35,00, z=-91,50], EntitySkeleton['Skeleton'/25876, l='MpServer', x=190,19, y=16,00, z=-167,25], EntityPlayerSP['reinder'/3866, l='MpServer', x=246,37, y=63,00, z=-135,86], EntityWisp['Wisp'/3870, l='MpServer', x=235,19, y=47,05, z=-144,69], EntityItem['item.item.bone'/6430, l='MpServer', x=199,88, y=13,00, z=-170,03], EntityItemFrame['entity.ItemFrame.name'/3874, l='MpServer', x=216,50, y=63,50, z=-142,03], EntityItemFrame['entity.ItemFrame.name'/3875, l='MpServer', x=215,97, y=63,50, z=-141,50], EntitySpark['Spark'/3876, l='MpServer', x=214,50, y=64,50, z=-131,50], EntitySpark['Spark'/3877, l='MpServer', x=217,50, y=64,50, z=-140,50], EntityWitch['Witch'/36389, l='MpServer', x=316,47, y=65,00, z=-106,09], EntitySpark['Spark'/3878, l='MpServer', x=217,50, y=64,50, z=-129,50], EntityWitch['Witch'/36390, l='MpServer', x=325,50, y=64,00, z=-97,50], EntitySquid['Squid'/3880, l='MpServer', x=260,20, y=55,28, z=-140,46], EntityCreeper['Creeper'/35880, l='MpServer', x=316,50, y=23,00, z=-107,50], EntitySpark['Spark'/3882, l='MpServer', x=217,50, y=64,50, z=-123,50], EntitySkeleton['Skeleton'/40490, l='MpServer', x=192,50, y=24,00, z=-117,50], EntitySpark['Spark'/3883, l='MpServer', x=214,50, y=64,50, z=-117,50], EntitySkeleton['Skeleton'/36152, l='MpServer', x=287,50, y=15,00, z=-174,50], EntityCreeper['Creeper'/31545, l='MpServer', x=200,78, y=41,00, z=-108,81], EntitySkeleton['Skeleton'/36153, l='MpServer', x=294,50, y=15,00, z=-177,50], EntityCreeper['Creeper'/31546, l='MpServer', x=203,50, y=41,00, z=-107,50], EntityCreeper['Creeper'/23100, l='MpServer', x=258,50, y=30,00, z=-97,50], EntityCreeper['Creeper'/35901, l='MpServer', x=176,00, y=21,00, z=-148,53], EntitySheep['Sheep'/3905, l='MpServer', x=209,84, y=62,07, z=-91,47], EntitySheep['Sheep'/3907, l='MpServer', x=193,50, y=74,00, z=-108,50], EntityPech['Pech Stalker'/35139, l='MpServer', x=219,50, y=39,00, z=-176,50], EntityZombie['Zombie'/40517, l='MpServer', x=268,50, y=33,00, z=-117,50], EntityItem['item.item.dyePowder.black'/12107, l='MpServer', x=267,34, y=57,00, z=-107,69], EntityAuraNode['Aura Node'/3929, l='MpServer', x=258,50, y=61,50, z=-206,53], EntityAuraNode['Aura Node'/3930, l='MpServer', x=259,25, y=62,19, z=-206,86], EntityThaumcraftGolem['Golem'/3932, l='MpServer', x=269,44, y=63,00, z=-201,50], EntitySheep['Sheep'/3933, l='MpServer', x=316,66, y=63,00, z=-117,56], EntityItemFrame['entity.ItemFrame.name'/3943, l='MpServer', x=218,97, y=63,50, z=-195,50], EntityItemFrame['entity.ItemFrame.name'/3944, l='MpServer', x=218,97, y=63,50, z=-196,50], EntityItemFrame['entity.ItemFrame.name'/3945, l='MpServer', x=218,97, y=64,50, z=-193,50], EntityItemFrame['entity.ItemFrame.name'/3946, l='MpServer', x=218,97, y=64,50, z=-195,50], EntityItemFrame['entity.ItemFrame.name'/3947, l='MpServer', x=218,97, y=65,50, z=-195,50], EntityItemFrame['entity.ItemFrame.name'/3948, l='MpServer', x=218,97, y=65,50, z=-196,50], EntityItemFrame['entity.ItemFrame.name'/3949, l='MpServer', x=218,97, y=64,50, z=-196,50], EntityItem['item.item.bone'/35693, l='MpServer', x=190,09, y=16,00, z=-168,03], EntityTurretCrossbowAdvanced['Advanced Automated Crossbow'/3950, l='MpServer', x=304,50, y=63,00, z=-169,50], EntitySheep['Sheep'/3951, l='MpServer', x=200,78, y=67,00, z=-74,47], EntityAuraNode['Aura Node'/3953, l='MpServer', x=318,50, y=64,50, z=-187,50], EntityAuraNode['Aura Node'/3954, l='MpServer', x=308,50, y=119,50, z=-185,50], EntityResizableCuboid['unknown'/4210, l='MpServer', x=116,25, y=68,00, z=-194,75], EntityAuraNode['Aura Node'/3955, l='MpServer', x=311,47, y=119,50, z=-185,50], EntityResizableCuboid['unknown'/4211, l='MpServer', x=118,25, y=7,00, z=-219,75], EntityAuraNode['Aura Node'/3956, l='MpServer', x=308,50, y=119,50, z=-182,53], EntityAuraNode['Aura Node'/3957, l='MpServer', x=311,49, y=119,50, z=-182,51], EntityBrainyZombie['Angry Zombie'/39285, l='MpServer', x=192,50, y=60,00, z=-111,94], EntityAuraNode['Aura Node'/3958, l='MpServer', x=314,47, y=119,50, z=-185,50], EntityAuraNode['Aura Node'/3959, l='MpServer', x=314,49, y=119,50, z=-182,51], EntitySquid['Squid'/14458, l='MpServer', x=257,47, y=61,15, z=-154,24], EntitySheep['Sheep'/3963, l='MpServer', x=205,28, y=65,00, z=-64,88], EntityItem['item.item.dyePowder.black'/32892, l='MpServer', x=285,75, y=48,00, z=-148,88], EntitySquid['Squid'/38782, l='MpServer', x=278,00, y=48,00, z=-139,41], EntitySquid['Squid'/38783, l='MpServer', x=281,66, y=50,00, z=-138,03], EntityBat['Bat'/40319, l='MpServer', x=178,69, y=14,04, z=-176,31], EntityZombie['Zombie'/31104, l='MpServer', x=266,50, y=34,00, z=-110,50], EntitySquid['Squid'/38784, l='MpServer', x=287,91, y=47,81, z=-133,44], EntitySquid['Squid'/38785, l='MpServer', x=275,95, y=47,01, z=-127,91], EntitySquid['Squid'/38787, l='MpServer', x=278,94, y=47,97, z=-147,53], EntityAuraNode['Aura Node'/3973, l='MpServer', x=196,50, y=12,50, z=-215,50], EntitySquid['Squid'/38789, l='MpServer', x=274,75, y=48,22, z=-135,81], EntityCreeper['Creeper'/38030, l='MpServer', x=202,50, y=21,00, z=-168,50], EntityCreeper['Creeper'/36752, l='MpServer', x=184,50, y=69,00, z=-64,50], EntityCreeper['Creeper'/38036, l='MpServer', x=205,50, y=47,00, z=-199,50], EntityBrainyZombie['Angry Zombie'/34197, l='MpServer', x=214,50, y=40,00, z=-107,50], EntityBrainyZombie['Angry Zombie'/34198, l='MpServer', x=212,50, y=40,00, z=-106,50], EntityBrainyZombie['Angry Zombie'/34199, l='MpServer', x=213,19, y=40,00, z=-111,09], EntitySquid['Squid'/14488, l='MpServer', x=289,16, y=62,44, z=-76,00], EntityZombie['Zombie'/27808, l='MpServer', x=201,50, y=20,00, z=-174,50], EntitySquid['Squid'/14497, l='MpServer', x=269,75, y=57,86, z=-130,92], EntitySquid['Squid'/14498, l='MpServer', x=265,68, y=59,10, z=-154,36], EntityBat['Bat'/35236, l='MpServer', x=173,55, y=49,10, z=-84,48], EntityBat['Bat'/35238, l='MpServer', x=174,63, y=48,48, z=-78,52], EntityBat['Bat'/35241, l='MpServer', x=177,96, y=46,11, z=-78,16], EntityBat['Bat'/35242, l='MpServer', x=176,90, y=46,92, z=-77,42], EntityZombie['Zombie'/40366, l='MpServer', x=174,50, y=16,00, z=-140,50], EntityAuraNode['Aura Node'/4028, l='MpServer', x=123,50, y=80,50, z=-80,50], EntityCreeper['Creeper'/36030, l='MpServer', x=206,47, y=26,00, z=-190,00], EntitySkeleton['Skeleton'/33992, l='MpServer', x=194,50, y=16,00, z=-180,50], EntitySkeleton['Skeleton'/27593, l='MpServer', x=254,50, y=14,00, z=-65,50], EntitySkeleton['Skeleton'/39890, l='MpServer', x=305,50, y=40,00, z=-131,50], EntitySkeleton['Skeleton'/39891, l='MpServer', x=302,50, y=40,00, z=-132,50], EntitySkeleton['Skeleton'/39892, l='MpServer', x=308,50, y=40,00, z=-134,50], EntityCreeper['Creeper'/32216, l='MpServer', x=259,50, y=29,00, z=-85,50], EntityCreeper['Creeper'/32990, l='MpServer', x=191,50, y=12,00, z=-151,50], EntitySkeleton['Skeleton'/38116, l='MpServer', x=302,59, y=17,00, z=-115,63], EntityCreeper['Creeper'/27111, l='MpServer', x=217,50, y=30,00, z=-162,50], EntityCreeper['Creeper'/38122, l='MpServer', x=229,41, y=17,00, z=-157,50], EntityCreeper['Creeper'/38123, l='MpServer', x=222,50, y=17,00, z=-155,50], EntityCreeper['Creeper'/38124, l='MpServer', x=236,19, y=20,00, z=-160,13], EntitySkeleton['Skeleton'/38125, l='MpServer', x=228,22, y=17,00, z=-156,16], EntitySkeleton['Skeleton'/38126, l='MpServer', x=229,06, y=17,00, z=-156,56], EntitySkeleton['Skeleton'/38127, l='MpServer', x=227,66, y=17,00, z=-153,56], EntityBat['Bat'/31984, l='MpServer', x=178,75, y=15,09, z=-144,63], EntityZombie['Infested Zombie'/39669, l='MpServer', x=177,50, y=47,00, z=-168,50], EntityZombie['Zombie'/39670, l='MpServer', x=177,50, y=14,00, z=-176,50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1159912200 bytes (1106 MB) / 2567856128 bytes (2448 MB) up to 4281597952 bytes (4083 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
    FML: MCP 9.19 Powered by Forge 11.15.1.1761 44 mods loaded, 44 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1761.jar) 
    UCHIJAAAA   Forge{11.15.1.1761} [Minecraft Forge](forge-1.8.9-11.15.1.1761.jar) 
    UCHIJAAAA   Waila{1.6.0} [Waila](Waila-1.6.0-B3_1.8.8.jar) 
    UCHIJAAAA   Baubles{1.1.3.0} [Baubles](Baubles-1.8.9-1.1.3.0.jar) 
    UCHIJAAAA   intangible{0.0.25} [Intangible](intangible-1.8.9-0.0.25.jar) 
    UCHIJAAAA   JEI{2.28.7.174} [Just Enough Items](jei_1.8.9-2.28.7.174.jar) 
    UCHIJAAAA   BloodMagic{1.8.9-2.0.0-19} [Blood Magic: Alchemical Wizardry](BloodMagic-1.8.9-2.0.0-19.jar) 
    UCHIJAAAA   bookshelfapi{2.3.6} [Bookshelf](Bookshelf-API-1.8.9-2.3.6.jar) 
    UCHIJAAAA   Thaumcraft{5.2.2} [Thaumcraft](Thaumcraft-1.8.9-5.2.2.jar) 
    UCHIJAAAA   Botania{r1.8-299} [Botania](Botania-unofficial.r1.8-299.jar) 
    UCHIJAAAA   BuildCraft|Core{7.2.0-pre12} [BuildCraft](buildcraft-7.2.0-pre12.jar) 
    UCHIJAAAA   BuildCraft|Transport{7.2.0-pre12} [BC Transport](buildcraft-7.2.0-pre12.jar) 
    UCHIJAAAA   BuildCraft|Energy{7.2.0-pre12} [BC Energy](buildcraft-7.2.0-pre12.jar) 
    UCHIJAAAA   BuildCraft|Factory{7.2.0-pre12} [BC Factory](buildcraft-7.2.0-pre12.jar) 
    UCHIJAAAA   BuildCraft|Silicon{7.2.0-pre12} [BC Silicon](buildcraft-7.2.0-pre12.jar) 
    UCHIJAAAA   BuildCraft|Robotics{7.2.0-pre12} [BC Robotics](buildcraft-7.2.0-pre12.jar) 
    UCHIJAAAA   BuildCraft|Builders{7.2.0-pre12} [BC Builders](buildcraft-7.2.0-pre12.jar) 
    UCHIJAAAA   mcmultipart{1.0.8} [MCMultiPart](MCMultiPart-1.0.8-universal.jar) 
    UCHIJAAAA   chiselsandbits{8.3} [Chisels & Bits](chiselsandbits-8.3.jar) 
    UCHIJAAAA   ComputerCraft{1.79pr1} [ComputerCraft](ComputerCraft1.79pr1.jar) 
    UCHIJAAAA   ElecCore{1.4.240} [ElecCore](ElecCore-1.8.9-1.4.240.jar) 
    UCHIJAAAA   deepresonance{1.1.4beta17} [DeepResonance](deepresonance-1.8.9-1.1.4beta17.jar) 
    UCHIJAAAA   endercore{1.8.9-0.3.0.10-beta} [EnderCore](EnderCore-1.8.9-0.3.0.10-beta.jar) 
    UCHIJAAAA   EnderIO{1.8.9-3.0.0.10_alpha} [Ender IO](EnderIO-1.8.9-3.0.0.10_alpha.jar) 
    UCHIJAAAA   exnihilo2{0.28} [Ex Nihilo 2](ExNihilo2-0.28.jar) 
    UCHIJAAAA   flatcoloredblocks{mc1.8.9-v1.8} [Flat Colored Blocks](flatcoloredblocks-mc1.8.9-v1.8.jar) 
    UCHIJAAAA   IGWMod{1.2.4-4} [In-Game wiki Mod](IGW-Mod-1.8.9-1.2.4-4-universal.jar) 
    UCHIJAAAA   IronChest{6.0.125.770} [Iron Chest](ironchest-1.8.9-6.0.125.770.jar) 
    UCHIJAAAA   JEIAddons{0.12.0.57} [Just Enough Items Addons](JEIAddons_1.8.9-0.12.0.57.jar) 
    UCHIJAAAA   jeresources{0.4.0} [Just Enough Resources](JustEnoughResources-1.8.9-0.4.0.jar) 
    UCHIJAAAA   mantle{1.8.9-0.9.0.jenkins97} [Mantle](Mantle-1.8.9-0.9.0.jar) 
    UCHIJAAAA   testdummy{1.0} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.9b.jar) 
    UCHIJAAAA   numina{0.5.0-001} [Numina](Numina-0.5.0-001.jar) 
    UCHIJAAAA   powersuits{0.11.0-002} [MachineMuse's Modular Powersuits](ModularPowersuits-1.8.9-0.11.0-002.jar) 
    UCHIJAAAA   tconstruct{1.8.9-2.2.0.jenkins133} [Tinkers' Construct](TConstruct-1.8.9-2.2.0a.jar) 
    UCHIJAAAA   neotech{2.4.1} [NeoTech](NeoTech-1.8.9-2.4.1.jar) 
    UCHIJAAAA   PneumaticCraft{1.13.8-12} [PneumaticCraft](PneumaticCraft-1.8.9-1.13.8-12-universal.jar) 
    UCHIJAAAA   practicalities{2.0.0-b6} [Practicalities](practicalities-1.8.9-2.0.0-b6.jar) 
    UCHIJAAAA   Psi{beta-23} [Psi](Psi-beta-23.jar) 
    UCHIJAAAA   randomthings{3.6.5} [Random Things](RandomThings-MC1.8.9-3.6.5.jar) 
    UCHIJAAAA   rftools{4.22beta31} [RFTools](rftools-1.8.9-4.22beta31.jar) 
    UCHIJAAAA   rftoolsdim{4.22beta27} [RFTools Dimensions](rftoolsdim-1.8.9-4.22beta27.jar) 
    UCHIJAAAA   worldedit{6.1.1} [WorldEdit](worldedit-forge-mc1.8.9-6.1.1.jar) 
    Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.8.9-0.3.0.10-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
LoadingPlugin (RandomThings-MC1.8.9-3.6.5.jar)
  lumien.randomthings.asm.ClassTransformer
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.2.jar)

```
GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276' Renderer: 'Intel(R) HD Graphics'
Pulsar/tconstruct loaded Pulses: 
    - TinkerCommons (Enabled/Forced)
    - TinkerWorld (Enabled/Not Forced)
    - TinkerTools (Enabled/Not Forced)
    - TinkerSmeltery (Enabled/Not Forced)
    - TinkerGadgets (Enabled/Not Forced)
    - TinkerOredict (Enabled/Forced)
    - TinkerIntegration (Enabled/Forced)
    - TinkerFluids (Enabled/Forced)
    - TinkerMaterials (Enabled/Forced)
    - chiselsandbitsIntegration (Enabled/Not Forced)
    - TinkerDebug (Enabled/Not Forced)

EnderIO: No known problems detected.
Launched Version: 1.8.9-forge1.8.9-11.15.1.1761
LWJGL: 2.9.4
OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4276, Intel
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 1.12 combined resource pack.zip
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 2x Intel(R) Pentium(R) CPU 2127U @ 1.90GHz
```

**Comment by lehjr** [comment]
Does it happen every time or is it more random?

**Comment by reinder-s** [comment]
every time

**Comment by lehjr** [comment]
I have a pretty good idea what is causing this. Should have it fixed later today.

**Comment by reinder-s** [comment]
Thanks
Btw it also happen with jet boots
And the gliders also crash me as soon as i aply them

**Comment by reinder-s** [comment]
Oh and the railgun
If you need the reports il crash myself for them

**Comment by reinder-s** [comment]
Oh and the railgun
If you need the reports il crash myself for them

**Comment by lehjr** [comment]
The railgun problem is caused by the same thing. I'm working on it now.

**Comment by reinder-s** [comment]
Ah ok
Good luck hope its easy to fix

**Comment by lehjr** [comment]
Testing a new build now. If it goes well, I'll upload it within the next hour.

**Comment by lehjr** [comment]
A new version has been uploaded, may take a little while before it becomes visible.
