### ISSUE TITLE
[Suggestion] Command to give Power Armor + Upgrades

### ISSUE THREAD

**Issue by Brend-Smits** [MachineMuse/MachineMusePowersuits#713]
Heey!
Thank you for creating this awesome mod.
I was wondering if it would be possible to implement a command where you can give players pieces of the Power Armor with upgrades inside of it?
I would love to give them away in my crates as some form of jackpot.

Please tell me what you think about this!

**Comment by flowtender** [comment]
You can already do this by assigning the NBT data of the items using the existing minecraft command.

**Comment by flowtender** [comment]
If you want to see what the nbt tags look like, just make the armor you want the normal way, and then save and exit and open your player.dat in an nbt viewer.
