### ISSUE TITLE
Giving lehjr push access to the repo

### ISSUE THREAD

**Issue by flowtender** [MachineMuse/MachineMusePowersuits#718]
I should have done this a while ago but here you go.

**Comment by lehjr** [comment]
:O

**Comment by lehjr** [comment]
I'll be using this repo for 1.9.4 and up. Still need access for Numina repo though. Once I get 1.9.4 running I might backport some fixes to the 1.8.9 branch and clean that up and put that here as well. In it's current state it's too much of a mess.

**Comment by Lordmau5** [comment]
First off: Congrats! :)

Second off: I _(personally)_ would just focus on 1.9.4 and leave 1.8.9 behind.
There's no real need to continue with work on 1.8.9 anymore - the jump to 1.9.4 is not that big (item changes, yay, enjoy backporting **FROM** json.) :P

**Comment by lehjr** [comment]
Well, the biggest things to fix would be the model for the power fist since converting from modelbase rendering (thanks to removal of IItemRenderer) to an actual model butchered it pretty bad.

**Comment by flowtender** [comment]
oh yeah lol ok there you go

**Comment by lehjr** [comment]
@MachineMuse Thanks! :D

**Comment by EzerArch** [comment]
I believe this feature is already implemented. ;)
