### ISSUE TITLE
Omniwrench module still has some Cofh dependency, may crash on use.

### ISSUE THREAD

**Issue by EzerArch** [MachineMuse/MachineMusePowersuits#720]
I tried to use the omniwrench on a stair, I wasn't expecting it would work. But it crashed because it seems this module still has some dependency on/to Cofh lib:

```
java.lang.NoClassDefFoundError: cofh/lib/util/helpers/ServerHelper
```

https://gist.github.com/EzerArch/89f7fdc5c8dca045143368cffcac0d9f

Using ModularPowersuits-0.11.0.300 or Forge 1614. MC 1.7.10.

Also reported here: https://github.com/aidancbrady/Mekanism/issues/3246

**Comment by lehjr** [comment]
I'll try and get this fixed this week. This will probably be the last of anything for 1.7.10 though as we don't have the manpower to work on multiple versions of the mod.

**Comment by lehjr** [comment]
the fix will be to enable the OmniWrench module only if CoFH lib/core is installed. Since the Jenkins build server has apparently been down for over a month, I'll be uploading a new version later today.

**Comment by lehjr** [comment]
MPS for 1.10.2 has no Omniwrench module. That will probably come back in 1.11.2. We can revisit this issue when that times comes, but it will likely be using different code anyway. 1.7.10 support has ended.
