### ISSUE TITLE
Solar Panels, Computer Chip, Artificial Muscles not craftable

### ISSUE THREAD

**Issue by CreepyLPYT** [MachineMuse/MachineMusePowersuits#722]
Hey! I can't see any crafting recipes for the items in the Title, so I can't craft it!
Is there a reason why?

**Comment by lehjr** [comment]
What version?

**Comment by CreepyLPYT** [comment]
The newest. But I found the problem. I had to start the Mod in the normal minecraft launcher instead of the Technic Launcher so that the Vanilla recipes were created. In the Modpack I used in Technic Launcher I couldn't craft some items because there was no support for the technic mods I used, that means the items were only craftable with the vanilla recipes.

**Comment by flowtender** [comment]
"Newest" is not a version number~
