### ISSUE TITLE
[Suggestion] Bring back the 1.4.7 armor models as a module and allow power tool coloring!

### ISSUE THREAD

**Issue by seijinshu** [MachineMuse/MachineMusePowersuits#723]
We should return the 1.4.7 armor as a module, or as a cosmetic option in 1.7.10+ versions.
We can color the armor like how it was done in 1.4.7 with color sliders like how the lux capacitors are, and citizen joe armor as either a slider (0/1 toggle) or separate module requiring the original model module.
We also should be able to color the power tool again and make the blue crystal on it colorable as a second module slider option, or enable it in the cosmetic menu.

**Comment by lehjr** [comment]
keep in mind that after 1.7.10 the rendering changes are such that many things are no longer possible or not easily implemented, especially with IItemRenderer removed and a completely different model system. And the more complex you make something, the harder it will be to port to the next version of Minecraft when the next round of changes comes and bites you.

**Comment by seijinshu** [comment]
Yeah, but in the 1.8 port, you already implement the old 1.4.7 model.

**Comment by lehjr** [comment]
the 1.8.9 port is using the vanilla armor model, but it's not by choice. And right now, cosmetics are the lowest priority. Doesn't matter how amazing or ugly the armor looks if things don't work right.

**Comment by lehjr** [comment]
Armor model by module is actually a thing now (but a work in progress). Power Fist coloring will come probably later.

**Comment by lehjr** [comment]
power fist and skinned armor coloring by tint module will be in mps alpha 1.10.2 alpha 11. Armor model switching is almost complete, just need to add some tweaks in the GUI
