### ISSUE TITLE
Massive power drain on chunk generation lag

### ISSUE THREAD

**Issue by leagris** [MachineMuse/MachineMusePowersuits#730]
Still getting issue of #510 
Getting this bug in 1.7.10, forge build 1614, ModularPowersuits-0.11.0.301.jar

**Comment by lehjr** [comment]
We don't need to open issues for the same bug

**Comment by leagris** [comment]
Then please re-open #510 
https://github.com/MachineMuse/MachineMusePowersuits/issues/510
