### ISSUE TITLE
Per-armor-piece meters and drop-down module list are gone

### ISSUE THREAD

**Issue by EzerArch** [MachineMuse/MachineMusePowersuits#735]
Firstly, my kudos to you @lehjr for the major overhaul and clean-up of the mod. The mod is 300KB smaller! Did you feed it lettuce and vegetables or what...? ^^'

But there's something I'm missing.

This is ModularPowersuits-0.11.0.301:
![2016-11-24_01 40 04](https://cloud.githubusercontent.com/assets/6743303/20586265/8eee2db8-b1e9-11e6-9a67-6b54aa84ad1a.png)
And if I press Shift:
![2016-11-24_01 40 15](https://cloud.githubusercontent.com/assets/6743303/20586264/8eedb482-b1e9-11e6-80e0-abc7001b70a0.png)

This is ModularPowersuits-0.11.1.101 (Please ignore the status effect badges):
![2016-11-24_01 55 14](https://cloud.githubusercontent.com/assets/6743303/20586271/aad905d4-b1e9-11e6-9830-fc7f85d99172.png)
And if I press Shift, nothing happens.

Is it intended?

**Comment by lehjr** [comment]
Thanks. I didn't even notice that. I'll look into it this weekend.

**Comment by lehjr** [comment]
Fix should be up in a few minutes.

**Comment by EzerArch** [comment]
Confirmed. It's fixed.
