### ISSUE TITLE
Not working speed asist module

### ISSUE THREAD

**Issue by Rumcajz23th** [MachineMuse/MachineMusePowersuits#739]
i nodest that speed asist module doesn't work i tried create a key bynding and set properites to maximum in that module... nothing help i even try to create special minecraft modpack with only NEI, Thermal Expansion mod set and MPS to test it and still don't work. So it is propably problem in MPS. Do you please look at it? Thx for information. 
With regards

Rumcajz

**Comment by lehjr** [comment]
I found the issue. Fixed version should be out in a few hours.

**Comment by Rumcajz23th** [comment]
wow. that is fast. thank you. :)

**Comment by audiogarden21** [comment]
Sprint Assist is still having issues in version "ModularPowersuits-0.11.1.106-Java-Port". It works fine when you first add the module but when you log out to the main menu and then back into the same world, none of the slider settings work anymore (they move but have no effect), the sprint function stops working entirely, and the walk assist stays at whatever percentage you had it set to before you logged out. Keybinds for SA also fail to work.

**Comment by lehjr** [comment]
OK, so more of this then: https://github.com/MachineMuse/MachineMusePowersuits/issues/738

This might be the missing peice of the puzzle I need to solve it, thanks. 
> but when you log out to the main menu and then back into the same world, none of the slider settings work anymore...

**Comment by audiogarden21** [comment]
I just had a look at that issue and it sounds pretty similar. I haven't had any issues with other settings as I have with Sprint Assist, however I also haven't fully tested the other features since I'm playing in an SSP world atm.

If you would like me to check the other features I'd be more than happy to help.

For the record, I've been using the latest version of Numina as well, version "Numina-0.4.1.103.jar".

**Comment by lehjr** [comment]
I'd be happy to have some testing done, but there will be a new version up on Curseforge soon (currently under review), so you might want to wait until that shows up.

**Comment by audiogarden21** [comment]
All right. As soon as it's available I'll get right on it.

**Comment by lehjr** [comment]
Thanks!

**Comment by audiogarden21** [comment]
Well .107 seems to have fixed my issue as I couldn't replicate it with that version. Here shortly I'll go into a creative world to test the rest of the features to make sure they're functioning properly as well.

**Comment by lehjr** [comment]
Thanks. Looks like this issue here https://github.com/MachineMuse/MachineMusePowersuits/issues/738 is going to take some time to track down. I suspect it's a network/packet issue, but beyond that, not yet sure.

**Comment by audiogarden21** [comment]
After extensive testing I didn't run into any issues that are addressed in this ticket, however I discovered a few issues unrelated, so I will post a new issue to cover them in a sort of compiled list, if you don't mind.
