### ISSUE TITLE
Crash on viewing model in tinker table and equipping power armor.

### ISSUE THREAD

**Issue by m0nkm0nk** [MachineMuse/MachineMusePowersuits#740]
Both resulting in:
java.lang.NoClassDefFoundError: net/smart/render/ModelRotationRenderer
Not sure whats causing it.

Full crashlog:
http://pastebin.com/9QPkXHdQ

**Comment by lehjr** [comment]
This is from using RenderPlayerAPI without SmartRenderer. Fix should be up soon.

**Comment by m0nkm0nk** [comment]
Tried with SmartRenderer but keeps asking for playerapi version 1.3 ^^ Thanks for your quick respond i'll await your fix. Thanks!

**Comment by lehjr** [comment]
What version of SmartRenderer? The version I'm using is 1.7.10-2.1

**Comment by m0nkm0nk** [comment]
Same as I used.

**Comment by m0nkm0nk** [comment]
Well just tested with PlayerApi 1.3 and SmartRenderer 1.7.10-2.1. That does work. However I cant remember using SmartREnderer with ModularPowersuits-0.11.0.301 and PlayerAPI-1.7.10-1.3. Problems started to happen when I updated to latest MP and Numina.

**Comment by lehjr** [comment]
After 0.11.0.301, I ported the mod from Scala to pure Java, changing about 70 percent of the code from Scala code to java equivalents. So there will be a few bugs, but most are easier to fix when the code is easier to read and understand.

**Comment by m0nkm0nk** [comment]
So for now I should use PlayerAPI-1.7.10-1.3 with SmarRenderer 1.7.10-2.1 until you fix it at your side?

**Comment by lehjr** [comment]
There will be a new version up on Curseforge soon (currently under review). It shouldn't be too long.

**Comment by m0nkm0nk** [comment]
Ok nice, thanks for your effort!

**Comment by m0nkm0nk** [comment]
Issue solved on 0.11.1.107. You can close this one. Again thanks.
