### ISSUE TITLE
[1.7.10] Jetpack offers no thrust no matter the config

### ISSUE THREAD

**Issue by ranger135xp** [MachineMuse/MachineMusePowersuits#745]
Hello,

I am having an issue where in single player I can fly around and the jetpack actually shows power consumption and thrust ratings when sliding the slider. When on my own server that has a matching config, it does not display anything and I cannot fly. I'm using version 0.11.1.107.

**Comment by lehjr** [comment]
Numina version?

**Comment by ranger135xp** [comment]
0.4.1.103. I did just see that there's a new version of powersuits and Numina and I'm going to try those later tonight to see if it has been resolved. From some reason, I started updating my personal modpack back on the 18th but CurseForge did not have powersuits 0.11.1.108 or Numina 0.4.1.104 on display. I'll also give you screens as it was 3AM when I posted.

**Comment by lehjr** [comment]
I didn't mark the latest versions as releases until  a day or so ago mainly because I had made a few internal changes and was waiting on feedback before marking them as done. 0.11.1.107 and 0.4.1.103 had some issues with dedicated servers which should be fixed. 1.7.10 development is done at this point. Bug fixes may still happen, but at this point I have to focus on future versions or get left behind.

**Comment by ranger135xp** [comment]
Yeah, I'm not trying to get you to support 1.7.10 for eternity. As long as I can do the basics and keep everything where it is such as AE2 and a whole lot of others then I'm done updating my 1.7.10. This was the final onslaught as EnderIO had a render glitch among a host of other various mod issues. The problem became that when you update one, you mostly have to do them all or something crashes due to API changes. I had the QMX version for a while because AE2 rv2 beta 10 did not work with the one I had before that.

From what I can see so far, if I can fly, I'll be good lol. I do appreciate your time on this. Once I get back from family stuff I'll try the newest version and detail my findings. :)

**Comment by ranger135xp** [comment]
I put the latest release in and all is well. Thank you! Merry Christmas and happy new year!
