### ISSUE TITLE
Key_Cycle Tool Backward can crash the game

### ISSUE THREAD

**Issue by EzerArch** [MachineMuse/MachineMusePowersuits#746]
Since I use MPS a lot in space, which means I can't use Shift+Cycle Tool (because there's no floor), I had to assign `key_Cycle Tool Backward (MPS)` and `key_Cycle Tool Forward (MPS)` to NumPad3 (81) and NumPad1 (79) in the game options to be able to select the tools for the Power Fist.

**The intended behavior:** if the Power Fist is selected in the hotbar, pressing NumPad3 or NumPad1 would cycle the Power Fist's tools. If not, pressing NumPad3 or NumPad1 would do nothing.

**The crash:** if the Power Fist is **not** selected in the hotbar, pressing NumPad3 crashes the game (crash below); funnily pressing NumPad1 would do nothing.

I'm using ModularPowersuits-0.11.1.108 and Numina-0.4.1.104, for MC 1.7.10.

https://gist.github.com/EzerArch/bc239d4887a40d920bd16d7153387330

**Comment by lehjr** [comment]
Looks like I missed a null check. I'll upload a new build in a few minutes.

**Comment by lehjr** [comment]
New build uploaded, should be available soon.

**Comment by EzerArch** [comment]
_(Shhhh.... I'm closing it. :x)_
