### ISSUE TITLE
[Java port] Wireless Terminal no longer works

### ISSUE THREAD

**Issue by Stalkstalks** [MachineMuse/MachineMusePowersuits#750]
The AE wireless terminal part on power fists no longer seems to work, instead always reporting insufficient power - the fist itself has a maximum size battery, and my inventory has other charged items, all fully charged.

This happens even after re-pairing the fist to the network and while standing right next to the wireless transmitter. Other wireless terminals work.

**Comment by lehjr** [comment]
What version of AE2 are you using?

**Comment by Stalkstalks** [comment]
Revision 3 beta 6.

**Comment by lehjr** [comment]
1.7.10 support has ended, sorry.
