### ISSUE TITLE
Sprint Assist and Walking Assist cause the powersuits to drain power when going through Mekanism/IC2 Teleporters (1.7.10) (1.10.2)

### ISSUE THREAD

**Issue by dro800** [MachineMuse/MachineMusePowersuits#751]
As the title says, when walking assist is enabled on the Powersuit Leggings, the armor will lose power when taking Mekanism Teleporters. I am running a custom modpack in Minecraft 1.7.10 on Forge 10.13.4.1614 with Modular Powersuits 0.11.1.111 and Numina 0.4.1.105, as well as Mekanism 9.1.0.281 along with a bunch of other mods installed. If more information is required, or if you would like to see a screenshot, I would be happy to include it. Unfortunately it's kind of hard to recreate this issue since it seems to happen randomly but it appears to happen more often if another player sets up 2 teleporters and then you take the teleporters when you have the Powersuit Leggings with walking assist equipped. You can try recreating this bug by placing down two Mekanism teleporters, linking them to each other, and then installing the speed assist module for the Powersuit leggings, and then increasing the walking assist, then you can walk through it. I hope this information will help and I might also send this issue report in the Mekanism GitHub as well. Thanks in advance.

EDIT: After some more testing, I discovered that this bug not only happens when walking assist is enabled, but also if sprint assist is enabled and you sprint at the teleporter. This leads me to believe that speed effects is causing this issue. Again, if more information is required, I wouldn't mind giving more information and sharing some screenshots. Thanks again in advance.

**Comment by Kemorno** [comment]
happens to with the IC2 teleporter too, i realised that the energy loss is linked with the distance, cause in my test world, i was about 400 block away and i lost about 0.1M EU, and in my normal world (survival) my other teleporter was up to 8000 block and i was losing up to 1.5M EU. that is also when i'm running, if i'm walking it doesnt lose energy

**Comment by lehjr** [comment]
If this issue is present in 1.10.2 it will be addressed there.
Unfortunately I have to completely discontinue 1.7.10 support in order to
work on future versions.

**Comment by dro800** [comment]
@lehjr Just tested this out in 1.10.2 using Modular Powersuits 0.12.2-008 and I can confirm that the issue still exists. I had Forge Mod loader 8.3.2185 and Mekanism 1.10.2-9.2.2.301 and tried going through the teleporter again with sprint assist on the power leggings and it still drains power.

**Comment by dro800** [comment]
@Kemorno Did you have walking assist enabled when you walk on the IC2 Teleporter?

**Comment by Kemorno** [comment]
indeed, and step assistant too, but never tried to walk into it without the step assistant neither without the sprint assistant (it as a block higher than the ground (test world))

so heres what probably happens, since you are walking fast, and wasting energy, to prevent cheating, or errors in code, machinemuse made it that if you teleport (cause of lag or similar) it would count the initial coordinates and the end coordinates, and would calculate the amount of energy spent, and then remove that energy from your suit, but it doesnt take in considerations teleporters... so the further you go, more energy you will spend... its a smar move from machinemuse to prevent "cheating" but it has flaws

**Comment by eyeonus** [comment]
Assuming you're correct, and I bet you are, putting in an upper bound, like, say 250 blocks, would help.

**Comment by lehjr** [comment]
This is on the radar, but everything is on hold until I fix the model loading for the armor. It's not a minor task by any means but is an absolute must before the mod can reach beta.

**Comment by Kemorno** [comment]
thanks man.

**Comment by lehjr** [comment]
I normally use Mechanism for power to charge the suit and the teleporters to expand my exploration capabilities so yeah, it won't be something that falls though the cracks.

**Comment by lehjr** [comment]
Was kind of able to replicate this, but it seems to stop draining at 400K. This will probably get fixed in the last alpha before the first beta release. The fact that I can replicate this on some level should make things easier.

**Comment by lehjr** [comment]
Is this still an issue in the Beta?

**Comment by eyeonus** [comment]
This appears to have been fixed. Tested by taking an IC2 teleporter from -237 69 232 to 1015 64 975 and back, which is a pretty decent distance, and also by taking a Mekanism teleporter to and from the Nether.

Neither showed any noticeable drop in power, even after multiple contiguous transfers.

I think you can safely mark this one fixed.

**Comment by lehjr** [comment]
Calculation is done by steps now rather than distance, making it a simpler, and more realistic calculation. I just needed to make sure it was working.
