### ISSUE TITLE
Older Versions unavailable

### ISSUE THREAD

**Issue by SpektorRED** [MachineMuse/MachineMusePowersuits#752]
With the build server down, any chance you could upload the older versions to curseforge?

**Comment by lehjr** [comment]
If @MachineMuse has them it would be possible, otherwise probably not. That said, old versions won't be supported and 1.7.10 support will be ending soon.

**Comment by EzerArch** [comment]
Which versions are you looking for? I have:
ModularPowersuits-1.5.2-0.7.1-635
ModularPowersuits-1.6.2-0.8.0-24
ModularPowersuits-1.6.4-0.10.0-91
ModularPowersuits-1.6.4-0.10.0-118
(in fact, I have hundreds of jar files. Those are sort of the milestones)
