### ISSUE TITLE
1.7.10 No Recipes

### ISSUE THREAD

**Issue by Aperturelab1** [MachineMuse/MachineMusePowersuits#754]
Hi Guys.

I'm having an issue with my MPS. No matter what Ive tried, i cannot get an recipes to work. Mps V- 0.11.1.111, coinciding with Numina V- 0.4.1.105 with FML V- 10.13.4.1558.  Ive tried downgrading MPS to keep numina above date in comparison, Ive isolated these two mods, Ive cleared my config of everything for every mod to have a fresh config, Ive tried editing the recipes in the config as well as within the mod itself. tried copying the recipes in the mod directly to the config. I think there's was something else Ive tried but i cant recall what that was. Any help you guys can give would be a tremendous help, Thank you.

~Devin

**Comment by lehjr** [comment]
And what version of Not Enough Items are you using?

**Comment by Aperturelab1** [comment]
I Typically use Too Many Items, but Ive left it uninstalled for testing of MPS.  I cant find the specific version of TMI; Only that the download calls it 2017-07-15-1.7.10. For item recipe info, i use Crafting Guide, though ill admit i havent updated it in some time. this as well has been left out of the mods folder. only Numina, MPS, CoFHCore and Industrial Craft. Hell, i even did it without industrial and cofh. Oh. i remembered what else i tried. I made an entirely new forge launch option with fresh JVM arguments so there wouldnt be any Incompatibility with the loading process.

**Comment by lehjr** [comment]
The recipe handler for MPS uses Not Enough Items.

**Comment by lehjr** [comment]
It may or may not work without it. I really don't know. However, given that the first MPS alpha for MC 1.10.2 is only a couple days away, it's safe to assume that anything for 1.7.10 that requires any major work just won't happen. I'd love to be able to support multiple versions, but there just isn't enough of me to go around in order to do so.

**Comment by Aperturelab1** [comment]
Deffinatly, thats more than fair enough. Work on the future, not the past. I just want to know if im doing anything wrong since its worked for other people in 1.7.10. if the recipes are integrated into the game through NEI, ill deffinatly try that combo. Thank you!

**Comment by Aperturelab1** [comment]
wow, that...worked. NEI is the monopoly middle man. Interesting. Thank you so much~

**Comment by lehjr** [comment]
yeah, the plugin was created back before I became involved with MPS. If 1.7.10 had more life in it I'd probably try writing an alternative, but we're already looking at 1.11 mods.

**Comment by Aperturelab1** [comment]
Dont worry yourself about it. 1.7.10 is so out of date. people like me should know theres a risk with being this far back
