### ISSUE TITLE
crash on 1.10.2 version

### ISSUE THREAD

**Issue by 0Navis0** [MachineMuse/MachineMusePowersuits#757]
I get this crash with the 1.10.2 ModularPowersuit version. http://pastebin.com/X8WTNavA

**Comment by eyeonus** [comment]
That's from having the old version of Numina installed, which will happen if you installed using Curse. Just delete the numina jar, the correct version of numina is included in the powersuits jar file.

**Comment by 0Navis0** [comment]
I haven't any Numina jar which installed it, I just checked it now.

**Comment by eyeonus** [comment]
Hmm. That fixed the problem for me. You're using the Alpha 001 version, right?

**Comment by 0Navis0** [comment]
Hm it seems to work now with the Alpha 002.

**Comment by eyeonus** [comment]
This crash occurred when installing the basic solar generator. energy armor installed in all pieces, hv cap in chest, fully charge cap at time of installing.

Forced a disconnect, neither server nor client forcequit.

Same error on login attempt. Still occurs on restart.

[latest.log.txt](https://github.com/MachineMuse/MachineMusePowersuits/files/836948/latest.log.txt)
(EDIT: ALPHA002)

**Comment by lehjr** [comment]
Yeah, that's a client side only method being called on both the client and server. I'd better see how many other places that's being used and just replace every usage of it. New build should be up in an hour

**Comment by lehjr** [comment]
I replaced every instance of that method, even in places where it shouldn't fail, just to get in the habit of not using it.

**Comment by eyeonus** [comment]
Found another one in alpha 3:
[latest.log.txt](https://github.com/MachineMuse/MachineMusePowersuits/files/839756/latest.log.txt)

**Comment by lehjr** [comment]
Another odd client side only method -_-

**Comment by lehjr** [comment]
in EntityItem
```
    @SideOnly(Side.CLIENT)
    public int getAge()
    {
        return this.age;
    }
```

**Comment by lehjr** [comment]
I think I have a fix, needs more testing though

**Comment by lehjr** [comment]
OK, alpha 4 is uploaded... should be "approved" in a few minutes

**Comment by eyeonus** [comment]
No crashes yet, but the Jump Boost isn't working and what happened to the Step Assist?

**Comment by lehjr** [comment]
Step assist was removed because it was obsoleted when you can walk up blocks in vanilla

**Comment by eyeonus** [comment]
Please re-add it. Vanilla step assist is awful. It's literally just auto-jumping for you and in my opinion is better left off, especially if your jump height has been increased. Ugh.

Regarding jump-boost: I have all the settings for it maxed. Normal jump height.

**Comment by lehjr** [comment]
Pretty sure I found the issue with the jump assist. The step assist will needs some testing. As I recall it was a bit flaky with the vanilla step assist. Maybe the vanilla step assist thing could be automatically disabled if the mps step assist is enabled. I do agree though, that vanilla thing is pretty bad. I only recently had a chance to play, since most of my free time was going into porting the mod.

**Comment by lehjr** [comment]
next build should be available in the next few minutes. It's great to be getting some feedback. At this rate the beta builds won't be far off.
