### ISSUE TITLE
[Suggestion] Ender IO Recipes

### ISSUE THREAD

**Issue by Zaikyu** [MachineMuse/MachineMusePowersuits#760]
It would be nice to see Ender IO Recipes since it is now a very popular Tech mod that is well established in 1.10.2

Even Immersive Engineering Recipes would be nice.

Forgive me if this is already put in since I haven't installed yet but going by the Curse page these do not exist.

**Comment by lehjr** [comment]
EnderIO recipes are already included and enabled when EnderIO is installed. -_-

Edit: The curse page is outdated. The EnderIO recipes have been included for about 2 years now, maybe more. Downloading the recipes is pointless, as they have been included for even longer.

**Comment by Zaikyu** [comment]
Alrighty Thanks! Maybe we need to have to have an update on the page then haha.

**Comment by lehjr** [comment]
Time I spend updating the page and screwing it up is time I could spend on updating the mod and fixing things. Development is powered by a team of 1.
