### ISSUE TITLE
Head module related crash, alpha 007

### ISSUE THREAD

**Issue by eyeonus** [MachineMuse/MachineMusePowersuits#763]
This might be related to the thing you mentioned in the changelog for this version, but since it's the head not the legs, I'm not sure.
[crash-2017-03-19_13.31.17-server.txt](https://github.com/MachineMuse/MachineMusePowersuits/files/853486/crash-2017-03-19_13.31.17-server.txt)

**Comment by lehjr** [comment]
Thanks. I'll look into that.

**Comment by eyeonus** [comment]
Let me know if you need anything more.

If you need testing environment, I'm basically using v1.8 of FTB's direwolf20 pack.

**Comment by lehjr** [comment]
I should have a fixed version up in about an hour.

**Comment by eyeonus** [comment]
Cool beans.

**Comment by lehjr** [comment]
New build will be up tomorrow. Had some unforeseen circumstances. Went outside to do some yard work, ended up changing my garage door opener. Good times

**Comment by lehjr** [comment]
new build should be visible shortly.
