### ISSUE TITLE
Keybind menu weirdness.

### ISSUE THREAD

**Issue by eyeonus** [MachineMuse/MachineMusePowersuits#764]
https://youtu.be/xea8mZ8X-Jc
Everything gets duplicated each time the menu is opened.

**Comment by EzerArch** [comment]
Yikes, this sometimes happens with me too in 1.7.10 version. Check powersuits-keybinds.cfg, see if there are duplicates (keybind lines start with a number; the module ones start with the module's name). My guess is MPS is just adding new lines in the cfg instead of rewriting the existing keybind nodes.

My workaround is to keep a good backup (powersuits-keybinds.cfg_BKP) that I restore if the main one breaks, so I don't need to redo all the work again.

**Comment by eyeonus** [comment]
Yeah, the keybinds gui has always been a bit wonky.

Never like this for me before, though.

**Comment by lehjr** [comment]
0.o

**Comment by lehjr** [comment]
Unfortunately, the keybinding is a hack on top of a hack, a mixture of reflection and access transformers to manipulate something that was never meant to be touched that way.

**Comment by lehjr** [comment]
o.0 
```
76:155.0:52.0:false:false
Sprint Assist~143.0761389835984~62.66871775151722
77:224.5:47.5:false:false
Jump Assist~217.48522188765725~61.88029513030234
77:224.5:47.5:false:false
Jump Assist~217.48522188765725~61.88029513030234
76:155.0:52.0:false:false
Sprint Assist~143.0761389835984~62.66871775151722
76:155.0:52.0:false:false
Sprint Assist~143.0761389835984~62.66871775151722
77:224.5:47.5:false:false
Jump Assist~217.48522188765725~61.88029513030234
76:155.0:52.0:false:false
Sprint Assist~143.0761389835984~62.66871775151722
77:224.5:47.5:false:false
Jump Assist~217.48522188765725~61.88029513030234```

**Comment by lehjr** [comment]
found it. missing "!"
correct way (in the 1.7.10 port: add keybinding if keybinding does not already exist): 
https://github.com/MachineMuse/MachineMusePowersuits/blob/1.7.10-Java/src/main/java/net/machinemuse/powersuits/control/KeybindManager.java#L95

fail (add the keybinding only if it already exists, meaning double each time it reads): 
https://github.com/MachineMuse/MachineMusePowersuits/blob/1.10.2-Java/src/main/java/net/machinemuse/powersuits/control/KeybindManager.java#L97

**Comment by lehjr** [comment]
Should be fixed in the next build.

**Comment by EzerArch** [comment]
> Check powersuits-keybinds.cfg, see if there are duplicates. My guess is MPS is just adding new lines in the cfg instead of rewriting the existing keybind nodes. https://github.com/MachineMuse/MachineMusePowersuits/issues/764#issuecomment-287658699

> o.0 https://github.com/MachineMuse/MachineMusePowersuits/issues/764#issuecomment-288096654

BINGO!

**Comment by eyeonus** [comment]
Awesome. I'm going to sleep now, but I'll check it out tomorrow. Haven't found anything new yet. Keep up the good work, man! (Or woman, whatever.)
