### ISSUE TITLE
[1.7.10?] Bibliocraft Armor Stand Ccrash

### ISSUE THREAD

**Issue by Shahelion** [MachineMuse/MachineMusePowersuits#765]
Not sure what made it crash this time, as I know it's worked just fine before. Maybe the fact that I had just made the suit before trying to put it on the stand, and hadn't touched the visual configuration yet. I shift-clicked the boots into place from my inventory. Question mark because I am unsure of what other versions this may apply to, it might still be an issue. I know, I know, outdated version.

https://gist.github.com/Zsashas/b5a85836dbc5b8464024d111abfeaa9c

**Comment by lehjr** [comment]
Wow, that's a lot of log spam. This is probably something that is going to take more time to fix than I want to put into 1.7.10. Support for it will officially end next Friday, as it is becoming increasingly difficult to support 1 version of Minecraft, let alone multiple versions.

**Comment by Shahelion** [comment]
I honestly thought 1710 support had already been dropped lol.

**Comment by lehjr** [comment]
I've been supporting it as much as I can, but there's too much work to be done before i can reach a beta state for 1.10.2.

**Comment by Shahelion** [comment]
Hmm...looks like it's a bigger issue, as it happened when I tried to put on the boots. Freshly crafted boots, then applied the second-tier battery and that's it. I can't even wear it. No crash report this time, as I panic-closed the game to avoid needing to use a backup.

**Comment by lehjr** [comment]
Yeah, biggest issue is you're using outdated builds and reporting issues that may have already been fixed. :P

**Comment by Shahelion** [comment]
I am? I thought I had the latest versions for 1.7.10...

**Comment by lehjr** [comment]
no, you're using an alpha build from when I first ported the mod to Java.

**Comment by lehjr** [comment]
ModularPowersuits-0.11.1.100,  Numina-0.4.1.100 
The very first Java pure ports.

**Comment by lehjr** [comment]
a lot of stuff got fixed since then

**Comment by Shahelion** [comment]
Holy shit, didn't realize there were so many updates since then. My Curseforge notifications have kind of been flooded with other mod updates for 1.10...thank you.

**Comment by lehjr** [comment]
btw, this will be working in the next 1.10.2 alpha https://twitter.com/Lehjr1/status/852891529098219524
