### ISSUE TITLE
Game crashes immediately if I start it with mod -modular power armor but I am incapable of filing a proper bug report so I want you to guess where the problem occurs and what the problem is.

### ISSUE THREAD

**Issue by egirlcatnip** [MachineMuse/MachineMusePowersuits#766]
Mods list [I play modpack-https://www.technicpack.net/modpack/welcome-to-reality-v2.975834/mods]
CRASH REPORT:numna : any 

 Additional Pipes by tcooc
rv2-stable-10
 Applied Energistics 2 by AlgorithmX2, henceforth
1.7.1
 Archimedes' Ships by Balkondeur
1.14.3
 Balkon's WeaponMod by Balkon
1.11.2
 Biblio Craft by Nuchaz
0.4.3A
 Big Reactors by ErogenousBeef
7.1.20
 Buildcraft by buildcraftchildsplay, SirSengir, Kraphty
3.3.8.1
 Carpenter's Blocks by Mineshopper
1.3.4.16
 Chicken Chunks by Chicken Bones
1.0.7.47
 Code Chicken Core by Chicken Bones
3.1.4-329
 CoFHCore by Team CoFH
1.75
 Computer Craft by dantwohundred
1.0.1.46
 Defense Tech by aidancbrady
1.7.10
 Dimensional Anchors by immibis
1.7.10
 Dimensional Doors by StevenRS11
1.4.7.38
 Ender Storage by Chicken Bones
0.3.0.547
 Equivalent Exchange 3 by Pahimar
2.3.14b197
 Extra Cells 2 by DrummerMC
1.2.12
 Extra Utilities by RWTema
3.2rS
 Food Plus by JoseTheCrafter
wtr-v2-1
 Forge by Forge Development LLC
3.0.12.465
 Galacticraft by Micdoodle8
1.11.2
 Gregs Lighting by Gregory C. Ewing
4.2.3
 iChunUtil by iChun
1.7.10
 Immibis Core by Immibis
1
 In-Game Wiki by MineMaarten
2-2.2.823-experimental
 Industrial Craft 2 by The IC2 Dev Team (Player, ThunderDark, RichardG, GregoriusT, SirusKing)
1.59-dev-152
 Inventory Tweaks by Kobata
1.7.10
 Iron Chests by progwml6
0.9.3.128
 Logistics Pipes by RS485, davboecki, theZorro266
0.3.2b
 Mantle by progwml6, bonusboni, mDiyo, Arkan
9.1.0.281
 Mekanism by aidancbrady
1.7-3.0.12.465
 Micdoodle Core by Micdoodle8
2.8.1-174
 Mine Factory Reloaded by TeamCoFH, skyboy026
1.7-1.53
 Moar Peripherals by TheOriginalBIT
0.0.51b29-universal
 Modular Force Field Systems by Calclavia, poopsicle360, BuiltBrokenModding
0.9.3
 Morph by iChun
1.0.5.120-universal
 Not Enough Items by Chicken Bones
1.6.1.11-universal
 Open Computers by Kethtar
2.2.10-233
 Open Modular Turrets by Poenjabiesous, Keridos
1.7.5
 Openccsensors by Cloudhunter, Mikeemoo, Orwell1984, Lyqyd, Nietsnie
1.7.10_HD_U_D6
 OptiFine by sp614x
1.9.2
 PlanetguyLib by Planetguy
1.7.10-4.7.0pre12.95
 Project Red by Mr_TJP
1.2.2
 qCraft by qCraft Team
9.12.2.0
 Railcraft by CovertJaguar
1.7.10
 Reis Minimap by ReiFNSK
2.8.9
 Remain In Motion (Redstone in Motion) by Planetguy, DA3DSOUL
1.7.10
 Secret Rooms by AbrarSyed
1.8.2
 Security Craft by bl4ckscor3
2.0.0.b18
 Steves Carts by Vswe
1
 Thermal * by Team CoFH
1.8.8
 Tinkers Construct by mDiyo, boni, JadeCat, KnightMiner
4.3.1_007
 Traincraft by Mrbrutal, Spitfire4466
1.1.2.16-universal
 Translocator
translocator
 by Chicken Bones
2.0.4
 Treecapitator by bspkrs
59.0.3
 Tubestuff by Immibis
1.2.3
 Vending by AUTOMATIC_MAIDEN, kamildanak
0.28.2b356-dev-universal
 Voltz Engine by DarkCow
1.5.10
 Waila by ProfMobius
0.24.1
 Witchery by Emoniph
1.4.1.9-universal
 Wireless Redstone Chicken Bones Edition by Chicken Bones
2
 WTR Framework by Recast Productions

**Comment by lehjr** [comment]
a crash log would help, , not to mention you don't even have Modular Powersuits in the list

**Comment by lehjr** [comment]
I'm not going to guess what the crash was or where it was happening.
