### ISSUE TITLE
F1 key shrinks MPS UI instead of hiding it

### ISSUE THREAD

**Issue by EzerArch** [MachineMuse/MachineMusePowersuits#769]
![2017-03-26_14 08 44](https://cloud.githubusercontent.com/assets/6743303/24336428/89e4ca5c-1265-11e7-8ab9-4696c8f7be88.png)
Can you spot the MPS icons on the upper-left corner?

**Comment by lehjr** [comment]
wow. That's unusual.

**Comment by lehjr** [comment]
should be fixed in the next 1.10.2 alpha

**Comment by lehjr** [comment]
This is fixed in alpha 10.
