### ISSUE TITLE
[1.10.2] Model loading

### ISSUE THREAD

**Issue by lehjr** [MachineMuse/MachineMusePowersuits#771]
Currently this is top priority, so much so that I'm giving this a separate issue. To elaborate, the current code uses "dummy items" to load the armor models using the built in JSON loading system. While it does work well, it creates completely useless items. Once it is fixed, these items will be removed. But removing items causes issues, even if no player has them. 

The model loading system is written around using static models, because in most cases this will suffice.  Using the JSON method of model registration means that not only are the models correctly loaded for you, but the textures are registered properly as well, which means when the models are "baked" the texture mapping (UV mapping) is saved in the "baked" model. However, the magic of the model loading system is what it does, but rather how it does it....

**Comment by lehjr** [comment]
I think I may have solved this. The JSON loading system has integrated texture registering and the models are baked around this setup. The thing is, the OBJ loader has an internal cache, so loading the OBJ models before the textures are registered produces models with invalid mapping. This means that the models need to be both loaded and baked after the textures are registered, so you cannot load the models to get the texture data to register the textures, then bake them after. Luckily, the XML reader for the mod already reads the XML files for textures, so it's just a matter of altering the code a little to make it a 2 step process.

**Comment by lehjr** [comment]
I'm gonna spend a little more time on this and streamline the process a bit.

**Comment by lehjr** [comment]
So I wrote a new OBJLoader for MPS that adds the ability to load the models without caching, this way the model can be loaded to get the textures to register without caching a broken copy. Works great from what I can tell and solves a major problem I was having. Now to clean it up and start working on the rendering issues.

**Comment by Bluexin** [comment]
Did you check performances difference? Both memory footprint, cpu/cpu usage etc.
(not sure it's in a state where it can be tested yet, but that's something to watch closely when changing caching systems xD learnt it the hard way)

**Comment by lehjr** [comment]
There really isn't any easy way to tell the difference, since the number of OBJModels is less than 10. However, it only loads twice vs Forge's internal setup, once to register the textures and without caching, once to load the valid models. Forge loads the models and gets the textures, then flushes and loads again. during which the modelBakeEvent is fired twice. I'm checking if the first event is disabled and only firing on the second event, after the textures are valid so that the texture mapping is valid for the models. If anything, it would be faster than what Forge uses.

**Comment by lehjr** [comment]
Also keep in mind that the OBJLoader cache isn't used for rendering, it's only used to store the models instead of loading from the disk. They still have to be baked. The problem is that if you use Forge's OBJLoader without going through the JSON loading system, you have to register your textures yourself and you have to do it without touching the OBJModels, so you can't register with OBJModel#getTextures() because otherwise you'll cach an invalid copy of the model, and there's no way to remove a single bad entry. That's why I copied the the OBJ loader and added functionality to deal with that.

**Comment by lehjr** [comment]
Finished
