### ISSUE TITLE
[Alpha 9] - Keybinds on HUD causes crosshair and experience level visual glitch.

### ISSUE THREAD

**Issue by eyeonus** [MachineMuse/MachineMusePowersuits#772]
Adding keybinds to the HUD causes the crosshair to glitch out, might be related to the black background thing. (#770)

Glitch:
![2017-03-30_02 11 45](https://cloud.githubusercontent.com/assets/1733600/24494262/e72c5f50-14ee-11e7-9a5c-42e67c9bc1ec.png)
No glitch:
![2017-03-30_02 14 37](https://cloud.githubusercontent.com/assets/1733600/24494263/e72d62ba-14ee-11e7-8c69-c8acb93b05c8.png)
[EDIT] Also see the experience glitches out the same way.

**Comment by eyeonus** [comment]
Unrelated, Mouse3 still doesn't get saved in the keybind between game loads.

**Comment by lehjr** [comment]
Yeah, once I get the model loading fixed, some of this stuff will go away. Some of it I think is the powerfist code, and that will be replaced with actual Wavefront models, so there won't be any messing with opengl calls there. I'd kinda like to replace the Tinker Table too, but I'm not good at modeling or graphics.

**Comment by eyeonus** [comment]
Blender could probably be used to convert the existing models, assuming they're supported or have a plugin.

**Comment by lehjr** [comment]
Blender cannot convert Model base models. I have a wavefront model for the Tinker Table, but it's a complete pain to get the transparencies working and the animation API is not well documented.

**Comment by EzerArch** [comment]
> Glitch:
*1st screen*

This may be also a problem on resource pack's end. Instead of using RGBA(0,0,0,0) for transparent pixels, some resource packs (including Minecraft) mistakenly use RGBA(255,255,255,0) -- visually both are the same for you, but not for the computer/software.

I didn't know the resource pack I maintain had the same issue, but [MPS sort of helped me find it out](https://youtu.be/sPs-9MO-s94?t=1m9s).

**Comment by lehjr** [comment]
Very interesting.

**Comment by lehjr** [comment]
The power fist I know for sure is glitched though. If you equip it your quick bar turns black. The Tinker Table may cause issues as well. Currently, I'm working on replacing the power fist models with the ones I made earlier on. The Tinker table is another story. I'm not sure what to do with that yet.

**Comment by eyeonus** [comment]
It's not showing up because it's not getting built when I tell it to run. So I need to know how to build it.

Not be told that that it's not showing up because I don't know how to make certain that source files in a project are "associated with the project".

You don't want to help me get this thing up and running so I can help out with this, then by all means do everything yourself.

Hopefully Google will be able to help me, but I haven't had any luck so far, what with the person most likely to know what's going on treating me like I'm an idiot instead of listening to what I'm saying.

**Comment by lehjr** [comment]
It's not being built because it's not set up properly. Like I said, I build the damned thing constantly, without any of the issues you are having. All I'm getting is grief and it's certainly not helping me get anything done. But you want to constantly argue the point that it's set up correctly. It builds when you run it, how on earth do you think it handles the changes you make in the source otherwise? Think about it.

**Comment by eyeonus** [comment]
No, it's not getting built. But since there's nothing wrong with Minecraft, it'll run anyway, just not with the mod that failed to compile.

https://pastebin.com/XSPHnwpm

**Comment by lehjr** [comment]
A properly set up project would not run if it fails to build.

**Comment by lehjr** [comment]
and that's kind of the point. When you make breaking changes, it should not run at all. When you make changes, those changes have to be accounted for. Otherwise there isn't much point in using an IDE. But Eclipse is kinda horrible anyway. I stopped using it several years ago.

**Comment by lehjr** [comment]
When you have a properly set up project and you run that project, it should build that project right there, then stop if there is a problem, or keep going if everything is fine. Having the IDE keep going means that either the project is not set up correctly or the IDE is broken. And honestly, either is plausible. I had nothing but problems with Eclipse, even when working on Android projects.

**Comment by eyeonus** [comment]
I haven't made any changes.

**Comment by eyeonus** [comment]
I have literally done exactly what you told me, and the best result I can get is that Minecraft will run whether or not the mod fails to build, but it will not build, and I have added all the jars it's asking for.

Gradle added most of them for me, actually.

**Comment by lehjr** [comment]
every single IDE will build and run the project, and stop on error if set up correctly. This includes, CodeBlocks, IntelliJ, Eric4/5 (Python), even IDE's from the 90's like Borland and things that no one remembers. They all had one thing in common. Build on run in order to include changes, then stop on error. This is basic IDE behavior from back in the early days of computing. 

But like I said, I do not use Eclipse, it's horrible and has not improved. I suggest trying intellij, it will give you far fewer headaches.

**Comment by lehjr** [comment]
Any time an IDE wants you to set up a directory as a workspace for all projects, that's a red flag for misery ahead. Microchip had an IDE like that. It was a pain to use.

**Comment by eyeonus** [comment]
The headache I have right now is that even though the forestry api is in the java build path, when I tell gradle to build, it gives me an error saying it doesn't exist.

I will see if IntelliJ works where eclipse does not.

**Comment by lehjr** [comment]
all mod files should be in ./libs, but if you add them after you set up the project, you will need to add them manually as libraries. You can also put files in a different folder if you want to do that manually all the time, like testing mod compatibility. As for how to add libraries to eclipse, I have no idea, but I suspect it involves a primitive hunting ritual and clay pots full of animal waste, and some kind of dance.

**Comment by eyeonus** [comment]
You right click the file, and select the "add to build path" option.

**Comment by eyeonus** [comment]
What's the $PWD in "./libs"?

**Comment by lehjr** [comment]
current working directory?

**Comment by eyeonus** [comment]
Is it the same folder src is in?

**Comment by lehjr** [comment]
should be

**Comment by eyeonus** [comment]
Yes. I wasn't sure about the p, haven't bashed in awhile.

**Comment by eyeonus** [comment]
I will see if renaming lib to libs will help.

**Comment by lehjr** [comment]
don't force it. Get a bigger hammer

**Comment by lehjr** [comment]
![screenshot from 2017-04-13 00-37-34](https://cloud.githubusercontent.com/assets/1084367/24990364/7cd452ea-1fe1-11e7-9509-1ecbd6ab5599.png)

**Comment by eyeonus** [comment]
Yup. That's where I currently have a folder called lib that contains the apis and jars.

**Comment by lehjr** [comment]
the default location is libs. That will get picked up when you set up the project, but after that, anything you add you still have to add manually in the IDE

**Comment by eyeonus** [comment]
IntelliJ has finished installing. I'm going to rename the folder to libs and start from scratch.

**Comment by eyeonus** [comment]
I can't figure out where a valid home is for JDK, so I'm done with IntelliJ.

Good news, however. Renaming lib to libs did the trick. Finally got it to compile.

So, now that I've got a working dev environment, I've finally made some progress. Got the glass flipped pretty easily, still need to flip the "fluid" and get the tanks positioned correctly.
![firsttest](https://cloud.githubusercontent.com/assets/1733600/25018108/75759ccc-2043-11e7-8ed6-9cbb89e06149.png)

Also, I'm thinking I should probably move my progress reports to a new issue, instead of continuing to misuse this one. I'll do that when I get home and get back to working on this.

**Comment by lehjr** [comment]
also have to get the "lightning" effect to go sideways

**Comment by eyeonus** [comment]
Actually, I'm pretty sure it already does that, you just can't tell from the screenshot....
[EDIT] No, it's vertical, but it does stay inside the correct tank and it moves side to side along most of the meter, so it is being contained correctly. I'll have to look at the lightning renderer method, after I get everything else flipped and repositioned.

No more progress until I get home from work, I'll make a new issue for further updates at that time.

Just so you know, all the problems I had setting this up: totally due to me not knowing how to gradle, none of my problems had anything to do with eclipse.

**Comment by lehjr** [comment]
Eclipse works well for some, it's just not for me. I find it un-intuitive (damned auto incorrect, counter intuitive is probably a better term ) .

**Comment by eyeonus** [comment]
Yeah, no worries. I originally went with eclipse because I know how to use it- first used it way back before IntelliJ even existed- or at least before I was aware of its existence.

I did eventually figure out what it meant by valid home for JDK, so I could probably switch to IntelliJ, but I don't see much point anymore, since it's working in eclipse now that I've sorted out the gradle problems- which I bet I probably would've had regardless of which IDE I was using.

**Comment by lehjr** [comment]
Use what works for you. Personally, I find Eclipse horrible just to set up a project anywhere outside the "workspace" directory. It does have some nice plugins. Intellij is much simpler and better laid out (mostly), although some settings seem to be buried under 7 layers of hell.

**Comment by eyeonus** [comment]
Yeah, eclipse has it's own set of problems. I've never had any difficulties working with a project from outside the workspace, but, then again, I have experience with eclipse so I know how to do that.

Regardless, the point is that I finally got the thing working, which is what really matters.
