### ISSUE TITLE
Error at login in latest version of 1.7.10

### ISSUE THREAD

**Issue by letzzar** [MachineMuse/MachineMusePowersuits#773]
https://pastebin.com/TrZPd2hv

**Comment by lehjr** [comment]
Need a complete log and I may not even get to addressing it as 1.7.10 support is officially done.

**Comment by Hypersonicx** [comment]
[](https://pastebin.com/embed_iframe/vQBrEQMu)

**Comment by Hypersonicx** [comment]
[https://pastebin.com/raw/vQBrEQMu](https://pastebin.com/raw/vQBrEQMu)

**Comment by lehjr** [comment]
not the full log either. i need a complete log, from load to crash before I even look at this

**Comment by Hypersonicx** [comment]
This is no crash report. Me and others can not join on the Server. They receive an error "Internel server error" The server get what i have posted before.
I updated your Mod from 11.1.111 to 11.1.113

Should i post a modlist?

**Comment by lehjr** [comment]
I need the complete log, from load to crash, which would have the mod list in it.

**Comment by lehjr** [comment]
nevermind, I did find the issue

**Comment by letzzar** [comment]
In effect the error is when connecting the user to the server disconnects it.

Before I had the version ModularPowersuits-0.11.1.111
Now ModularPowersuits-1.7.10-0.11.1.113-FINAL

Modpack: Universal: Interdimiensional Escape 1.7.10 (Curse)

Link to the complete log https://www.dropbox.com/s/zm4uwdogxn1lalk/fml-server-2.log?dl=0

**Comment by lehjr** [comment]
already found the issue, however, it will be some time before a fix is released since I'm in the middle of doing OS updates as I was not expecting to be doing any more 1.7.10 updates. ETA: 1 hour - 1 day

**Comment by letzzar** [comment]
thank you very much

**Comment by lehjr** [comment]
Fixed build should be up in a few minutes. Sorry for the delay. Had to do an OS reinstall and troubleshoot a couple vanilla bugs.
