### ISSUE TITLE
Client connection issue with magnet 

### ISSUE THREAD

**Issue by a-frenzy** [MachineMuse/MachineMusePowersuits#774]
Hope this isn't a duplicate, I have a user who switched to their power glove and has been unable to connect to the server with this error

https://gist.github.com/frenzye/66220dd65f30926c2c8232eb59d1d2a2

**Comment by lehjr** [comment]
Would really help to have an error log that has more information than just a few lines of the error, especially when I don't even know what version of the mod is being used.

**Comment by lehjr** [comment]
Also, the magnet module is in the chestplate, not the power fist.

**Comment by a-frenzy** [comment]
Yea, removing the chest plate from the inventory allowed him to connect. This error occurs without a crash log, here it is in it's entirety extracted from the server log https://gist.github.com/frenzye/25372091e256053f13d001bbb5c1641c

MC 1.10.2, MPS  0.12.2-003, Forge 12.18.3.2239

**Comment by lehjr** [comment]
MPS 0.12.2-003? Seriously? You do know there are 6 more alphas after that build, right? Always try the latest build before filing a bug report.

**Comment by a-frenzy** [comment]
confirmed resolved in .009, my mistake
