### ISSUE TITLE
[ALPHA 10] Numina listed as a required library on Curse but the changelog says it's no longer needed.

### ISSUE THREAD

**Issue by laserlemons** [MachineMuse/MachineMusePowersuits#775]
Title.

**Comment by lehjr** [comment]
because if you remove the dependency, it removes it for all versions, not just 1.10.2 alphas, but every 1.7.10 build.

**Comment by laserlemons** [comment]
Ah, I didn't know that. That sucks.

**Comment by Razorskills** [comment]
maybe you could make a fake 1.10 version that the launcher would install for 1.10 instead of using the 1.7.10 version and basically do nothing..? Temp fix..

**Comment by lehjr** [comment]
possible, but I don't know how the launcher even determines if there the version is valid or not. I don't think it would be as simple as providing an empty jar file.

**Comment by lehjr** [comment]
For now, I have removed the "dependency" link so that 1.10.2 builds don't have 1.7.10 builds of Numina downloaded. 1.7.10 users should know that they need numina by now.

**Comment by Razorskills** [comment]
lol *starts getting crash reports

**Comment by lehjr** [comment]
already been getting them: https://github.com/MachineMuse/Numina/issues/22
