### ISSUE TITLE
[1.7.10][Urgent]Keys unable to unbind

### ISSUE THREAD

**Issue by CKTheUltimate** [MachineMuse/MachineMusePowersuits#776]
I tried to unbind keys by throwing them to trash but it doesn't work and now I cannot use the mod anymore as some keys are broken...(I binded A and after I place it in trash,I still can't walk left)
I tried most 1.7.10 versions and this issue stays...

**Comment by lehjr** [comment]
no version info (MPS... Numina... Forge...), no screenshots, no diagnostic information, nothing to show the problem. My crystal ball that deals with 1.7.10 issues has been sent to storage and I'm not supporting 1.7.10 anymore, largely because of the vague reports like this.

**Comment by lehjr** [comment]
If I was supporting it, I would only be supporting the latest version, something to keep in mind.

**Comment by CKTheUltimate** [comment]
Nvm I will go give up the latest 1.7.10 versions and play 1.10.2
