### ISSUE TITLE
Cant compile project locally 

### ISSUE THREAD

**Issue by compilerqq** [MachineMuse/MachineMusePowersuits#778]
What libraries/dependencies does this project have that aren't in source control?

I tried building it locally from the gradle script but it blew up with errors about forestry, mekanism and other api's.

**Comment by lehjr** [comment]
If you find it asking for certain libraries, then supply them. Dependencies are subject to change without notice, so what compiles today may not compile tomorrow.

**Comment by lehjr** [comment]
this is my current list in /libs (note not all are needed, some are for one experiment or another)  :
- CodeChickenLib-1.10.2-2.5.7.241-deobf.jar
- CoFHCore-1.10.2-4.1.0.155-universal.jar
- CraftTweaker-1.10.2-3.0.20.jar
- EnderCore-1.10.2-0.4.1.65-beta.jar
- EnderIO-1.10.2-3.1.172.jar
- forestry_1.10.2-5.2.17.368-api.jar
- industrialcraft-2-2.6.188-ex110-api.jar
- itemtransformhelper-1.10.2b.jar
- MCMultiPart-2.0.0-universal.jar
- Mekanism-1.10.2-9.2.1.298.jar
- MekanismGenerators-1.10.2-9.2.1.298.jar
- MekanismTools-1.10.2-9.2.1.298.jar
- Tesla-1.10.2-1.2.1.50.jar
- ThermalExpansion-1.10.2-5.0.3.86-universal.jar
- ThermalFoundation-1.10.2-2.0.3.77-universal.jar

**Comment by lehjr** [comment]
The full IC2 jar can be used, but it often crashes (probably 1 out of every 8 times),  even with CraftTweaker removed. Forestry also has issues.

**Comment by eyeonus** [comment]
Okay, how do I run this thing? For some reason powersuits doesn't show up at all in the mod list.
![whereismysupersuit](https://cloud.githubusercontent.com/assets/1733600/24987941/eaa204ce-1fbf-11e7-91d3-e8db8bae6d5a.png)
![no mmps](https://cloud.githubusercontent.com/assets/1733600/24987983/2b70085c-1fc0-11e7-9b83-cb81228e7f35.png)

**Comment by lehjr** [comment]
How exactly did you set it up in the first place?

**Comment by lehjr** [comment]
To set it up, use
```
gradlew setupDecompWorkspace --refresh-dependencies
```
then
```
gradlew eclipse
```

also, when searching in JEI, prefix your search with @ for mods

**Comment by eyeonus** [comment]
Github download.
Extract the archive to my workspace.
Run "gradlew setupdevworkspace eclipse".
Run eclipse
Import Gradle Project.
Add the needed jars to mods directory.
Run Minecraft using the MachineMusePowersuits-1.10.2-Java_Client
Crash from errors from the other mods.
Move the jars to a "lib" folder and add to the Build Path because tossing them in the mods folder wasn't working.
Run Minecraft using the MachineMusePowersuits-1.10.2-Java_Client
Take screenshots.

**Comment by lehjr** [comment]
not sure, I don't use eclipse, but I think you needed to run gradlew eclipse
I know you do with Intellij

**Comment by eyeonus** [comment]
Yes, I know. "@power" shows nothing at all, and "power" still would've shown the power fist, power armors, etc.

**Comment by eyeonus** [comment]
According to the three different tutorials I looked at, I used the right command for setting it up in eclipse.

As you can see from the first screenshot, the source is showing. Eclipse knows it's there.

MINECRAFT doesn't.

**Comment by lehjr** [comment]
yes, you're right. However, the project isn't setup if the mod isn't showing. This is literally all I do to set the mod up for development (note I use intellij): 
```
gradlew setupDecompWorkspace --refresh-dependencies
```
then
```
gradlew idea
```

**Comment by lehjr** [comment]
then open the project rather than importing it

**Comment by eyeonus** [comment]
Just to make sure, I did a test.
`gradlew setupdevworkspace eclipse`
does the exact same thing as
`gradlew setupDecompWorkspace --refresh-dependencies
gradlew eclipse`
except as one command, not two.

I'm trying again starting with a git clone instead of a download.

**Comment by eyeonus** [comment]
No. I'm sure it's not anything to do with the repository. The mod shows up just fine in the project. All the source is there. It's just not showing up in Minecraft.

So, again, how do you run it?

**Comment by lehjr** [comment]
again, I do not use eclipse

**Comment by eyeonus** [comment]
What are the run conditions you use when you run it from within IntelliJ?

Or, more simply, how do you run it?

**Comment by lehjr** [comment]
the mod can show up as files, but that does not mean the project is set up correctly. You can have source files not associated with the project.

**Comment by lehjr** [comment]
select run from the drop down menu, that's pretty much it

**Comment by lehjr** [comment]
If you import the project as a gradle project rather than opening it as an eclipse or idea project, your project files will likely get overwritten

**Comment by eyeonus** [comment]
I assure you, that is not the case.
![src main java](https://cloud.githubusercontent.com/assets/1733600/24988806/83d905c0-1fc5-11e7-943a-2bbf3e663371.png)

**Comment by lehjr** [comment]
"project files" being the IDE settings files

**Comment by eyeonus** [comment]
No, it asked me if I wanted to keep or overwrite.

**Comment by lehjr** [comment]
check the logs, if the mod does not show up in the logs, then the project is not set up correctly. It's really that simple. It doesn't matter what files you can open if the IDE is not seeing them as source files in the source directory.

**Comment by lehjr** [comment]
I set the mod up all the time, especially when I want to test something sketchy and I've never had the issue you are having.

**Comment by eyeonus** [comment]
Minecraft isn't detecting it because an mcmod.info isn't getting generated.

Apparently I need to build it first, which is what I thought I was doing when I told the thing to run....

**Comment by eyeonus** [comment]
How many times do I have to tell you I know for a fact that the IDE is seeing the source files as source files? I even showed you a damned screenshot!

**Comment by lehjr** [comment]
and how many times do I have to tell you that you can have source files in a project not associated with the project. And how many times do I have to tell you that if the mod isn't visible, the project is not set up correctly.

**Comment by lehjr** [comment]
I'm done with this. Either you'll figure it out or you wont. But it won't be with any further help from me
