### ISSUE TITLE
[MachineMuse/]: Item eng_toolbox:modular_socket not found in registry for recipe

### ISSUE THREAD

**Issue by jasonsaffle13** [MachineMuse/MachineMusePowersuits#779]
This keeps spamming my console over and over. I do not have engineers toolbox installed I will drop it in and see if it will stop. This is with the Final (final) 1.7.10 build.

**Comment by lehjr** [comment]
No idea. It's not something I have ever seen before. Not something in Modular powersuits. Keep in mind that 1.7.10 is no longer supported, but if it was, you would not have supplied enough information to be able to diagnose or replicate the issue.

**Comment by jasonsaffle13** [comment]
I was able to stop all console spam by dropping in Eng. toolbox mod so it's all good.  I was going to upload the mod list and the forge logs but no need and it's no longer supported, but just in case this is here if anyone else has issue and searches for it.
