### ISSUE TITLE
(Suggestion) Galacticraft Oxygen Sealer for 1.10.2

### ISSUE THREAD

**Issue by StevieNicholai** [MachineMuse/MachineMusePowersuits#780]
In case you didn't know Galacticraft is in Beta for 1.8.9, 1.10.2, and 1.11.2, but there is no Oxygen sealer in Modular Powersuits (Helmet Module). So maybe, could you add that (I know that this may take a bit of time, so if you don't get it out for a while, I completely understand, and I don't code, so I can't exactly help with this).

**Comment by lehjr** [comment]
Once MPS is out of Alpha stage, I'll look into it. Right now I'm spending as much time waiting for the game to load as I am writing code. AE2 support should return as well, as will compact machines support.

**Comment by lehjr** [comment]
Fixed in the next alpha. Should be up tonight.
