### ISSUE TITLE
No recipies with JEI/NoNumina 1.10.2?

### ISSUE THREAD

**Issue by McMercy** [MachineMuse/MachineMusePowersuits#781]
Im guessing there is no recipies since I don't have the numina mod? I can't seem to find any download for 1.10. How do I get the vanilla recipies?

**Comment by lehjr** [comment]
Numina is in the MPS jar file. What version of the mod are you using?

**Comment by McMercy** [comment]
ModularPowersuits-1.10.2-1.2.110.jar

**Comment by lehjr** [comment]
recipes should be in .minecraft/config/machinemuse/recipes

**Comment by McMercy** [comment]
Yes. There is a file called "mps-vanilla.recipes", but the recipes aren't showing in JEI

**Comment by lehjr** [comment]
What version of JEI are you using?

**Comment by McMercy** [comment]
JustEnoughResources-1.10.2-0.5.9.3

**Comment by lehjr** [comment]
that's not just enough items.

**Comment by McMercy** [comment]
jei_1.10.2-3.14.7.417
Sorry, commented too quickly

**Comment by lehjr** [comment]
hmm, I'll have to check with the newer version of JEI. I'm still using 3.14.7.415

**Comment by McMercy** [comment]
That version is for 1.10 aswell I see. I can try that version of JEI and see if that helps

**Comment by lehjr** [comment]
I'll need to update anyway

**Comment by McMercy** [comment]
The recipes works for me aswell with 3.14.7.415
Will use it untill you update :)
Thanks!

**Comment by lehjr** [comment]
thanks for the heads up

**Comment by lehjr** [comment]
tried with jei_1.10.2-3.14.7.419 and recipes still work, at least in the current code. If this issue happens again this can be reopened.
