### ISSUE TITLE
enhancement- RS 

### ISSUE THREAD

**Issue by RobinNightWing** [MachineMuse/MachineMusePowersuits#782]
Maybe u should add compatibilty with the refined storage system like u did with AE2 in the power fist

**Comment by lehjr** [comment]
I was considering this a while ago but never really took much time to investigate it.

**Comment by RobinNightWing** [comment]
Well I think it'd be a great idea, since the mod supports/supported AE2, and RS is gaining some popularity

**Comment by lehjr** [comment]
tend to agree, since ae2/3 development seems to be losing a bit of steam. Some type of mass storage support is needed for sure.

**Comment by RobinNightWing** [comment]
Also, maybe there should be some support for the wireless crafting grid and the wireless crafting terminals by The Realp455w0rd, just as an upgrade for the original support for AE2, and perhaps RS in the future

**Comment by lehjr** [comment]
I'll be looking into this after I get some of the major issues fixed. The rendering glitches are currently the priority.

**Comment by lehjr** [comment]
This is done and will probably show up this weekend in an alpha for testing this. I want to get some feedback on it before releasing it before moving it to a beta. 
In terms of functionality, the actual device opened depends on whether or not the wireless crafting grid is installed. So if you don't have the wireless crafting grid installed and then decide to install it later, your wireless grid module will work as a wireless crafting grid module.

**Comment by lehjr** [comment]
This will be in ModularPowersuits-1.10.2-ALPHA-12, and newer if it works like it's supposed to.

**Comment by lehjr** [comment]
Included in latest alpha.
