### ISSUE TITLE
[Enhancement] realign meters to horizontal and align with numeric display

### ISSUE THREAD

**Issue by eyeonus** [MachineMuse/MachineMusePowersuits#784]
The "glass" part is in the right spot and turned the right way. Looking good. Next up is the "fluid" part.

https://youtu.be/eB51dJsPAyo

**Comment by eyeonus** [comment]
Fluid done. Lightning is all that's left.
![moar progress](https://cloud.githubusercontent.com/assets/1733600/25031946/815a3e40-208d-11e7-8ff5-36409fa0cf48.png)

**Comment by eyeonus** [comment]
BTW, a side effect of the changes I made to the code to make it horizontal instead, is that adding new meters is simply a matter of adding the `if (max<meter> > 0 && draw<meter>Meter ){` and `if (<meter> != null) {` checks for the new meter, and the new ones will show up in order first to last, top to bottom.

**Comment by eyeonus** [comment]
The realignment is complete. I knocked out the fix to the lightning drawing during my lunch break.

Here's a video of it in action:
https://youtu.be/ZruD4VOQai4

And here's the diff patch:
https://pastebin.com/nJfeWHtF

I kept the original vertically aligned code in and just commented it, in case for some crazy reason you do want to create an option to toggle between horizontal and vertical. Personally, I'd just tell anyone who asked for that to buzz off, but, you know, to each his own.

Also, it seems like the lightning gets drawn BEHIND the texture, which makes it very difficult to see on the portal texture.

I'd suggest either choosing a different texture or maybe moving EnergyMeter's drawFluid() call to be before the lightning drawing code on the assumption that would cause lightning to be drawn on top, but I'm going to leave those design choices to you.

[EDIT] Oh yeah, if you like, since I have a working dev environment, if you like I can help out with the coding. I can't really help you with anything graphical, but I'm pretty alright when it comes to just plain coding.

**Comment by lehjr** [comment]
Very nice work. The portal texture was a recent change. I thought it was a better choice than having 2 meters with the water texture. It seems it does have a bit of an issue in the dark though.

**Comment by eyeonus** [comment]
Thank you. I agree about the texture thing. I'm not sure that particular texture's the right one though. What about purple hardened clay?

**Comment by lehjr** [comment]
I think I tried that for the plasma meter, but it was opaque so I didn't really like it. I did try a bunch of different colors. Really though, I've been wondering about how those textures are handled in the case of a texture pack where the size is completely different. Seems the size is hard coded in the meters instead of being read from the texture attributes and adjusted accordingly.

**Comment by lehjr** [comment]
I've never seen a complaint, so I don't know if it's even an issue. I guess I should just try it sometime. 
I'll mess around with meter colors after I get the meter code merged. Currently I'm messing around with the personal shrinking device for Compact Machines. There's already a couple of 1.10.2 builds for it, so this is as good of a time as any. That and the meters will be the last thing for the next alpha.

**Comment by eyeonus** [comment]
Aren't all the textures opaque, though? I don't know if it's possible to set the meter textures to be transparent, except maybe by using a transparent texture in the first place.

The method that does the drawing has maximum size of 16, so only the top left 16*16 pixels ever gets drawn, I assume. That maximum size isn't part of the method itself, though, it's just that a value above 16 to define the dimensions of the texture to draw are never passed to the method in any of the calls to it.

So, in a 32*32 texture pack, the top left quarter of the texture gets drawn.

You could easily test it, of course. Just create a texture bigger than 16*16 that is easy to see how much of it is being drawn (like a checkerboard pattern or some such), replace one the the texture's being used by the meters, and see how it looks in the meter.

[Grammar edit]

**Comment by lehjr** [comment]
some textures are actually translucent. Different viewers and editors will show them differently. I'm really not sure about the technical aspects of it, but if you check out the tinker table texture, you'll see the translucent green areas. Oddly they actually work on an OBJ model if you're holding it, but not placed, not yet anyway.

**Comment by eyeonus** [comment]
Meh. It's not a big deal. Hard to see lightning is a minor quibble compared with the other issues.

Oh yeah, the actual method that does the texture drawing can handle any size texture. It draws the texture aligned top-left at the xpos, ypos, and the way it draws it is by getting the bounds x1,x2,y1,y2 and drawing whatever is in those bounds. (So if you gave it 0,32,0,16 as the bounds, it would draw the texture you called and the texture after it in the texture map, assuming 16*16 textures.)

**Comment by eyeonus** [comment]
Is it possible to get the texture to be drawn translucent even when it isn't? Does OGL have an alpha setting?

**Comment by lehjr** [comment]
Yes, there's an alpha setting used in different places in the rendering code. For the meters is should probably be safe, but using it for ModelBase models seems to have an issue with bleeding into other models, like chests.

**Comment by lehjr** [comment]
RenderState.blendingOn();
RenderState.blendingOff();
Those are the implementations in the mod. As far as I can tell, they are working fine for everything except the ModelBase models, maybe as a side effect of threaded rendering, I don't know.

**Comment by eyeonus** [comment]
Maybe that's what the WHITE value passed in the call to draw the textures is? The alpha layer? I don't really have the time to check that, my lunch is over.

**Comment by lehjr** [comment]
It might be. I'll look into it tonight.

**Comment by eyeonus** [comment]
This seems relevant:
`public Colour withAlpha(double newalpha) {
        return new Colour(this.r, this.g, this.b, newalpha);
    }`

Maybe try `Colour.WHITE.withAlpha(0.5f)`?

**Comment by eyeonus** [comment]
Since this has been merged in, I'm going to go ahead and close this. If there's anything you'd like me to look at, let me know.

**Comment by eyeonus** [comment]
> Yes, there's an alpha setting used in different places in the rendering code. For the meters is should probably be safe, but using it for ModelBase models seems to have an issue with bleeding into other models, like chests.

If you can get that to happen to blocks too, boom! Colored lighting! :)

**Comment by eyeonus** [comment]
I've been experimenting with the colour thing. Using a colour with a 0.0 ≤ alpha < 1.0 does make it transparent. And it'll tint the texture too.

Check these out:
![2017-04-15_00 48 38](https://cloud.githubusercontent.com/assets/1733600/25061667/eca44c68-2178-11e7-955c-8462702359bb.png)
![2017-04-15_00 56 33](https://cloud.githubusercontent.com/assets/1733600/25061671/eca6ee46-2178-11e7-9eb6-0ca29da8ce7e.png)
![2017-04-15_00 56 45](https://cloud.githubusercontent.com/assets/1733600/25061670/eca6c920-2178-11e7-8f19-335b4ebbfcf1.png)
![2017-04-15_01 06 01](https://cloud.githubusercontent.com/assets/1733600/25061669/eca64bee-2178-11e7-9b78-49957bb8437d.png)
![2017-04-15_01 10 03](https://cloud.githubusercontent.com/assets/1733600/25061668/eca4ce9a-2178-11e7-9932-d975413be65c.png)

**Comment by eyeonus** [comment]
Here's the diff patch.
https://pastebin.com/RiMF0a4t

I also cleaned up the code for the meters, eliminated a lot of unnecessary duplication of code, and I fixed the mistake I made in the lightning drawing as well.

With the patch, it is possible to set a custom texture, coloring, and alpha level on each meter individually by creating the appropriate "get" method, or just inherit those values from HeatMeter, so you could, for example, just use the texture HeatMeter is using, but with a different color. I recommend playing around with it a bit.
