### ISSUE TITLE
Shears on vines drop powerfists

### ISSUE THREAD

**Issue by dshadowwolf** [MachineMuse/MachineMusePowersuits#790]
Yes - using a powerfist with the shearing module active on vines causes powerfists to drop

**Comment by lehjr** [comment]
gonna need more details than this.

**Comment by lehjr** [comment]
Looks like the  latest version. o.0

**Comment by lehjr** [comment]
It's not just vines but every plant.

**Comment by dshadowwolf** [comment]
Yeah, sorry, was going to do some more testing and got distracted by fun world-gen from one of the mods in the pack I'm playing. Yes - it is the latest available on CurseForge and I only tested on vines.

**Comment by lehjr** [comment]
Anyway, thanks for the heads up. This will be fixed in the next version.

**Comment by lehjr** [comment]
fixed here: https://github.com/MachineMuse/MachineMusePowersuits/commit/60f8909cb3ce41d1bd9b1d87c5da9fbfc8609908#diff-75bce4c4e18e858c59ce36af1eb047aeL141

and included in latest alpha.
