### ISSUE TITLE
Power Fist Causing To Crashing My MC! But I can't be bothered with logs so I want you to guess what is happening. 

### ISSUE THREAD

**Issue by SorryForKs** [MachineMuse/MachineMusePowersuits#791]
My mc version : 1.7.10
My forge version : Forge 10.13.4.1481 -1.7.10-1.7.10
i got Numina the version is : Numina - 0.4.1.105
The version of the mps : MoudularPowersuits - 1.7.10-0.11.1.114

I'm tried to figure it out but i cant i downloaded a lot of different versions of numina and mps and they stil not work the crash report : 

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/machinemuse/powersuits/item/ItemPowerFist

PLZ HELP 
Thx for the guys who helping and thx for the guys who trying to ^_^

**Comment by lehjr** [comment]
No, it's not. The least you could do if you wanted support for an unsupported version is provide the logs. Most likely the issue is with an outdated mod that adds an addon module to the powerfist but since you provided no log, I cannot tell you for certain.
