### ISSUE TITLE
Sprinting is messed up in some unspecified version, but I can't be bothered to provide enough details for you to look at it. Instead I want you to guess. 

### ISSUE THREAD

**Issue by coleweinman** [MachineMuse/MachineMusePowersuits#792]
Vanilla sprinting without any suit is broken, it like accelerates to the normal sprinting speed and it is very annoying.

**Comment by eyeonus** [comment]
That's not nearly enough information. Read the readme for what is needed to submit a bug report.

It's on the main page.

**Comment by lehjr** [comment]
If you can't take the time to fill out a proper bug report, I'm not going to take the time to look into it, let alone fix anything. This is almost the same as just saying "It doesn't work" and nothing more.
