### ISSUE TITLE
Vanilla sprinting mechanic is distorted

### ISSUE THREAD

**Issue by coleweinman** [MachineMuse/MachineMusePowersuits#793]
Version: 1.10.2-1.2.114
Mods involved: only ModularPowersuits
Description: When trying to sprint without a power suit, it's not normal in that you accelerate to sprinting speed and the FOV effect is gone.

How to reproduce: Start up a world and double tap w to start sprinting. (Compare with vanilla.)

**Comment by lehjr** [comment]
the FOV effect is configurable in Numina. Has been that way for years.
