### ISSUE TITLE
[Texture] LuxCap taking up a huge Chunk on the texture Atlas

### ISSUE THREAD

**Issue by BloodWorkXGaming** [MachineMuse/MachineMusePowersuits#794]
powersuits:blocks/LuxCap is using up 5% of the hole texture atlas of the ATM1 Modpack.

run [TextureDump](https://github.com/mezz/TextureDump) to check it out for yourself, but here is a screenshot of parts of the atlas from atm1:

![image](https://cloud.githubusercontent.com/assets/8137062/25922017/e9e8d872-35d7-11e7-9732-ecd19c81655e.png)
It is up there with a lot of other textures which are too big, but a 1024x1024 Texture is far too big for such a simple object and probably can't even be rendered in that size on the screen.

**Comment by lehjr** [comment]
The Lux capacitor texture has always been overly large for some reason. It's never really been a problem before, but I do agree there is no reason to have a texture that big for something that small and simple.

**Comment by lehjr** [comment]
Scaled it down to 256x256. Will be in the next version.

**Comment by BloodWorkXGaming** [comment]
thanks ^^

**Comment by lehjr** [comment]
got it down even further, now 128x128. Really can't go further without remapping the UV coordinates.

**Comment by BloodWorkXGaming** [comment]
128x is totally okay, since it doesn't really affect performance _as much_, just makes it use less ram, especially vram. 
Thanks for fixing that problem

**Comment by lehjr** [comment]
I'll probably upload the new version in about an hour

**Comment by BloodWorkXGaming** [comment]
Perfect, can include that into the update of ATM1 then
