### ISSUE TITLE
[Suggestion] TechReborn recipes

### ISSUE THREAD

**Issue by Skillotic0703** [MachineMuse/MachineMusePowersuits#796]
A long time ago (for 1.5.2 I guess) you had recipes for gregtech, but gregtech isn't anymore what it used to be but now that TechReborn (for 1.10.2) is pretty stable you can make recipes for TechReborn.

**Comment by lehjr** [comment]
It's not impossible, but without being familiar with the mod, it's rather difficult, especially trying to preserve any sort of balance (challenge/reward).

**Comment by Skillotic0703** [comment]
It's a remake of gregtech 2 so maybe you can copy the old recipes but you'll have to change the recipes for the hologram and glider wing as there are no luminator and magnalium in TechReborn!

**Comment by lehjr** [comment]
I have the recipes done, which will be in the next version. In the mean time, if you want to try them out and see if they need any adjustment, you can find the file here: https://gist.github.com/lehjr/c4e4e27aa2f721a1065e4ff34740ecc7

**Comment by Skillotic0703** [comment]
Thank you very much!

**Comment by Skillotic0703** [comment]
I really like your recipes, they are not too hard or too easy and they make sense but I feel like a few changes would make them even better.
So here is the file that I would recommend: https://gist.github.com/Skillotic0703/6449358690bdb23b7d2a0147bc0c21d5

1) For the tinker table craft, I would replace the standard machine casing by an advanced machine block, the iron plates by steel ingots and the electronic circuit by an advanced electronic circuit.
2) For the solenoid recipe I think that you should keep the old recipe so I would replace the electronic circuit with a tungsten ingot and the iron plates with steel ingots.
3) For the glider wing I would just replace the iron ingot by a steel ingot.
4) I would also keep the old recipes for the capacitors but with the batteries that you put.
5) I think that you should keep the old recipe for the ion thruster (replace the two bottom iridium plates by iridium neutron reflectors) because it's like the ultimate item of MPS so it should be very difficult to acquire imho.
6) For the basic plating I would replace the nickel ingots by steel ingots.
7) There is no uranium ore in TechReborn so you should probably change the recipe of myofiber gel by replacing the uranium with sulfur dust.

**Comment by eyeonus** [comment]
I know GregTech required ic2, and ic2 provides uranium. Does TechReborn not require it?

**Comment by Skillotic0703** [comment]
No TechReborn is standalone and it's a recreation of IC2 pre-experimental + gregtech. https://wiki.techreborn.ovh/doku.php

**Comment by lehjr** [comment]
I'll adjust these tomorrow based on the feedback. Actually good to have someone looking at them before they get included in the next release.
