### ISSUE TITLE
[Suggestion] Adding support to advanced rocketry space suite?

### ISSUE THREAD

**Issue by mzldh** [MachineMuse/MachineMusePowersuits#798]
would it be possible to add a few up grades that can use the Modular Power suite as a space suite?

**Comment by lehjr** [comment]
from the code, it looks like the suit itself is treated as an air tank rather than having a separate air tank like Galacticraft.

**Comment by mzldh** [comment]
yeah, in advance rocketry you have a whole set of space suite using up the armour slots, that's why I think maybe adding a little support to that would be nice?

**Comment by gdarai** [comment]
It would be enough for modular powersuit to not owerwrite the enchantment tag every time you actually put it on.... ```<powersuits:powerArmorTorso>.withTag({ench: [{id: 128 as short, lvl: 1 as short}]})``` would in that instance work the same way as having some upgrade. I'll put this into a new thread.

**Comment by lehjr** [comment]
Enchantments are disabled for the mod, so those tags may end up getting removed somewhere in the tag parsing code, like in EnchantmentHelper. I haven't really dug into the code enough to see. However, the mod is undergoing a major rewrite for 1.12, and the plan is to do a backport to 1.10. I'll be putting this on my TODO list, but I'm not sure how soon I'll be able to get to it. I will try to make it a point to make it happen.

**Comment by lehjr** [comment]
addressed here for 1.10 : https://github.com/MachineMuse/MachineMusePowersuits/commit/2e4706d2ad1c97df9d869579e56aa65c2f1e6ea1
