### ISSUE TITLE
Question about Mechanical Assistance

### ISSUE THREAD

**Issue by PokeMaserJ** [MachineMuse/MachineMusePowersuits#811]
In ModularPowersuits-1.10.2-1.2.123 is this upgrade supposed to drain power when idle?

**Comment by lehjr** [comment]
it will if you are using the mechanical assistance module. If not there may
be some underlying issue not yet discovered.

**Comment by PokeMaserJ** [comment]
Any reason why the Mechanical Assistance upgrade drains power when I'm idle?

**Comment by lehjr** [comment]
It's by design. You can turn it off, but as long as it is on, it will drain power as it is actively offsetting weight.

**Comment by PokeMaserJ** [comment]
fair enough
