### ISSUE TITLE
Client crash on load Caused by: java.lang.NoClassDefFoundError: ic2/api/item/IElectricItemManager

### ISSUE THREAD

**Issue by a-frenzy** [MachineMuse/MachineMusePowersuits#812]
Need some help with this one, Minecraft 1.10.2, Forge 12.18.3.2316, MPS 1.2.124
IC2 not even installed

https://gist.github.com/frenzye/e364b25f05f2482c99b4767588c0868d

**Comment by lehjr** [comment]
I can't replicate the crash, but then again, I'm not going to go through that entire mod list and figure out what mod is triggering the issue.

**Comment by a-frenzy** [comment]
it was Refined Storage. you're welcome
