### ISSUE TITLE
Armour Toughness

### ISSUE THREAD

**Issue by cloakable** [MachineMuse/MachineMusePowersuits#813]
After 1.7.10, Mojang introduced a secondary armour attribute, armour toughness. It makes the armour better at protecting the wearer (high damage reduces the protection, resisted by armour toughness). Would it be possible to support that attribute with MPS? (Thinking basic plating gives no toughness, advanced in line with diamond, and shields possibly superior to diamond)

**Comment by lehjr** [comment]
I'll look into it, but it probably won't be in anything before 1.12

**Comment by lehjr** [comment]
Added in 1.12.2. alpha 6
