### ISSUE TITLE
Pickaxe, axe and shovel not working

### ISSUE THREAD

**Issue by ZeBrasa** [MachineMuse/MachineMusePowersuits#815]
I not able to overclock the tools. Even if it is maxed, it won't make a difference on the speed.
Im using the tekkit pack, with some other mods, which are Mo'creatures, Fossils and Aether 2, with the necessary complements for each. Just another Spawner for Mo'creatures, threadedlighting for Aether and Id fix so I can run the server, cause of the ID conflits with other mods. Sorry if there is anything misspelled or misswrittened, English is not my first language :D 
Ps: Using 1.6.4 version for minecraft, and tekkit server

**Comment by lehjr** [comment]
1.6.4 is not supported and has not been in years.

**Comment by ZeBrasa** [comment]
I know, but if some of you had the same problem, and can help me it would be great. Sorry to bother you with this. I've been looking on old posts, but found nothing.
It's only cause of the tekkit mod, and i don't know if i can update the server with the latest mods without removing the progress of my friends and mine

**Comment by Mysterious-thingy97** [comment]
i deinstalled the aether II and it works, for some reason, I had the same issue in 1.7.10 but now its fixed

**Comment by ZeBrasa** [comment]
Thanks
