### ISSUE TITLE
[1.10.2] Major Power issue with Mekanism and Modular Powersuits Power Suit

### ISSUE THREAD

**Issue by MJRLegends** [MachineMuse/MachineMusePowersuits#818]
Modular Powersuits Version: 1.2.124
Forge Version: 12.18.3.2422
Mekiansm Version: 9.2.4.103

See https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/issues/127 for detals since everything is posted in that issue :D

**Comment by lehjr** [comment]
Interesting. Most likely an MPS issue and not related to Mekanism. Hopefully I'll get a chance to look at it in the next couple days.

**Comment by MJRLegends** [comment]
Thank you

**Comment by lehjr** [comment]
Tested with the modpack itself and as easily able to confirm the issue, or at least as easily as 1fps would allow. Pretty sure this is just a bug in the MPS power implementation. Hopefully I'll have a fix up tonight.

**Comment by MJRLegends** [comment]
Thanks

**Comment by lehjr** [comment]
Fixed version is uploaded, should become visible soon.

**Comment by MJRLegends** [comment]
Thank you
