### ISSUE TITLE
Unable to cycle Tools 

### ISSUE THREAD

**Issue by GalaxyPZ** [MachineMuse/MachineMusePowersuits#819]
Hello,
I play the FTB Infinity Lite 1.10 Modpack and added the Power Armor mod.
I have a very big problem. I can´t change the upgrades like railgun or plasma cannon with Sneak+Mousewheel.

**Comment by eyeonus** [comment]
Tool cycling has been changed. Hold down the hotbar key to open a radial menu, then move the mouse to select the tool directly. (So if the Fist is in hotbar slot 1, hold down the 1 key. If it's in slot 5, hold down the 5 key, and so on.)

This change both allows quickly switching between tools without needing to cycle through intermediaries, awesome when there's a lot of tools installed, and frees up the shift key so tool selection doesn't interfere with every thing else that key does. (Like descending in Vanilla mode flight, for example.)
