### ISSUE TITLE
Key Binding on 1.10

### ISSUE THREAD

**Issue by gdarai** [MachineMuse/MachineMusePowersuits#822]
On Current version of Powersuits, when I open the keybinding menu I don't see any of the installed gadgets. How can I bind them to keys if I don't see them. I also don't understand the cfg file format for keybinding so I cannot do that even there.

**Comment by lehjr** [comment]
screenshot?

**Comment by lehjr** [comment]
Keybinds are handled (mostly) in the tinker table.

**Comment by gdarai** [comment]
Ok that was just some visual bug... they works now. Nevermind.
