### ISSUE TITLE
Problem while Tring to update the mod

### ISSUE THREAD

**Issue by vianney78** [MachineMuse/MachineMusePowersuits#827]
Hello, could you help me i tried to update the mods in 1.7.10, i have the error crash in text file(join file)
[crash-2017-12-10_13.29.46-client.txt](https://github.com/MachineMuse/MachineMusePowersuits/files/1545611/crash-2017-12-10_13.29.46-client.txt)
could you help me please

**Comment by lehjr** [comment]
Don't try to mix and match old and new versions of Numina with MPS

**Comment by vianney78** [comment]
I must update Numina Too?

**Comment by vianney78** [comment]
Thanks it's okay
