### ISSUE TITLE
Client side crash due to Lux Capacitor Model rendering

### ISSUE THREAD

**Issue by MJRLegends** [MachineMuse/MachineMusePowersuits#829]
See https://github.com/MJRLegends/Space-Astronomy-2-Feedback-/issues/215 it contains already needed details

**Comment by lehjr** [comment]
Interesting. I'll look into this when I get a chance, but it will probably be a few days. I'm not sure if I'll be able to reproduce it or not, but I'll give it a shot. I do have some code from the 1.12.2 version that I'm working on that I can backport when it's done. It might help, might not. I just have to make sure I can do it without breaking any existing games.

**Comment by MJRLegends** [comment]
Yeah i was able to reproduce it when i tested it so hopefully it will be reproduceable for you too

**Comment by lehjr** [comment]
The problem is my computer has a hard time just running the mod pack and with default setting's I only see single digit frame rates.

**Comment by MJRLegends** [comment]
Oh rip haha

**Comment by lehjr** [comment]
Anything you can tell me about how you reproduced it? I tried to replicate the issue with 1.4.0 and couldn't.

**Comment by eyeonus** [comment]
MJR, the developer of the other mod, can't reproduce it either, and commented on that bug that he(?) thinks it's a Mac-only issue.

**Comment by MJRLegends** [comment]
@aionys that turned out to be incorrect

**Comment by MJRLegends** [comment]
@lehjr will see what i can do

**Comment by eyeonus** [comment]
Yeah, I saw that. :(

**Comment by lehjr** [comment]
This should be fixed in the latest build

**Comment by MJRLegends** [comment]
@lehjr Nice thank you, just out of interest what was underline cause?

**Comment by lehjr** [comment]
I believe there were a few edge cases where the model was being called before it was fully loaded. The latest version contains a back port of the setup that will be used in the 1.12 version and should be far less error prone.

**Comment by MJRLegends** [comment]
Nice i appreciate your work :D

**Comment by lehjr** [comment]
Should be a bit more efficient but I haven’t had a chance to check the numbers.

**Comment by MJRLegends** [comment]
I will reopen this if i see anymore issues related to this, thanks for your time
