### ISSUE TITLE
Suggestion [More Compat]

### ISSUE THREAD

**Issue by CTH999** [MachineMuse/MachineMusePowersuits#832]
So, a mod with compatibility is great, right?

I think it would be nice if it was compatible with [Advanced Rocketrey](https://minecraft.curseforge.com/projects/advanced-rocketry) Air, as well as [Galacticraft](https://github.com/MachineMuse/MachineMusePowersuits/issues/780) Also, compatibility [Refined Storage Addons](https://minecraft.curseforge.com/projects/refined-storage-addons) and [Applied Energetics 2](https://minecraft.curseforge.com/projects/applied-energistics-2?gameCategorySlug=mc-mods&projectID=223794) (IE Access to you grid on hand. (Or Glove!))

Would work great [Here](https://github.com/zmaster587/AdvancedRocketry/issues/1156) As Well!

Also, what about compatibility with [Mekanism](https://github.com/aidancbrady/Mekanism/issues/4950)

However, this is just a suggestion. It's your mod and your decision. (Last time I checked at least!)

**Comment by lehjr** [comment]
Are you sure you've actually tried the mod? Some of what you are asking for has been around either in the main mod, or the addons that were merged in since mid 1.7.10, with the exception of Refined Storage module being added in 1.10.2 and a hacky work around for Advanced Rocketry added in later in 1.10.2 until I have time to do it right.

**Comment by CTH999** [comment]
I have played the mod. I just didn't know about some of that! (Also, come to think of it, Thaumcraft 6 Casters Gauntlet Would be Nice!) I'm also. I just don't notice most features! I would like some compat with Mekanisim, but I get the feeling that Would be difficult with the way this mod is made. My bad!

**Comment by lehjr** [comment]
Not sure what you're referring to in terms of compatibility with Mekanism. The mod already supports Mekanism power. As far as adding support for things in 1.10.2, that's not likely to happen until I finish 1.12 just due to lack of time and lack of manpower.

**Comment by CTH999** [comment]
@lehjr The 1.12.2 makes sense. And, what I mean is for instance:

1. If Mekanisim is installed, the jetpack requires hydrogen. (Configurable)
2. Refined Glow stone Plates
3. Refined Obsidian Plates
4. A micro-fusion reactor (How would you fuel it?)
5. Mekanisims H2 For some systems if installed
6. Mekanisims Speed (Power Gen, Extra Boosts in systems, faster cooling off, more power)/ Power (Less Power, More Power Storage)/ Gas Efficiency (less usage of gas if needed)/ Muffling (Parts/ _you_ make less noise)

However, just some suggestions!
