### ISSUE TITLE
Why aren't you updating for 1.12? [Help!! No lifeguard at the gene pool]

### ISSUE THREAD

**Issue by GeoGeo85** [MachineMuse/MachineMusePowersuits#833]
Please, someone! It's important, almost every mod is or is gonna be on 1.12! It's the ONLY right time to do an update even just a port! Of course just a port, nothing more! and the sooner, the better!!!

**Comment by eyeonus** [comment]
Don't be a dick. It'll happen when it happens. He's been putting a lot of work into the 1.12 version. Ass.

**Comment by lehjr** [comment]
@aionys I'm going to chalk this up to not having a life guard at the gene pool.
