### ISSUE TITLE
1.12.2

### ISSUE THREAD

**Issue by JoeSGT** [MachineMuse/MachineMusePowersuits#837]
Hello is this mod getting update it to 1.12.2 anytime soon, many other heavy mods already updated already and i was wondering when will this mod going to be update or not ?

**Comment by eyeonus** [comment]
Yes. Stop asking. It will be released when it is released and not a moment before.

Developers hate being asked this question more than literally _anything_ else.

**Comment by guillaumearm** [comment]
@JoeSGT Why did you close this issue ? ModularPowersuits for mc 1.12.2 is not here yet.

**Comment by eyeonus** [comment]
For one thing, it's not an issue, it's a status update request.

**Comment by lehjr** [comment]
...for another, there's already an entire thread dedicated to the 1.12.2 development and a simple search would reveal that.
