### ISSUE TITLE
how i can play the 1.12.2 ver from here? 

### ISSUE THREAD

**Issue by matyklug18** [MachineMuse/MachineMusePowersuits#838]

**Comment by lehjr** [comment]
There have been no releases of the 1.12.2 version because it is still actively under development.

**Comment by matyklug18** [comment]
i wan't test it, and code is in guthub. i downloaded it, but i can't run it. it have errors. i try ./gradlew runClient, but it fails.

**Comment by lehjr** [comment]
Sorry, but I'm not going to write a tutorial for properly setting up a development environment.

**Comment by matyklug18** [comment]
i only wan't to launch client.
it fails: https://pastebin.com/W6M3JcYb

**Comment by lehjr** [comment]
Does't matter what you want to do with it, you still have to properly set up the environment and add the proper dependencies. The error messages tell you what the problem is, you are missing dependencies. That is all the help I am giving you.
