### ISSUE TITLE
[Bug] Cycling on power fist doesn't work

### ISSUE THREAD

**Issue by Skillotic0703** [MachineMuse/MachineMusePowersuits#841]
It's impossible to cycle between tools on the power fist.
I'm using the first 1.12.2 alpha on curseforge.

**Comment by eyeonus** [comment]
Hold down the hotkey for the slot the fist is in. A radial menu will appear.
Move the mouse to select which module you want.
Let go of the hotkey.

The old shift + mouse wheel has been removed since shift is used for about 70 million things, all of which are interfered with by the old method.

**Comment by Skillotic0703** [comment]
ok thanks!
