### ISSUE TITLE
Powersuit components, powersuit components everywhere (in the creative menu)

### ISSUE THREAD

**Issue by TheSnarkyKnight** [MachineMuse/MachineMusePowersuits#842]
Using last version available on CurseForge (1.12.2-ALPHA-1)

Whenever I open any of the creative tabs (both vanilla and modded) in the creative inventory there are powersuit components at the end of the tab. 
I'm guessing the game registered those under all tabs because of a syntax error in the item registration (then again not an educated guess, as I know almost nothing when it comes to programming).

**Comment by lehjr** [comment]
Thanks. Will be fixed in the next alpha
