### ISSUE TITLE
[1.12] Iron and Diamond Plating name incorrect in JEI

### ISSUE THREAD

**Issue by dash16** [MachineMuse/MachineMusePowersuits#843]
When mousing over the Iron and Diamond plating in JEI, the tooltip shows a placeholder name.  All the rest of the items in the mod show the correct tooltip.

item.powerArmorComponent.componentPlatingDiamond.name
item.powerArmorComponent.componentPlatingIron.name

<img width="645" alt="screen shot 2018-08-27 at 12 31 16 pm" src="https://user-images.githubusercontent.com/10954565/44681393-569cd300-a9f5-11e8-89d9-1b6174c0129c.png">
<img width="662" alt="screen shot 2018-08-27 at 12 31 10 pm" src="https://user-images.githubusercontent.com/10954565/44681404-5ac8f080-a9f5-11e8-8213-400e3755edae.png">

Forge: 14.23.4.2758
MPS: ModularPowersuits-1.12.2-0.1.0.1
JEI: jei_1.12.2-4.11.0.212

**Comment by lehjr** [comment]
Thanks. The language files are still a work in progress, but I should have caught those.

**Comment by lehjr** [comment]
field strength translation is also broken for the energy shield.

**Comment by dash16** [comment]
Tooltip on compass also appears to have text from the lightning weapon appended to the end.  Do you want separate bugs for each of these reports, or do you want to collect all the related ones here?

<img width="570" alt="screen shot 2018-08-29 at 11 46 25 am" src="https://user-images.githubusercontent.com/10954565/44808626-942e6700-ab81-11e8-820f-ee5901c72963.png">

**Comment by lehjr** [comment]
Thanks. Fixed in latest commit
