### ISSUE TITLE
Error, unable to log in server

### ISSUE THREAD

**Issue by KamiSami** [MachineMuse/MachineMusePowersuits#849]
Im not sure if this is much of help, but i suspect it might be this mod since it started happening after i installed this, i can't get entire log since it's too large for pastebin but i copied part that i saw server repeately screaming about of, i hope this says something helpful https://pastebin.com/ZpPyi5FU

**Comment by lehjr** [comment]
Usually that would not be enough, but it looks like this is probably a client side method being called on the server. I'll look into it

**Comment by lehjr** [comment]
yup, "func_185359_l()" is actually "getBiomeName()" and is client side only. Testing a fix now.

**Comment by lehjr** [comment]
This should be fixed in Alpha 6 which will be available shortly
