### ISSUE TITLE
[1.12.2]tinker table doesn't detect armour or power fist if they are offhand and/or not worn

### ISSUE THREAD

**Issue by tonimark** [MachineMuse/MachineMusePowersuits#852]
very usual bug the first that I saw when I put items in the creative mod in my inventory and right clicked on a power armour tinker table. The table says that the armour is missing despite as it was in my inventory and my Hotbar mod versions:1.12.2-0.2.0.6

**Comment by lehjr** [comment]
The tinker table only detects equipped items. This is by design.

**Comment by lehjr** [comment]
Not really a bug but reverted to old behavior in alpha 12. The old behavior was better anyway.
