### ISSUE TITLE
suit has durability and breaks upon reaching -1 

### ISSUE THREAD

**Issue by Rynlwar** [MachineMuse/MachineMusePowersuits#854]
tried this in a couple saves, and even with just modular powersuits installed but the suit has durability and once it reaches 0 or -1 i dont know for sure but the suit definitely breaks

**Comment by lehjr** [comment]
Thanks. Yeah, that's definitely a bug

**Comment by Rynlwar** [comment]
I wouldn’t mind it to much if the durability was at like 3000 or more cause that’ll give me plenty of time to repair it, but its showing around 160-200 or so for each piece, hopefully it gets fixed soon as this is my favorite mod out there

**Comment by lehjr** [comment]
The armor shouldn't actually take any damage, probably a porting issue. What version are you using anyway? I vaguely remember seeing that, but I've been working on the next alpha so long I forget what was the last thing I fixed.

**Comment by Rynlwar** [comment]
The latest alpha 6 on 1.12.2

**Comment by lehjr** [comment]
fixed released a few versions ago
