### ISSUE TITLE
game crash while loading 

### ISSUE THREAD

**Issue by voidegg** [MachineMuse/MachineMusePowersuits#858]
crash report net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/machinemuse/powersuits/item/armor/ItemPowerArmorHelmet
    at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:599)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
    at net.minecraft.client.Minecraft.init(Minecraft.java:466)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3929)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: net/machinemuse/powersuits/item/armor/ItemPowerArmorHelmet
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
    at java.lang.Class.privateGetPublicMethods(Class.java:2902)
    at java.lang.Class.getMethods(Class.java:1615)
    at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82)
    at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
    ... 36 more
Caused by: java.lang.ClassNotFoundException: net.machinemuse.powersuits.item.armor.ItemPowerArmorHelmet
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 42 more
Caused by: java.lang.NoClassDefFoundError: thaumcraft/api/items/IGoggles
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 44 more
Caused by: java.lang.ClassNotFoundException: thaumcraft.api.items.IGoggles
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 48 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 965112480 bytes (920 MB) / 1525678080 bytes (1455 MB) up to 2863661056 bytes (2731 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.4.2765 118 mods loaded, 118 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                                           | Version                  | Source                                          | Signature                                |
       |:----- |:-------------------------------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
       | UC    | minecraft                                    | 1.12.2                   | minecraft.jar                                   | None                                     |
       | UC    | mcp                                          | 9.42                     | minecraft.jar                                   | None                                     |
       | UC    | FML                                          | 8.0.99.99                | forge-1.12.2-14.23.4.2765.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UC    | forge                                        | 14.23.4.2765             | forge-1.12.2-14.23.4.2765.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UC    | com.elytradev.movingworld.common.asm.coremod |                          | minecraft.jar                                   | None                                     |
       | UC    | openmodscore                                 | 0.12.1                   | minecraft.jar                                   | None                                     |
       | UC    | foamfixcore                                  | 7.7.4                    | minecraft.jar                                   | None                                     |
       | UC    | elucore                                      | 1.0                      | minecraft.jar                                   | None                                     |
       | UC    | uncraftingtable                              | 1.8-beta6                | [1.12]UncraftingTable-1.8-beta6.jar             | None                                     |
       | UC    | actuallyadditions                            | 1.12.2-r141              | ActuallyAdditions-1.12.2-r141.jar               | None                                     |
       | UC    | baubles                                      | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
       | UC    | actuallybaubles                              | 1.1                      | ActuallyBaubles-1.12-1.1.jar                    | None                                     |
       | UC    | quark                                        | r1.5-130                 | Quark-r1.5-130.jar                              | None                                     |
       | UC    | autoreglib                                   | 1.3-20                   | AutoRegLib-1.3-20.jar                           | None                                     |
       | UC    | betterbuilderswands                          | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
       | UC    | biomesoplenty                                | 7.0.1.2399               | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar   | None                                     |
       | UC    | blockcraftery                                | 0.1.3                    | blockcraftery-0.1.3.jar                         | None                                     |
       | UC    | bonsaitrees                                  | 1.0.5                    | bonsaitrees-1.0.5-b77.jar                       | None                                     |
       | UC    | bookshelf                                    | 2.3.559                  | Bookshelf-1.12.2-2.3.559.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UC    | buildinggadgets                              | 1.6.2                    | BuildingGadgets-1.6.2.jar                       | None                                     |
       | UC    | chameleon                                    | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
       | UC    | chancecubes                                  | 1.12.2-3.2.2.237         | ChanceCubes-1.12.2-3.2.2.237.jar                | None                                     |
       | UC    | ctm                                          | MC1.12.2-0.3.2.18        | CTM-MC1.12.2-0.3.2.18.jar                       | None                                     |
       | UC    | chisel                                       | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                    | None                                     |
       | UC    | codechickenlib                               | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UC    | controlling                                  | 3.0.6                    | Controlling-3.0.6.jar                           | None                                     |
       | UC    | cosmeticarmorreworked                        | 1.12.2-v3                | CosmeticArmorReworked-1.12.2-v3.jar             | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | UC    | cosmeticarmorreworked|tombmanygraves         | 1.12.2-v3                | CosmeticArmorReworked-1.12.2-v3.jar             | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | UC    | craftingtweaks                               | 8.1.9                    | CraftingTweaks_1.12.2-8.1.9.jar                 | None                                     |
       | UC    | crafttweaker                                 | 4.1.10                   | CraftTweaker2-1.12-4.1.10.jar                   | None                                     |
       | UC    | ctgui                                        | 1.0.0                    | CraftTweaker2-1.12-4.1.10.jar                   | None                                     |
       | UC    | mtlib                                        | 3.0.5                    | MTLib-3.0.5.jar                                 | None                                     |
       | UC    | modtweaker                                   | 4.0.13                   | modtweaker-4.0.14.jar                           | None                                     |
       | UC    | jei                                          | 4.12.1.217               | jei_1.12.2-4.12.1.217.jar                       | None                                     |
       | UC    | crafttweakerjei                              | 2.0.2                    | CraftTweaker2-1.12-4.1.10.jar                   | None                                     |
       | UC    | cucumber                                     | 1.1.1                    | Cucumber-1.12.2-1.1.1.jar                       | None                                     |
       | UC    | cyberware                                    | 0.2.10.15                | cyberware-1.12.2-0.2.10.15.jar                  | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
       | UC    | cyclicmagic                                  | 1.16.10                  | Cyclic-1.12.2-1.16.10.jar                       | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
       | UC    | endercore                                    | 1.12.2-0.5.41            | EnderCore-1.12.2-0.5.41.jar                     | None                                     |
       | UC    | enderio                                      | 5.0.35                   | EnderIO-1.12.2-5.0.35.jar                       | None                                     |
       | UC    | mantle                                       | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                        | None                                     |
       | UC    | enderiointegrationtic                        | 5.0.35                   | EnderIO-1.12.2-5.0.35.jar                       | None                                     |
       | UC    | tconstruct                                   | 1.12.2-2.10.1.87         | TConstruct-1.12.2-2.10.1.87.jar                 | None                                     |
       | UC    | p455w0rdslib                                 | 2.0.35                   | p455w0rdslib-1.12-2.0.35.jar                    | None                                     |
       | UC    | theoneprobe                                  | 1.4.24                   | theoneprobe-1.12-1.4.24.jar                     | None                                     |
       | UC    | danknull                                     | 1.4.43                   | DankNull-1.12-1.4.43.jar                        | None                                     |
       | UC    | darkutils                                    | 1.8.211                  | DarkUtils-1.12.2-1.8.211.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UC    | movingworld                                  | 1.12-6.342               | movingworld-1.12-6.342-full.jar                 | None                                     |
       | UC    | davincisvessels                              | @DVESSELSVER@            | davincisvessels-1.12-6.340-full.jar             | None                                     |
       | UC    | endercompass                                 | 1.2.6.2                  | EnderCompass-1.12-1.2.6.2.jar                   | None                                     |
       | UC    | enderiobase                                  | 5.0.35                   | EnderIO-1.12.2-5.0.35.jar                       | None                                     |
       | UC    | enderioconduits                              | 5.0.35                   | EnderIO-1.12.2-5.0.35.jar                       | None                                     |
       | UC    | enderioconduitsappliedenergistics            | 5.0.35                   | EnderIO-1.12.2-5.0.35.jar                       | None                                     |
       | UC    | refinedstorage                               | 1.6.5                    | refinedstorage-1.6.5.jar                        | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
       | UC    | enderioconduitsopencomputers                 | 5.0.35                   | EnderIO-1.12.2-5.0.35.jar                       | None                                     |
       | UC    | enderioconduitsrefinedstorage                | 5.0.35                   | EnderIO-1.12.2-5.0.35.jar                       | None                                     |
       | UC    | enderiointegrationforestry                   | 5.0.35                   | EnderIO-1.12.2-5.0.35.jar                       | None                                     |
       | UC    | enderiointegrationticlate                    | 5.0.35                   | EnderIO-1.12.2-5.0.35.jar                       | None                                     |
       | UC    | ftblib                                       | 5.3.0.54                 | FTBLib-5.3.0.54.jar                             | None                                     |
       | UC    | enderiomachines                              | 5.0.35                   | EnderIO-1.12.2-5.0.35.jar                       | None                                     |
       | UC    | enderiopowertools                            | 5.0.35                   | EnderIO-1.12.2-5.0.35.jar                       | None                                     |
       | UC    | enderstorage                                 | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UC    | valkyrielib                                  | 1.12.2-2.0.17.2          | valkyrielib-1.12.2-2.0.17.3.jar                 | None                                     |
       | UC    | environmentaltech                            | 1.12.2-2.0.17.1          | environmentaltech-1.12.2-2.0.17.1.jar           | None                                     |
       | UC    | erebus                                       | 1.0.23                   | Erebus-1.0.23.jar                               | None                                     |
       | UC    | extrautils2                                  | 1.0                      | extrautils2-1.12-1.9.4.jar                      | None                                     |
       | UC    | foamfix                                      | 0.10.2-1.12.2            | foamfix-0.10.2-1.12.2.jar                       | None                                     |
       | UC    | forgelin                                     | 1.7.4                    | Forgelin-1.7.4.jar                              | None                                     |
       | UC    | ftbutilities                                 | 5.3.0.52                 | FTBUtilities-5.3.0.52.jar                       | None                                     |
       | UC    | guideapi                                     | 1.12-2.1.6-61            | Guide-API-1.12-2.1.6-61.jar                     | None                                     |
       | UC    | immersiveengineering                         | 0.12-85                  | ImmersiveEngineering-0.12-85.jar                | 4cb49fcde3b43048c9889e0a3d083225da926334 |
       | UC    | immersivepetroleum                           | 1.1.9                    | immersivepetroleum-1.12.2-1.1.9.jar             | None                                     |
       | UC    | immersivetech                                | 1.3.10                   | immersivetech-1.12-1.3.10.jar                   | None                                     |
       | UC    | mekanism                                     | 1.12.2-9.4.13.349        | Mekanism-1.12.2-9.4.13.349.jar                  | None                                     |
       | UC    | teslacorelib                                 | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UC    | industrialforegoing                          | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.11.4-214.jar       | None                                     |
       | UC    | inventorytweaks                              | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | UC    | ironbackpacks                                | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar               | None                                     |
       | UC    | ironchest                                    | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar                 | None                                     |
       | UC    | jeresources                                  | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar         | None                                     |
       | UC    | jeroreintegration                            | 1.1.0                    | JEROreIntegration-1.12.2-1.1.0.jar              | None                                     |
       | UC    | journeymap                                   | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                     | None                                     |
       | UC    | mcjtylib_ng                                  | 3.0.5                    | mcjtylib-1.12-3.0.5.jar                         | None                                     |
       | UC    | mekanismgenerators                           | 9.4.11                   | MekanismGenerators-1.12.2-9.4.13.349.jar        | None                                     |
       | UC    | mekanismtools                                | 9.4.11                   | MekanismTools-1.12.2-9.4.13.349.jar             | None                                     |
       | UC    | mekatweaker                                  | 1.1.2                    | mekatweaker-1.12-1.1.2.jar                      | None                                     |
       | UC    | mob_grinding_utils                           | 0.3.11                   | MobGrindingUtils-0.3.11.jar                     | None                                     |
       | UC    | modnametooltip                               | 1.10.0                   | modnametooltip_1.12.2-1.10.0.jar                | None                                     |
       | UC    | numina                                       | 1.10.0                   | ModularPowersuits-1.12.2-0.3.0.10.jar           | None                                     |
       | UE    | powersuits                                   | 1.12.2-0.3.0.10          | ModularPowersuits-1.12.2-0.3.0.10.jar           | None                                     |
       | U     | moreoverlays                                 | 1.14                     | moreoverlays-1.14-mc1.12.2.jar                  | None                                     |
       | U     | mousetweaks                                  | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                    | None                                     |
       | U     | mysticalagriculture                          | 1.6.13                   | MysticalAgriculture-1.12-1.6.13.jar             | None                                     |
       | U     | mysticalagradditions                         | 1.2.8                    | mysticalagradditions-1.12-1.2.8.jar             | None                                     |
       | U     | naturescompass                               | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                 | None                                     |
       | U     | nuclearcraft                                 | 2.12d                    | NuclearCraft-2.12d--1.12.2.jar                  | None                                     |
       | U     | openmods                                     | 0.12.1                   | OpenModsLib-1.12.2-0.12.1.jar                   | None                                     |
       | U     | openblocks                                   | 1.8                      | OpenBlocks-1.12.2-1.8.jar                       | None                                     |
       | U     | oreexcavation                                | 1.4.129                  | OreExcavation-1.4.129.jar                       | None                                     |
       | U     | reborncore                                   | 3.10.1.335               | RebornCore-1.12.2-3.10.1.335-universal.jar      | None                                     |
       | U     | rebornstorage                                | 1.0.0                    | RebornStorage-1.12.2-3.2.2.65.jar               | None                                     |
       | U     | refinedstorageaddons                         | 0.4.2                    | refinedstorageaddons-0.4.2.jar                  | None                                     |
       | U     | resourceloader                               | 1.5.3                    | ResourceLoader-MC1.12.1-1.5.3.jar               | None                                     |
       | U     | rftools                                      | 7.56                     | rftools-1.12-7.56.jar                           | None                                     |
       | U     | rftoolsdim                                   | 5.61                     | rftoolsdim-1.12-5.61.jar                        | None                                     |
       | U     | rftoolspower                                 | 1.1.1                    | rftoolspower-1.12-1.1.1.jar                     | None                                     |
       | U     | soulshardstow                                | 1.12-2.7.6-56            | SoulShards-TOW-1.12-2.7.6-56.jar                | None                                     |
       | U     | stevescarts                                  | 2.4.24.118               | StevesCarts-1.12.2-2.4.24.118.jar               | None                                     |
       | U     | storagedrawers                               | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.7.jar                 | None                                     |
       | U     | tinkertoolleveling                           | 1.12.2-1.0.5.DEV.30c7957 | TinkerToolLeveling-1.12.2-1.0.5.jar             | None                                     |
       | U     | tp                                           | 3.2.31                   | tinyprogressions-1.12.2-3.3.31-Release.jar      | None                                     |
       | U     | tombstone                                    | 3.2.0                    | tombstone-3.2.0-1.12.jar                        | None                                     |
       | U     | universalmodifiers                           | 1.12.2-1.0.16.1          | valkyrielib-1.12.2-2.0.17.3.jar                 | None                                     |
       | U     | vanillafix                                   | 1.0.9-97                 | VanillaFix-1.0.9-97.jar                         | None                                     |
       | U     | woot                                         | 1.12.2-1.4.5             | woot-1.12.2-1.4.5.jar                           | None                                     |
       | U     | xray                                         | 1.4.0                    | xray-1.12.2-1.5.0.jar                           | None                                     |
       | U     | elulib                                       | 0.1.12                   | elulib-0.1.12.jar                               | None                                     |
       | U     | teslacorelib_registries                      | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                | None                                     |
  Loaded coremods (and transformers): Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      FMLPlugin (elulib-0.1.12.jar)
                                        elucent.elulib.asm.ASMTransformer
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.41.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      ForgelinPlugin (Forgelin-1.7.4.jar)
                                        
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-85.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      LoadingPlugin (Quark-r1.5-130.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.9-97.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.2-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      MovingWorldCore (movingworld-1.12-6.342-full.jar)
                                        
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
                                        openmods.core.OpenModsClassTransformer
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
                                   - craftingtweaksIntegration (Enabled/Not Forced)
                                   - theoneprobeIntegration (Enabled/Not Forced)
  Suspected Mods: Unknown
  Launched Version: forge-14.23.4.2765
  LWJGL: 2.9.4
  OpenGL: Intel(R) HD Graphics Family GL version 3.0.0 - Build 8.15.10.2253, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 4x Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz

**Comment by lehjr** [comment]
fixed in next alpha. should be visible soon
