### ISSUE TITLE
Crash when added to DNS Techpack

### ISSUE THREAD

**Issue by MajorMinge** [MachineMuse/MachineMusePowersuits#863]
Hi All,

Running DNS Techpack (latest version) with a couple of added mods, and when I add MMMP there is a crash that I am strugling to identify the cause of. Perhaps some of the mods/forge are too out of date, but I don't know how to diagnose that. Can you point me in the right direction?

Thanks

https://pastebin.com/4kprk40c

**Comment by lehjr** [comment]
That's caused by a very an outdated Forge. Normally I would say grab the latest recommended version, but you can't with Thaumcraft, as it has yet to be fixed. AFAIK, the latest version of Forge you can use is 1.12.2-14.23.4.2766 with that. You may also want to update your mods as well.

**Comment by MajorMinge** [comment]
Thanks a lot mate. I will try updating what I can. 

How were you able to diagnose the old forge version? Calling methods that don't exist?

**Comment by lehjr** [comment]
This particular problem has been around for awhile. The method was added in Forge early on in 1.12.2, and most mod developers are probably using a much later version in their development environment, so it doesn't show up as missing for them. Normally, the best way to avoid it would be to set a minimum Forge version, but given the mod is still in Alpha, it's not the biggest priority.

**Comment by MajorMinge** [comment]
Unfortunately as I am running a modpack it will not be easy for me to update forge. I will just wait for the pack to be updated I suppose!

**Comment by lehjr** [comment]
judging by the looks of the mod versions, the pack isn't well maintained. That version of forge is over 6 months old.

**Comment by MajorMinge** [comment]
You are right. Perhaps the time for maintaining my own pack approaches...
