### ISSUE TITLE
[1.12.2] Crash when hovering over powersuit while holding shift

### ISSUE THREAD

**Issue by solunareclipse1** [MachineMuse/MachineMusePowersuits#868]
With only JEI and Powersuits installed, attempting to shift click any power armor piece (helmet, chest plate, leggings, boots, power fist). This crash does NOT occur when doing it in JEI, it simply tells me there was an error and to check the logs. Crashlog [here](https://hastebin.com/qawonixafu.cs). JEI error [here](https://i.imgur.com/z7hzZTW.png).

Minecraft Version: 1.12.2
Forge Version: 14.23.5.2772
Powersuits Version: 1.12.2-ALPHA-16
JEI Version (for completion's sake): 1.12.2-4.12.1.217

**Comment by lehjr** [comment]
Thanks! Yeah, this is a case of me not paying attention to the class I was using. I should have a fix up in an hour or so.

**Comment by solunareclipse1** [comment]
No problem, have a nice day :)
