### ISSUE TITLE
Crash on load, server only

### ISSUE THREAD

**Issue by ghost** [MachineMuse/MachineMusePowersuits#871]
Forge 2768, Powersuits Alpha 18. This crash happens on startup of a dedicated server only, it does not occur on a singleplayer world.

Pack file: https://minecraft.curseforge.com/projects/continuity/files/2634221

[crash-2018-11-01_21.34.52-server.txt](https://github.com/MachineMuse/MachineMusePowersuits/files/2540847/crash-2018-11-01_21.34.52-server.txt)

Since mod devs seem to be asking me to do this a lot, no, I will NOT update my forge to anything that is not listed as a recommended version on the forge website. No offense meant.

**Comment by lehjr** [comment]
fixed in Alpha 19. Should be visible shortly.

**Comment by ghost** [comment]
That was fast :)
