### ISSUE TITLE
Bugs with Power Armor Legs

### ISSUE THREAD

**Issue by ThatsPM** [MachineMuse/MachineMusePowersuits#88]
Hey there, I really like this new mod, and it's a nice addon to the Direwolf20 modpack! I have encountered 2 issues with the Power Armor Legs at the moment.

First (this one is not so bad); when I use the Uphill Step Assist on the legs, then unequip them, They prevent me from climbing up half blocks as well (stairs/slabs). the ways I've gotten around it is to keep the leggings at all times, switch dimensions or logging off and back in. So yeah, can't go up half blocks after removing the Power Armor Legs...

The other one (and the one that is kinda annoying me =/) is that the Haste enchantment you can get from Thaumcraft 3 overrides the sprint assist from the Power Armor Legs. ( had 2kg of modular Powersuits weight at the time of testing, so that wasn't the issue). So if you have boots with the haste enchantment, you won't get any sprint boosts from the leg armor. Haste is really neat because it affects walking and gliding, but if it neglects your sprinting abilities it's kinda annoying (especially with no ways of removing the enchantment once it is on it)
- Haste hinders sprint assist, but aqua affinity 1 on helm does not hinder aqua affinity from the tool.

I don't  think haste and the sprint assist need to stack, but maybe sprint assist would also ignore any speed enhancing bonus but itself ( so that speed pots or haste enchants wouldn't affect sprinting when sprint assist is activated). Since energy and weight limits pretty much all the options from the Modular Powersuit, I don't think it would make this armor set more overpowered than a mix of quantumsuit leggings and boots of the traveler, which cost no energy to function...

Looking forward to some feedback, keep up the good work!
- I am not the one running the server I am playing on and I'm not really sure on how to update only 1 mod inside a ftb modpack, so we're using whatever version is on the Direwolf20 5.1.1 patch

**Comment by spacebuilder2020** [comment]
Why does it let you enchant it then?  There is no notice that an enchantment does not work, and the armor can be enchanted, but the enchantment is then removed....  Lost valuable soul bound enchants due to it not being documented properly in-game.

**Comment by MachineMuse** [comment]
The armor material's enchantability is 0 and the armor can't be enchanted the vanilla way. If a mod goes around that to allow you to apply enchantments to something that shouldn't be enchantable, then that's not really something I can guard against?

**Comment by spacebuilder2020** [comment]
I used a vanilla anvil to enchant them
