### ISSUE TITLE
[1.12.2] Power fist abilities not Scrolling

### ISSUE THREAD

**Issue by Orikoin** [MachineMuse/MachineMusePowersuits#886]
When installing a usable right-click module on the power fist it becomes the only usable module, requiring the current one to be uninstalled or the on you want to use installed for that moment.
-After encountering this problem on a self made mode pack using ALPHA 25 of power armour.

I've tested with having only the power armour mod installed and couldn't get the function to scroll,
i am right in thinking its shift+scroll to change right?, it did say cycling forward and backward were bound to button 100?
I've tried rebinding button 100 to keys that i can press and see no change.

As i have not crashed i dont think there are any logs i can give.
Chances are I've missed something or am being incredibly stupid, sorry if i am

**Comment by lehjr** [comment]
The scrolling thing hasn’t been a thing for awhile. The current method is to press and hold the hot bar number corresponding to the hot bar slot the power fist is in.

**Comment by Orikoin** [comment]
oh, ive been quite stupid then, thx for the super fast reply

**Comment by eyeonus** [comment]
If only Direwolf20 would do an update spotlight... :D

**Comment by Orikoin** [comment]
i play several modpacks at a time and wanted to try what 1.12 had to offer,
cant believe that i didnt think for a second that the way things were done would be changed 
(facepalm)

a spotlight would indeed give this fun mod some love
