### ISSUE TITLE
Enhancement - removing recipes & Air seal bug

### ISSUE THREAD

**Issue by EngineerXL** [MachineMuse/MachineMusePowersuits#888]
What about recipe module in config? I'd like to remove EnderIO and ThermalExp recipes, but I'd like to see TechReborn recipes.... 
**Also, bug - galacticraft seal doesn't work**

**Comment by lehjr** [comment]
"it doesn't work" is about as lacking in information as you can get.

**Comment by EngineerXL** [comment]
Okay, I installed air seal and went to Moon. I've evuiped oxygen tanks and oxygen gear and also MPW helm with seal, but I got damaged

**Comment by lehjr** [comment]
Yes, I get that "it doesn't work" but you still need to provide more information than that.

**Comment by EngineerXL** [comment]
What info shall I provide?

**Comment by lehjr** [comment]
Version numbers would be a good start. Kinda hard to pinpoint the issue without it

**Comment by EngineerXL** [comment]
Oh, sorry, forget it(
Minecraft 1.12.2; Forge 2768; GalactiCraft and all parts 185; MPS 0.7.0.25;

**Comment by lehjr** [comment]
should be enough

**Comment by lehjr** [comment]
This SHOULD be fixed in Alpha 26.

**Comment by EngineerXL** [comment]
Nice, ty for fast fix
