### ISSUE TITLE
Enhancement - Scannable integration process bar

### ISSUE THREAD

**Issue by EngineerXL** [MachineMuse/MachineMusePowersuits#889]
I think, that process bar would be nice, bcs Fist does not auto-scan (Scanner does). Players, who are playing without sound can't use scanner to some extent
![image](https://user-images.githubusercontent.com/37447286/50987556-03966900-151b-11e9-9549-f77afb893822.png)
![image](https://user-images.githubusercontent.com/37447286/50987587-1446df00-151b-11e9-9881-e34ed96216b0.png)

**Comment by EngineerXL** [comment]
Sorry, haven't seen that it's on the left side) Anyway, I think that central position would be nice

**Comment by lehjr** [comment]
probably not going to happen. It's just not feasible to write a new progress meter for a single module, especially with 1.13 around the corner.

**Comment by EngineerXL** [comment]
kk, I just didn't see this bar for 5 mins(
