### ISSUE TITLE
[1.12.2] No recipes for most items

### ISSUE THREAD

**Issue by hulk6418** [MachineMuse/MachineMusePowersuits#891]
No recipes are working, or appearing in JEI, for most items. The exceptions are the coil and the armour/powertool themselves. However, the recipe for the wiring has been modified to use copper from projectred-core or Mekanism, and silver from projectred. I am unsure of how to modify the config in terms of using vanilla recipes.

Mods:
Modular Powersuits version ALPHA 26
Mekanism version 9.4.13.349
projectred (base, compat, integration, lighting, world) version 4.9.1.92
(complete mod list available on the image attached; .disabled mods are not in use)
![mod list](https://user-images.githubusercontent.com/46621622/51072180-7b899e00-1697-11e9-9ad6-af098941bf45.png)

**Comment by lehjr** [comment]
Looking at the list, you would already be using vanilla recipes. That said, it's not always possible to use resources from other mods because sometimes their resources are loaded after the recipe loader, such as Gregtech.

**Comment by hulk6418** [comment]
That's my issue; the vanilla recipes don't work, even though they should. Are you saying that the load order may be conflicting with the recipes working correctly?

**Comment by lehjr** [comment]
If you’ve edited the recipes to use resources from mods, those resources have to be registered before the recipes load. Unfortunately this is outside my control, which is why Gregtech recipes are disabled.

**Comment by hulk6418** [comment]
Ah, sorry I wasn't clear. I have not manually changed the recipes, they automatically changed to utilise projectred resources. Is this likely due to a different mod I have installed, and not MPS mistaking projectred/mekanism for thermal expansion or IC2?

**Comment by lehjr** [comment]
There isn’t any way of mistaking one mod for another unless the mod is using the namespace of another mod. The recipes themselves mostly use oredict entries. And if those entries don’t exist, or they’re loading after the recipe loader,the recipes don’t get loaded.

**Comment by lehjr** [comment]
Also, there aren’t any recipes for Mekanism.

**Comment by lehjr** [comment]
I still have to find a solution to this, maybe adding Mekanism recipes is the way to go, not sure.

**Comment by lehjr** [comment]
btw, this is why logs are important, especially when filing a bug report: https://gist.githubusercontent.com/lehjr/982f8ebd57447bb03ac19c4a962b754b/raw/a8ea30743eaa0f20414b04a737b9ca40bc39282e/gistfile1.txt

**Comment by lehjr** [comment]
fixed in alpha 27
