### ISSUE TITLE
[1.12.2] super/mod4/windows (and others) key spam.

### ISSUE THREAD

**Issue by ghost** [MachineMuse/MachineMusePowersuits#892]
For a demonstration:

https://www.youtube.com/watch?v=tgD7V8BBdDA

### Sound issue has since been fixed, still leaving the old info for sake of accuracy
~~When someone wears armor, you get a constant "buzzing" noise. When removed, sound stops. When this audio happens, it seems as though it uses all audio channels (voices?) available on the sound device as all other audio gets either muted/nulled or clips horribly. For example, chests will only play thier open/close sounds maybe 20% of the time and when they do the sound isn't fully played.~~
#### Edit end

Hitting the windows key (super/mod4) also causes "notifications" (debug info?) to show. Note, I have all MPS keys unbound. Binding them to any key still causes win/super/mod4 to act the same.

I'm running on Arch Linux, while the person in the video (shazzba) is running Windows 10. We're running the same exact config files and the same jar.

**Comment by lehjr** [comment]
Which version of MPS are you running?

**Comment by ghost** [comment]
Sorry, forgot to post any useful info, was tired that day.

It was previously with version 25. Still seeing with 27 (ModularPowersuits-1.12.2-0.7.0.027.jar). Was previously using forge recommended 14.23.5.2768, now on 14.23.5.2807. Sadly I can't do much more testing as it requires another person.

Is the armor supposed to make sound?

**Comment by lehjr** [comment]
The armor only has a few sounds, but that isn't one of them.

**Comment by ghost** [comment]
Is there any more information I could try and provide to solve this?

Edit: I should have probably mentioned that this happens regardless of sound device used. When the video was made I was using my dedicated sound card (asus xonar d1). Sadly it also happens when using HDMI audio from my gtx 970.

2nd edit: Also should note that the "notification" pops up when pressing other keys as well. I've noticed it with pgup/pgdn, /, backspace and delete.

**Comment by lehjr** [comment]
Generally, the best thing to do is try it with the least amount of mods possible and see if the issue is still present.

**Comment by eyeonus** [comment]
And if not, add back the other mods one at a time until it shows up again.

**Comment by ghost** [comment]
Would either of you be willing to help test this? I can host a dedicated server for this but without anyone to equip the armor, it's would be pointless.

**Comment by Redd56** [comment]
im on ubuntu (running i3 cause i like it more than ram hog manager. i mean gnome.) and i dont got the audio issues, but the super key does still bring up menus. which is wierd

**Comment by lehjr** [comment]
I believe the audio issue was addressed a few weeks ago, but the win key thing, I'm I'm on Kubuntu 18.10 and I don't see it.

**Comment by ghost** [comment]
I edited the title to reflect your fixes.

Currently on alpha 35 on a clean/fresh MC instance with nothing but MPS and Forge (14.23.5.2823) and the two keys (left) windows/super/mod4 and \ (key above enter on US layout) still bring up the MPS menu. Again, all MPS keys are unbound in options and binding them to anything still results in the menu opening.

@Redd56 What version of Ubuntu are you on? Also what version of Java? Are you using the Mojang launcher?

@lehjr What version of Java do you use on Kubuntu? OpenJDK 8  2xx?


I'm still on Arch myself, using [JDK 8.u212-1](https://www.archlinux.org/packages/extra/x86_64/jdk8-openjdk/). For the sake of verbosity, I'm also running nvidia drivers 418.56. Also using [MultiMC 6.5](https://aur.archlinux.org/packages/multimc5/).

Edit: MC log though there doesn't seem to be anything of importance
https://gist.github.com/HellishINC/53ebbcf001359b3d56e854a8baebca00

**Comment by lehjr** [comment]
The next update will include tweaked code for the keybind handler. Other than that, not much else I can do. Keybinding is handled in LWJGL, so I would recommend checking to make sure you have the latest 2.9.x version. MultiMC was using a really old version awhile ago. the 2.9.x branch is already old and was abandoned years ago. 

Also answer the question about my own system specs ...
Kernel 5.0.5-050005-generic
Java 1.8.0_201
nVidia 418 (primary),  amdgpu (secondary)

**Comment by Redd56** [comment]
ubuntu 18.04 sorry for forgetting to clarify, i could have sworn i did
openjdk 8  191
and yes the mojang launcher,
i wish twitch worked on linux but no, curseforge hasnt ported it yet...
and amd pro gpu drivers now, but was running nvidia i forget as i switched to amd like a week ago

**Comment by ghost** [comment]
> Keybinding is handled in LWJGL, so I would recommend checking to make sure you have the latest 2.9.x version. MultiMC was using a really old version awhile ago. the 2.9.x branch is already old and was abandoned years ago.

I'm not sure why you mention this as, correct me if I'm wrong, but 2.9x and 3.x are not compatible? MMC uses a last git version that was ever released. I'm not in disagreement that LWJGL has had its many issues (like not being able to hit shift + 2) but there's not much anyone can really do, unless they want to maintain a nearly 5 year old legacy library.

@Redd56 is also having the issue depsite using the Mojang launcher too.

**Comment by lehjr** [comment]
There are multiple releases for 2.9.x version of LWJGL. There was a jenkins repo for 2.9.x nightly builds a couple years ago, but I believe it was abandoned. Regardless, I've done everything on my end possible. Without being able to replicate the issue, I cannot fix it.
