### ISSUE TITLE
Clients can't connect to server

### ISSUE THREAD

**Issue by Xhale1** [MachineMuse/MachineMusePowersuits#894]
Latest update (alpha 28) makes it impossible for clients to connect to a dedicated server. They receive errors such as being forcibly kicked by remote host, or an internal io exception. Rolling back to alpha 27 fixes the issue.

We tried completely wiping the world and alpha 28 still didn't work.

**Comment by lehjr** [comment]
Generally, wiping the world shouldn't be needed. Usually if something changes enough to require that I put in a warning on the download page. What is needed is to have the same version on both client and server. Beyond that I can't even begin to diagnose the issue without logs.

**Comment by Xhale1** [comment]
Yea, we had the same version on both the client and server. And I would have gotten you the logs, but they too were wiped. I dug through them a bit though and couldn't find much more beyond standard fml connection failed errors. Maybe someone else will have the same issue and can supply logs.

**Comment by lehjr** [comment]
When looking at errors between client and server, you have to look at both client and server logs. This error would have saved a lot of time: 
```[08:16:38] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingEvent$LivingUpdateEvent@61b9a670:
java.lang.NoClassDefFoundError: net/machinemuse/numina/client/sound/Musique ```

**Comment by lehjr** [comment]
Fixed in alpha 29
