### ISSUE TITLE
[1.12.2-Exp] Broken Configuration Options

### ISSUE THREAD

**Issue by TechnicianLP** [MachineMuse/MachineMusePowersuits#897]
After trying to figure out on how to only enable a single recipe type i stumbled across a slight problem:
The respective configuration fields in [MPSSettings.java](https://github.com/MachineMuse/MachineMusePowersuits/blob/1.12.2-experimental/src/main/java/net/machinemuse/powersuits/common/config/MPSSettings.java) are declared static causing the Options on Lines 32, 57, 60, 63, 66, 77 and 81 to be ignored.
Additionally when trying to open the Configuration-Screen (in Mods-List) the following Exception gets thrown: https://hastebin.com/inasugolud

**Comment by lehjr** [comment]
Fixed in alpha 31
