### ISSUE TITLE
Visual bug with some parts of the suit

### ISSUE THREAD

**Issue by VoidFyre** [MachineMuse/MachineMusePowersuits#900]
When i equip the power armor helmet (031 alpha version for 1.12.2) a second helmet appears near my stomach (like an invisible child mob bound to me is wearing it) and the same happens with the jetpack of the chestplate.  Also, when I go to the visual customization and click on the default second color (the blue), it vanishes for some reason.

**Comment by eyeonus** [comment]
Logs? Screenshots? Any supporting documentation of any kind to help track down the source?

Have you done any testing? It could be a mod interaction, have you tried with just this mod and no others installed? If it doesn't happen with nothing else installed, have you tried it with some but not all other mods installed, and narrowed down the combination of mods that causes the problem?

**Comment by VoidFyre** [comment]
It was late and i decided to go to bed, but ill narrow this down tomorrow and do some testing. Due to plans i cant do it today but ill let you know what I find. Im currently troubleshooting my new modpack, Project: Ascension (on the technic launcher, if you want to test it out) and this only started when I updated MPS to the 031 alpha.

**Comment by VoidFyre** [comment]
I did some tests and this seems to be an issue between the 031 version of this mod and the 0.1.1 indev build of the Aether II Highlands.
