### ISSUE TITLE
Rendering Crash on Version Alpha-32

### ISSUE THREAD

**Issue by PessimisticBastard** [MachineMuse/MachineMusePowersuits#902]
When opening up inventory menu, the game crashes due to a rendering bug. Downgrading to Alpha-31 fixes this issue.

Crash log:
https://paste.dimdev.org/qigufubeku.mccrash

MC Version: 1.12.2

Forge Version: 14.23.5.2811

**Comment by lehjr** [comment]
Thanks. I'll have a fix out in a few minutes.

**Comment by lehjr** [comment]
.... [ minutes go by, then turn to hours ] ... 
Unfortunately, I need to fix an issue with a missing lib before I can release the fix for this. Working on it though.

**Comment by lehjr** [comment]
New fixed version should be visible soon.
