### ISSUE TITLE
[Suggestion] Interdimensional capsules.

### ISSUE THREAD

**Issue by Poxorosa** [MachineMuse/MachineMusePowersuits#907]
Its gonna be rideable entity. In this capsule, u can select dimension in which she will fly. After that, u must charge capsule and press teleportation button. U can store items in the capsule, select dimension and coordinates. When u teleorting to another dimension, this capsule wil teleport with u.

**Comment by eyeonus** [comment]
That sounds like a horribly over complicated idea that doesn't suit this mod in the slightest.

**Comment by lehjr** [comment]
Sounds like what you're looking for is a Galacticraft or Advanced Rocketry.
