### ISSUE TITLE
Parachute slows down, does not prevent fall damage.

### ISSUE THREAD

**Issue by CassandraRC7** [MachineMuse/MachineMusePowersuits#910]
FTB Ultimate Reloaded 1.1.1, Windows 10. Multiplayer.

1. Wear a power chestplate with a parachute installed.
2. Get to a high place.
3. Fall.
4. Activate the parachute.
5. (Expected) Land softly, with no fall damage.
5. (Actual) Land softly, and take full (possibly fatal) fall damage.
I have a video of the bug, but it's 500 MB, and I only have 400 kbps up.

**Comment by eyeonus** [comment]
Just out of curiosity, if you install the shock module on the boots, the one that requires wool, and set it to 100%, do you not get hurt in the same scenario?

**Comment by lehjr** [comment]
Should the shock absorber be needed when the parachute or glider is being used? Probably not, but I'd like some input to confirm the expected behavior before I change it.

**Comment by lehjr** [comment]
looks like the issue was caused by this being commented out: https://github.com/MachineMuse/MachineMusePowersuits/blob/1.12.2-experimental/src/main/java/net/machinemuse/powersuits/event/PlayerUpdateHandler.java#L88

**Comment by CassandraRC7** [comment]
> Just out of curiosity, if you install the shock module on the boots, the one that requires wool, and set it to 100%, do you not get hurt in the same scenario?

The shock absorbers work fine, with or without using the parachute.

**Comment by eyeonus** [comment]
> 
> 
> Should the shock absorber be needed when the parachute or glider is being used? Probably not, but I'd like some input to confirm the expected behavior before I change it.

I was just curious as to if that would be a viable workaround, and it might've also led to a source for a fix if one was needed.

**Comment by lehjr** [comment]
I don't know how long it's been broken for, but it's probably been a few months
