### ISSUE TITLE
Exhaustion Compensation calculation is really wrong

### ISSUE THREAD

**Issue by DR01D-Qs** [MachineMuse/MachineMusePowersuits#913]
Jump Assist's Exhaustion Compensation at 100% actually DECREASES player's exhaustion even down to negative values. It does it ~2-4 times by 0.05 points per jump, depends on the time jump key is pressed/jump height.
Sprint Assist's Exhaustion Compensation seems to not do anything at any %

Latest version on 1.12.2. Don't think any additional info is needed, can provide if it is.

**Comment by lehjr** [comment]
This should be fixed in the next release
