### ISSUE TITLE
[1.12.2] Thaumcraft Cloudstepper ring conflict

### ISSUE THREAD

**Issue by hiimcody1** [MachineMuse/MachineMusePowersuits#916]
When using Thaumcraft and MPS together, the Cloudstepper ring no longer fires its double jump. Tested just TC (plus baubles dependency) and MPS (plus numia dependency) alone to confirm no other mods are mucking with things.

I imagine this is due to overriding player capabilities, something with the Cloudstepper may not play well with how jump-assist is handled, but admittedly I haven't looked at the MPS code in detail since 1.7.10, so I can only theorize right now.

I cannot locate a functional FAQ link to determine if this is due to new implemented behaviour/mechanics for the MPS mod.

Versions:
Forge: forge-1.12.2-14.23.5.2814
Thaumcraft: Thaumcraft-1.12.2-6.1.BETA26
Baubles: Baubles-1.12-1.5.2
MPS: ModularPowersuits-1.12.2-1.0.37
Numina: Numina-1.12.2-1.0.36

[Client Log](https://github.com/MachineMuse/MachineMusePowersuits/files/3076281/latest.log)

**Comment by lehjr** [comment]
Not something that can be easily fixed. The ring fails when ```**mc.gameSettings.keyBindJump.isPressed()**``` is used. Even commenting out all other code in the keybinding handler so that no values are set is still enough to cause the ring to not work.

**Comment by hiimcody1** [comment]
Alright. Thanks for checking into it. I'll see if I can hack together a helper mod or something just for my own use in this case.

**Comment by lehjr** [comment]
I believe I have a fix for this. I've been testing it for the past few minutes.

**Comment by hiimcody1** [comment]
I'm more than happy to test it out, would save me trying to get up to speed with 1.12.2's codebase.

**Comment by lehjr** [comment]
should be OK. I just moved the key handling for the jump and down keys to the player tick handler. Seems to be more or less OK now

**Comment by hiimcody1** [comment]
Sounds good. I'll update my jar once changes are pushed. Thanks again for looking into this.
