### ISSUE TITLE
1.12.2 - Latest Ver MPS 1.0.38 - Lux Capacitors Aren't Working

### ISSUE THREAD

**Issue by marikc0** [MachineMuse/MachineMusePowersuits#918]
I have Lux Capacitors installed, but they don't seem to "fire". All the other tool parts work. Using right-click to activate. Checked key-binds and I can't find what I may possibly be doing wrong. Updated MPS to the version that was released today to see if it resolves. Same thing. Possible that I'm just missing something, but I can't be certain. Also tried changing the colors to see if it that jolted it into working.

Also, just an fyi, I'm not sure if the background of the parts (Lux, etc) on the toolbar should be transparent or not but they appear to be black instead. 

Tried asking on FTB Reddit, but they delete posts asking any questions and tell us to annoy you.

https://i.imgur.com/EQfMU6M.png

**Comment by lehjr** [comment]
There was a typo that disabled the modules. Fixed in the next build.

**Comment by lehjr** [comment]
Dupicate of 917

**Comment by marikc0** [comment]
Great. Thanks. :)
