### ISSUE TITLE
Salvage Function not returning any items

### ISSUE THREAD

**Issue by ShadowHex99** [MachineMuse/MachineMusePowersuits#921]
Tested with leather, iron, and diamond armour plating, as well as various other modules on the body, such as jetpack, glider, jet boots, and shock absorber. Tested in a single player world with 1.0 salvage chance in the config. Version: 1.12.2-1.0.39.jar

**Comment by lehjr** [comment]
This is a rather interesting issue. In 1.13.2 this won’t be an issue, as the install cost will be replaced with a crafting recipe, and you’ll have to craft the module to be installed. 
This shouldn’t be hard to figure out. I’ll look into it later today.

**Comment by lehjr** [comment]
This should be fixed in build 40.
