### ISSUE TITLE
Not an issue - a question

### ISSUE THREAD

**Issue by dshadowwolf** [MachineMuse/MachineMusePowersuits#922]
In the 1.7.10 version there was the option of changing the recipes for the various suit enhancements - is that going to return in a later version ?

**Comment by lehjr** [comment]
In 1.12.2, recipes can be changed via resource packs. This is probably how things will work for future versions of the mod. The 1.17.10 way was a nightmare for years.

**Comment by dshadowwolf** [comment]
I meant the install costs - which look to be fixed in code at the moment. Base recipes... yeah - thats an easy enough fix, but the install costs... (I had a 1.7.10 pack that had the install costs changed to better integrate MPS with the other mods in the pack - I'm working on getting it onto 1.12 and actually finishing it)

ie: see <https://github.com/MachineMuse/MachineMusePowersuits/blob/45de030e7cd6ae307eb698478f3e1fd959370922/src/main/java/net/machinemuse/powersuits/item/module/vision/NightVisionModule.java#L21-L22> where you have a fixed install cost... I know I've struggled with trying to make a json-format for non-grid recipes for mods I work on, so I'm not going to push - just wanted to make sure what I'm asking is actually understood :)

**Comment by lehjr** [comment]
for 1.13.2, install costs will be replaced with recipes since the modules themselves will be items. For 1.12.2, I believe most of the code is there. However, I'm currently dividing my time between maintaining 1.12.2 and porting/rewriting the mod for 1.13.2, so finishing, debugging/testing the custom install costs, not really a priority at the moment. So possible, yes, just not at the moment.

**Comment by dshadowwolf** [comment]
ty, makes sense - and don't overwork yourself... I've gotten into burnout territory several times.

**Comment by lehjr** [comment]
I have the code finished, needs testing. Requires update of both Numina and MPS. Only requires the install cost to be on the server, and is synced to the clients automatically on login.
