### ISSUE TITLE
Visual bug with Powersuit arms

### ISSUE THREAD

**Issue by solunareclipse1** [MachineMuse/MachineMusePowersuits#926]
Some odd quirks happen with the arms on powersuits after doing certain actions. Specifically, arms will, for lack of a better word, "desync" with the suit. I have taken some screenshots showing what this looks like. I have put them in an imgur album, which can be accessed via this link: https://imgur.com/a/gDBHiRG

Also, while I do not think that this will help much, here is a log file, from after the screenshots were taken: https://hastebin.com/avukifufic.md (i have removed all instances of my real name, but that is the only change)

I have been able to reproduce this issue. Reproduced on:
Java 1.8.0_211
Forge 14.23.5.2837
With mods:
Numina 1.12.2-1.0.37
Modular Powersuits 1.12.2-1.0.40

I was able to reproduce by flying around with an Elytra for a bit, then equipping powersuit armor. I have not been able to reproduce the bug through any other means using only Powersuits and Numina, but I believe using Quark emotes also causes the issue.

**Comment by solunareclipse1** [comment]
I realize that this is pretty impatient of me, and for that I apologize in advance.

Could I get a response? I realize that it isn't a huge bug, in fact its pretty minor, but I would like to know that it is at least known, even if it is not currently being worked on.

Again, sorry for being impatient, I just want some closure on if this has been noticed or not.

**Comment by lehjr** [comment]
If the updated version doesn't fix it then it's not a bug that can be fixed. Anything that messes with the player model is likely to cause the issue. Not something that I can even address.

**Comment by solunareclipse1** [comment]
So it's something forge has to fix then?
Everything works as intended until some form of animation plays.

Even if it is not possible to have it work with custom animations, is there not some way to have it "reset" back to the working state, from before it stops working? It is fixed by a game restart, but that can take a while depending on amount of mods, all to fix an animation.
I'm not great with java but from my observations, I am going to guess that when some unexpected animation occurs, it simply links the main hand and off hand "sleeves" to animate in the same way. It doesn't seem like it should be too hard to tell the mod to reset the animations back to their original state once the animation is over, right? It's probably not that easy, but again: I am not the best with Java, so this is just a sort of rough idea on what I think could work.

If anything, it could be a default setting in one of the forge configs that messes with it. I'll take a look once I get some time

**Comment by lehjr** [comment]
Did you even try the updated version? And no, there isn't some magic code that you can just spit at the player model to reset it after some other mod has screwed with it through reflection, say RenderPlayerAPI for example. The arms on the model depend on what it's being told the player model is doing. It's as simple as that.

**Comment by lehjr** [comment]
And for the record, this is not some game breaking bug, so it's not going to get treated as such. I'm just one person maintaining one version of the mod while working on another. That's it. That's the team. My time is limited, my patience, even more so when I have to take time from what I'm doing to answer bug reports with less and less information given while higher and higher demands are placed. I cannot work on the mod while I'm answering questions. And quite frankly, my will to even keep the mod going has nearly gone already.

**Comment by solunareclipse1** [comment]
First of all, I apologize. I didn't realize that you were a one man army. For that, serious props.

As for the new version, I checked for new commits before commenting and didn't see anything and was a bit confused. Either way, my mistake. Anyway, it does seem the update fixed it.

### **Feel free stop reading here, as anything after this is unrelated to the bug itself. It's simply my thoughts on what you said about losing interest.**

not gonna try to write in proper grammar here, as its not me.
anyway, i personally love this mod. pretty much always have, ever since i first tried it out back in late 1.6 i think it was. i love how everything about the armor can be customized, even how it looks. the only other armor i can really think of that can be changed visually is chisels & bits armor, which not only doesnt have the whole utility belt of different features, but i cant use that mod to save myself, and the blockier powersuit is pretty much how i would design it anyways. i realize the amount of effort it probably takes to sustain a mod this popular as just a single person, and i seriously cant even imagine doing that myself. personally, if you need a break, take one. dont burn yourself out. if you dont enjoy what you are doing, then why continue doing it? im not going to pretend like i know what kind of shit you deal with. all i can do is just let you know, this is one of my favorite mods. i think it has a lot of currently unused potential and would be sad to see it stop being developed, but if thats what you need to do, go ahead. i realize this probably sounds pretty... cliche? is that a good word for it? well go with that. i get its pretty cliche but i really do think that doing something you dont want to do makes everyone effected by it worse off. if you need a break, take one. if you dont want to develop anymore, then dont. decision is up to you in the end. one last thing: i personally always try to make informative, non-redundant bug reports. im going to go out on a limb and say that the ones who make shitty bug reports probably just dont know better. i personally think a basic issue template + one of those github bots i sometimes see would help with that, but i dunno

all right im done. sorry for the wall of text. i realize that this probably wasnt the best place to put that but im not really sure of anywhere else to put it, and this was convenient.
