### ISSUE TITLE
High poly visuals not available?

### ISSUE THREAD

**Issue by Methlon** [MachineMuse/MachineMusePowersuits#927]
I apologize in advance if I'm wasting your time.

I'm not sure if it's a bug, or a feature not yet re-implemented.
In any event, I don't seem to have any option to change to the old high poly model of the suit.  The only options I get are default and cit joe.

Apologies again if I missed a memo.

**Comment by lehjr** [comment]
version?

**Comment by Methlon** [comment]
1.0.40, just updated tonight.

**Comment by lehjr** [comment]
All of the customization is done through the tinker table in the "visual" tab.

**Comment by Methlon** [comment]
![visual](https://user-images.githubusercontent.com/4023706/58296972-8cf85a80-7d9b-11e9-8479-6d9441d6ddba.jpg)

I can't find an option, or don't know where to look for the option to go to high poly.

**Comment by lehjr** [comment]
High poly models can be disabled in the config. That's the only option to disable/enable them. That whole module thing was removed in 1.12.2. You said you upgraded to 1.0.40 but you didn't say from where. In any event, you can try the reset button to reset your visuals to defaults and clear out any invalid settings. Other than that, I have no idea what you have going on.

**Comment by Methlon** [comment]
1.0.40 was the mod version, sorry I wasn't clear about that.
Minecraft version is 1.12.

So high poly model went away, then. 
Ok, no worries.  I'll just have to do without.  
Thanks for taking the time to get back with me, I do appreciate it.
And also thanks for the mod work you do.

**Comment by lehjr** [comment]
No.
High poly models did not go away. Please reread my response.

**Comment by eyeonus** [comment]
Go to your config.
Find the config for ModularPowersuits.
Find the entry that disables the high poly models.
Turn it off.
Restart Minecraft.

**Comment by lehjr** [comment]
Some thoughts:
> You said you upgraded to 1.0.40 but you didn't say from where
I still do not know what version you upgraded from, meaning what version were you on before 1.0.40. I have no idea whether you were just on a previous version of the mod, or if you were on a previous version of Minecraft. You still haven't answered that.
>  you can try the reset button to reset your visuals to defaults and clear out any invalid settings
still probably needed.

**Comment by Methlon** [comment]
"High poly models can be disabled in the config. That's the only option to disable/enable them. That whole module thing was removed in 1.12.2", -- I assumed that when you said that whole module thing was removed, you meant that the high polly system/model was removed.  Sorry, for misreading.  I'm on call and often insanely low on sleep, with a resulting teetering attention span lol.

I'll try to clarify and add more details.

I updated to mod version of modular powersuits, 1.12.2-1.0.40 from 1.12.2-1.0.39 at the time I opened this ticket.
As of today I see there's a new version out (modular powersuits 1.0.41), which I'll have to update to.
All mod versions are obtained here at curseforge.

Minecraft version is 1.12.2.  It's a fresh world gen.  This map was never updated from a prior map or minecraft version.

Server is using forge.  No spongeforge, just forge.  (v2882, some mods haven't bothered to update to later versions.)

A snippet from the config.
    cosmetics {
        # Allow high polly armor models instead of just skins
        B:allowHighPollyArmorModuels=true  (I tried setting false, no change.)

        # Allow PowerFist model to be customized
        B:allowPowerFistCustomization=false

        # Use legacy cosmetic configuration instead of cosmetic presets
        B:useLegacyCosmeticSystem=true (I tried setting false, no change.)

If I go further into the subdirectories, "machinemuse/cosmeticprests/powerarmor_head" for example, I find four dat files.
Citizen Joe Armor Skin.dat
Default Armor Skin.dat
Default Armor2.dat
Default.dat

I don't know if that's important or not, but in the event there's a missing file, maybe it is lol.
Those are the current settings, and were the ones in use when I posted the above image, in an attempt to illustrate that I'm not seeing any high polly mode available.

I've pusheded buttonses, i've hit reset, I've started running new worlds locally to test different settings.
I've also deleted the powersuits config directory so it could regen.  No change.

At the moment, it's possible the mod is simply smarter than I am lol.

**Comment by lehjr** [comment]
Those config settings should probably be explained better.

The "useLegacyCosmeticSystem" basically is just the same setup that you're used to. The only difference is that there is no module to enable high poly models, but rather they are always enabled. Turning the setting off switches to a system that uses presets where rather than being able to configure the individual parts, you can only pick from a selection of predetermined settings. This is more for servers that have tons of players because using the presets significantly reduces the amount of data that needs to be synchronized between all the players. For single player and LAN users, this probably isn't even needed. 

The preset directory is just that, storage for those presets you see there. The dat files are actually just NBT data stored in a compressed file format on disk. 

A couple things come to mind, make sure both Modular PowerSuits and Numina are both up to date, and make sure you aren't downloading from shady website. I currently only put them on CurseForge. Anything else may be compromised. 

The only thing else I can think of in terms of why this isn't working would be looking at the logs or looking at the NBT data on the armor. The easiest way to get the NBT data is Craft Tweaker (formerly known as MineTweaker).

**Comment by lehjr** [comment]
the allowPowerFistCustomization setting, basically the same thing. It allows the individual pieces of the power fist to be tweaked, but at the cost of adding more data that has to be synced.

**Comment by eyeonus** [comment]
I feel I should point out that in the screen shot, both the high poly head pieces and the Citizen Joe head piece are selected to be shown.

Have you tried turning off the Citizen Joe pieces? It may be a render conflict of trying to render both helmets at the same time?

**Comment by Methlon** [comment]
Ok, did some updates, still nothing.
Having gotten some sleep yesterday for a change, It dawned on me to fire up a local run of minecraft and run only power suits 'n numina.. there, it works, which means something is causing a conflict, and preventing high polly render.  Now I get to slowly re-add mods until I figure out what's causing that.

Thanks guys.
Sorry to have taken up so much of your time, but you got me going in the right direction.

When I figure out what's causing this problem, I'll post my solution, in the event this comes up again.

**Comment by Methlon** [comment]
It's the mod "emoticons" causing the issue.
(It's an animation mod, to make minecraft characters a bit less boring.  Makes sense why it might conflict.)
All set.  Will remove post haste to enjoy glorious power armor.

Thanks again, folks.
I appreciate you hangin' in there with me.
I can't offer you a drink in return, so I'll just have one for each of you tonight lol
