### ISSUE TITLE
Testing, yup it works.

### ISSUE THREAD

**Issue by eyeonus** [MachineMuse/MachineMusePowersuits#930]
**Version info**
Java version:
Minecraft Forge version:

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Mod list**
Including versions, provided by crash report if game crashed:

Smallest sub-list that still produces issue, if any exclusion testing was done:

**Log files**
(Link to pastebin, gist, or other hosting site preferred, file attachment okay.)
Game log (make sure it's the log that was generated during the gameplay the issue occurred in):
Crash report (if issue caused game to crash):
Server log (if issue occurred on a server, make sure it's the log generated during the gameplay the issue occurred in):
Server crash report (if issue caused server to crash):

**Screenshots**

**Additional context**

**Comment by lehjr** [comment]
Yup, much appreciated.

**Comment by eyeonus** [comment]
Anything I can do to help you keep your sanity. :)

**Comment by EzerArch** [comment]
:heart: :clap:
