### ISSUE TITLE
Lux capacitor texture broken

### ISSUE THREAD

**Issue by XCOAnnika** [MachineMuse/MachineMusePowersuits#934]
**Version info**
Java version:1.8.0_211
Minecraft Forge version:14.23.5.2836

![image](https://user-images.githubusercontent.com/26392051/59160909-d656e280-8adb-11e9-8625-b69af831e926.png)

**To Reproduce**
https://drive.google.com/open?id=1Vkfktuy33PjxmVfS8m7TOlq7pdsYn6-c

start a World and place a luxcapatitator

**Mod list**
https://drive.google.com/open?id=1Vkfktuy33PjxmVfS8m7TOlq7pdsYn6-c

Smallest sub-list that still produces issue, if any exclusion testing was done:

**Log files**
https://cdn.discordapp.com/attachments/321715943984201728/587296477483761726/latest.log

Found This could be related:
```
[17:04:34] [Client thread/FATAL] [rs_ctr]: The following mods attempted to register textures into a texture atlas they don't belong:
- cofh
- industrialforegoing
- buildcraftlib
-->powersuits<--
- immersiveengineering
- thermaldynamics
- buildcraftsilicon
- buildcraftenergy
- buildcrafttransport
- genetics
- bibliocraft
- thermalfoundation
- ic2
- buildcraftbuilders
- reborncore
- topaddons
- buildcraftfactory
- appliedenergistics2
- blockcraftery
- ae2stuff
- railcraft
- thermalexpansion
- xreliquary
- buildcraftcompat
- chisel
- computercraft
- ftblib
- flatcoloredblocks
- thaumcraft
- peripheralsplusone
- forge
- mysticallib
- twilightforest
- chiselsandbits
- buildcraftcore
- techreborn
- magicbees
- forestry
- extratrees
Modders please check whether the TextureMap given in texture stitch event is actually the one you want to register to!
```

**Comment by lehjr** [comment]
Tried the base pack without the mods you added and it works fine. If you want to take the time to drill down exactly what mod is causing this issue be my guest. As far as the error message goes, it probably is related. Seems CD4017BE created a separate TextureAtlas when only one is expected, and likely this is related to the issue.

**Comment by XCOAnnika** [comment]
ok fixt it
