### ISSUE TITLE
Power fist Bug

### ISSUE THREAD

**Issue by chyper111** [MachineMuse/MachineMusePowersuits#939]
**Version info**
Java version:
Minecraft Forge version:14.23.5.2838

**Describe the bug**
A clear and concise description of what the bug is. Visuals for power fist won't render in the world any attempt to alter will cause a crash.

**To Reproduce**
1. Go to '...'get a new power fist
2. Click on '....'go to tinker table
3. Scroll down to '....'click visual for tool
4. See error game goes bye bye

**Expected behavior**

**Mod list**
Including versions, provided by crash report if game crashed:

Smallest sub-list that still produces issue, if any exclusion testing was done:

**Log files**
(Link to pastebin, gist, or other hosting site preferred, file attachment okay.)https://gist.github.com/chyper111/c35718ea637eb3cb1584a6d79e6cb887
Game log (make sure it's the log that was generated during the gameplay the issue occurred in):
Crash report (if issue caused game to crash):
Server log (if issue occurred on a server, make sure it's the log generated during the gameplay the issue occurred in):
Server crash report (if issue caused server to crash):

**Screenshots**

**Additional context**

**Comment by chyper111** [comment]
just to stop log spam XD

**Comment by lehjr** [comment]
First thing you really should do is update your java version. It's really, really old. The second thing was: https://github.com/MachineMuse/MachineMusePowersuits/issues/938#issuecomment-506570573

**Comment by lehjr** [comment]
The thing is, I cannot spend the time setting up my development environments with all of your mods to figure out what mods if any are causing this. I really just don't have the time. It's up to you to be able to reproduce the issue with the least amount of mods possible. Once you do that, I can proceed.

**Comment by chyper111** [comment]
tks we will try it soon and keep you updated

**Comment by chyper111** [comment]
sorry ive been buzzy as well i cant find time to pull all the mods apart but i will when i get a chance

**Comment by chyper111** [comment]
hay just so you have one less bug report I'm going to close this since neither of us had time to find it and i don't use this mod or the world it was in any more thanks for trying to help.
