### ISSUE TITLE
Game Crashing with Error

### ISSUE THREAD

**Issue by ShawnStrawman** [MachineMuse/MachineMusePowersuits#943]
**Version info**
Java version: 1.8.0_221
Minecraft Forge version: 1.7.10 - 10.13.4.1614

**Describe the bug**
The game crashes when I start it, giving me an error

**Crash Report**
https://pastebin.com/YXH0uEJU

**Additional context**
When it crashes, it says this:
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/machinemuse/powersuits/item/ItemPowerFist

**Comment by lehjr** [comment]
Pro tip: don't mix a 5 month old version of the mod with a 4 year old version of the library it uses.

**Comment by ShawnStrawman** [comment]
What Library does it use?

**Comment by lehjr** [comment]
It uses Numina but you're using a version from 2015

**Comment by ShawnStrawman** [comment]
Sorry, I kind of ported some mods over from another modpack then added a ton myself. I should have updated them but I got lazy

**Comment by lehjr** [comment]
First rule of bug reports, update before reporting bugs.
