### ISSUE TITLE
PowerFist Not Switching Tools

### ISSUE THREAD

**Issue by jwashb** [MachineMuse/MachineMusePowersuits#944]
The Power Fist won't switch between the Modules. Shift+Scroll does nothing. The tools show up in the tinker table, but I can't switch between them and they don't show in the Keybinds tab of the tinker table. The power fist has full power and the switches for the tools are all set to have power and usage. Even in creative mode, I can't make the tool switch between tools. I have verified that I am not in adventure mode.

**Comment by jwashb** [comment]
I am using FTB Ultimate Reloaded with the latest version.

**Comment by lehjr** [comment]
In the future, please specify the MInecraft version. That said, the shift + scroll operation was replaced awhile ago with a different operation where you press and hold the slot bar number the fist is in.

**Comment by jwashb** [comment]
Thank you lehjr! I played the old Ultimate version and was thinking it would work the same way!

**Comment by eyeonus** [comment]
Can you add a comment text to the power fist's info box that says "hold hotkey for mode select menu" or something to that effect?

Might stop this kind of bug report from happening.

**Comment by lehjr** [comment]
Whether I do that in the tool tip or in the Tinker Table, it requires adding more translations. Currently my hands are full with 1.14.4 and I don’t really want to divert any more time into 1.12.2 since nearly nothing I do there will carry over.
