### ISSUE TITLE
Power fist placing blocks

### ISSUE THREAD

**Issue by Dalethium** [MachineMuse/MachineMusePowersuits#946]
**Version info**
Java version: 1.8 201
Minecraft Forge version: 14.23.5.2838

**Describe the bug**
Blocks from hotbar placed when right clicking when fist is selected, no sound is produced and can also place irregular blocks on non compatible surfaces (such as sapplings on leaves)

**To Reproduce**
1. get some cobble
2. get a fully upgraded fist in slot 1
3. right click anywhere.
**Expected behavior**
no block to be placed when right clicking
**Mod list**
https://pastebin.com/jLQszvYL

**Log files**
Game log https://pastebin.com/raw/YeVDrHRE (warning, quite large)

**Comment by lehjr** [comment]
Unfortunately your mod list is too extensive for me to even look into this. The reality is that I need to see the minimum mods needed to reproduce the issue, so I can track down the cause and fix it. I simply cannot spend the time hunt down all these mods, and painstakingly remove them one at a time until the issue goes away. If I did that, I would be spending all of my free time doing just that and no new version would ever be released.

**Comment by eyeonus** [comment]
205 active mods is way too much for any developer to slog through.

**Comment by Dalethium** [comment]
Yeah hey sorry, I will work to reduce the mod list size. I did however find out that it only happens when when the block is in the final slot of your hotbar.

**Comment by Dalethium** [comment]
I am closing this as I found out it's unrelated to MPS, I am still not sure what causes it but I found it happened with Tiny Progressions Wub Axe. Sorry to waste your time! 

PS: Love the mod!
