### ISSUE TITLE
Enchantment Shimmer Visual Bug

### ISSUE THREAD

**Issue by Jigbashmop** [MachineMuse/MachineMusePowersuits#950]
**Version Info**
Java: Version 8 Update 161
Forge: 14.23.5.2847
MPS: ModularPowersuits-1.12.2-1.0.46

**Describe the Bug**
Enchanting any piece of armor causes the enchantment shimmer to bug out. It only happens on the "Armor 2" and "MPS" versions, not the "Default Armor Skin" and "Citizen Joe" options (guess it doesn't like the polygons). Additionally, they appear as shimmering black squares in the Tinker Table, though they are fine in the inventory.
As a side note, I don't seem to be able to enchant the Power Fist. Was this feature removed due to Issue #937?

**To Reproduce**
Enchant any piece of armor from Modular Powersuits. I used Soulbound from EnderIO when I noticed it, and Protection was used to reproduce it later.

**Expected Behavior**
The normal transparent shimmer effect will be applied upon enchantment.

<details> 
  <summary>Modlist</summary>
   <p>

-p455w0rd's Library (by TheRealp455w0rd)

-Wireless Crafting Terminal (by TheRealp455w0rd)

-ExtraCells2 (by Destroyer7128)

-AE2 Wireless Fluid Terminal (by TheRealp455w0rd)

-AE2 Wireless Terminal Library (by TheRealp455w0rd)

-Pollutant Pump (by bright_spark)

-ForgeEndertech (by EnderLanky)

-Sync (by ohaiiChun)

-More Overlays (by FeldiM245)

-Wawla - What Are We Looking At (by DarkhaxDev)

-Flux Networks (by sonar_sonic)

-Ender IO (by CrazyPants_MC)

-Dynamic Trees (by ferreusveritas)

-CodeChicken Lib 1.8.+ (by covers1624)

-Inventory Tweaks (by Kobata)

-EnderCore (by tterrag1098)

-Advanced XRay (by Lumous)

-Applied Energistics 2 (by AlgorithmX2)

-**Numina (by machinemuse)**

-**Modular Powersuits (by machinemuse)**

-Redstone Flux (by TeamCoFH)

-BdLib (by bdew)

-Matter Overdrive: Legacy Edition (by HRZNStudio)

-JourneyMap (by techbrew)

-Wireless Pattern Terminal (by TheRealp455w0rd)

-SwingThroughGrass (by exidex)

-Mouse Tweaks (by YaLTeR)

-Pollution of the Realms (by EnderLanky)

-AE2 Wireless Interface Terminal (by TheRealp455w0rd)

-Dynamic Surroundings (by OreCruncher)

-AE2 Stuff (by bdew)

-OreLib (by OreCruncher)

-WorldEdit (by sk89q)

-MineTweaker RecipeMaker (by DoubleDoorDev)

-Just Enough Items (JEI) (by mezz)

-Draconic Evolution (by brandon3055)

-CustomOreGen (by lawremi)

-SpatialCompat (by MrDj200)

-Brandon's Core (by brandon3055)

-CraftTweaker (by Jaredlll08)

-iChunUtil (by ohaiiChun)

-Hwyla (by TehNut)

-Optifine
</p> 
</details>

**Comment by lehjr** [comment]
The armor isn't meant to be enchanted in the first place, so the bug is that the armor isn't blocking enchantments.

**Comment by lehjr** [comment]
as to the enchantment shimmer effect being glitched, the skin armor used the vanilla rendering system, the others do not.
