### ISSUE TITLE
Active Camouflage module affects only the chestplate

### ISSUE THREAD

**Issue by EzerArch** [MachineMuse/MachineMusePowersuits#955]
**Version info**
Java version: 1.8.0_51
Minecraft Forge version: 1.12-2847
Modular PowerSuits: 1.12.2-1.0.46

**Describe the bug**
The Active Camouflage module affects only the chestplate.

**To Reproduce**
1. Equip 5 armor pieces: helmet, chestplate, laggings, boots and power fist;
2. At the Tinker Table, install a battery in all armor pieces and the Active Camouflage in the chestplate;
3. Add a keybind to toggle the Active Camouflage (here I'm using "I") and use it;
4. Only the chestplate and the player model become invisible. The other armor pieces don't.

**Expected behavior**
All parts of the armor become invisible. 

**Screenshots**
![2020-02-21_18 32 49](https://user-images.githubusercontent.com/6743303/75074908-6bb7cc80-54db-11ea-9b8d-de6b85ac3a88.png)
![2020-02-21_18 33 01](https://user-images.githubusercontent.com/6743303/75074920-6fe3ea00-54db-11ea-98a3-d23ea85bc11e.png)

**Comment by lehjr** [comment]
unfortunately, the current java 8 version (openjdk8 -242) breaks forge gradle 2.x and anything using it is no longer supported by Forge. As such, this breaks development environments for any version older than 1.13.x 
Using an older version of Java is not trivial, and using a newer java branch is not possible.

**Comment by EzerArch** [comment]
> As such, this breaks development environments for any version older than 1.13.x

So this may be fixed or fixable in 1.14+?

**Comment by lehjr** [comment]
Yes.

**Comment by lehjr** [comment]
fixed in 1.14.4.

**Comment by EzerArch** [comment]
Close it?

**Comment by lehjr** [comment]
won't make much difference either way since everything from 1.14.4 onward is in the MPA fork.
