### ISSUE TITLE
[1.12.2] Module Limit being ignored.

### ISSUE THREAD

**Issue by Rsslone** [MachineMuse/MachineMusePowersuits#959]
**Version info**
Java version: 8
Minecraft Forge version: forge-1.12.2-14.23.5.2847

**Describe the bug**
I have the default config with this
I:maxEnergyStorageModules=1
But I can add multiple batteries to the armors. 

**Expected behavior**
I expected only to be able to add one battery each.

**Screenshots**
https://i.imgur.com/rLL05SA.png

**Comment by lehjr** [comment]
This was the result of a feature that had not yet been implemented. This issue is fixed in 1.16.4/1.16.5
