### ISSUE TITLE
Power Fist Damage does not match 1.7.10 behavior

### ISSUE THREAD

**Issue by DoomRater** [MachineMuse/MachineMusePowersuits#960]
**Version info**
Minecraft Forge version: 14.23.5.2847
Powersuits version: 1.12.2-1.0.46

**Describe the bug**
Power Fist deals 3 damage with no modules installed.

**Expected behavior**
Power Fist is a passive component that should be dealing the same damage as a fist, 1 damage.

**Comment by lehjr** [comment]
Unfortunately, 1.12.2 development is dead. I am currently working on the successor for 1.14.4, and have no time to support anything older. That, and the development environment for 1.12.2 is broken and the version of Forge is no longer supported and won't be fixed.

**Comment by DoomRater** [comment]
Forking.
