### ISSUE TITLE
[Bug] Power Fist module selection not working

### ISSUE THREAD

**Issue by Tobias11007** [MachineMuse/MachineMusePowersuits#965]
**Version info**
Java version: Version 8 Update 241 (build 1.8.0_241-b07)
Minecraft Forge version: 14.23.5.2846
Modpack: FTB Revelation 3.2.0 (Minecraft 1.12.2)
ModularPowersuits-1.12.2-1.0.46

**Describe the bug**
I built a Power Fist and equipped it with elite battery, most of the tools (see images), two weapons and all mining enhancements. However I can't switch between the different modules, only the shears are displayed using sneak (shift)+scroll wheel. The speed modifiers for the pickaxe, shovel and axe appear to work. I have to remove modules in the tinker table for the other modules to become active. I tested the latest ModularPowersuits 1.12.2-1.0.46 and 1.12.2-1.0.45 and both had the same behavior. The java Version is the latest build. The game does NOT crash or BSOD.

**To Reproduce**
1. Build a tinker table and power fist
2. Add various modules from tools, weapons and enhancements
3. Attempt to select PowerFist modules while holding it

**Expected behavior**
I would expect to be able to scroll through the modules with sneak (shift) + scroll wheel and also see previews of the modules to the left and right of the main selected module.

**Screenshots**
Added
![Power Hand showing only shears](https://user-images.githubusercontent.com/63586244/79116260-454e3900-7d88-11ea-8f02-0bcd716df035.png)
![Selected Modules (Off Screen all Mining enhancements selected)](https://user-images.githubusercontent.com/63586244/79116267-48e1c000-7d88-11ea-9e45-ed83319bcaa6.png)

**Comment by EzerArch** [comment]
> I would expect to be able to scroll through the modules with sneak (shift) + scroll wheel and also see previews of the modules to the left and right of the main selected module.

That's deprecated. Hold down Number 1 key (not the 1 in keypad), you'll see a wheel-menu. Select the module with mouse pointer.

![2020-04-13_09 12 03](https://user-images.githubusercontent.com/6743303/79119494-de6c5800-7d66-11ea-89cf-723d26533d61.png)

**Comment by Tobias11007** [comment]
In that case I had a severe case of RTFM (Read The F***ing Manual). Thank you for the fast help! That sorted everything.

**Comment by EzerArch** [comment]
LOL.

You can also assign a keybind to "select next" and "select previous module" in Options > Controls > Modular Power Suits.

**Comment by Tobias11007** [comment]
Is that function in the tinker table or in a config somewhere?

**Comment by EzerArch** [comment]
> Is that function in the tinker table or in a config somewhere?

It's in Minecraft. Hit ESC > Options > Controls > scroll down to Modular Power Suits section.

**Comment by Tobias11007** [comment]
Fab! Thank you very much!
