### ISSUE TITLE
CustomInstallCosts don't work.

### ISSUE THREAD

**Issue by Xemorr** [MachineMuse/MachineMusePowersuits#972]
**Version info**
Java version: openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)
Minecraft Forge version: 14.23.5.2847

**Describe the bug**
Install Costs JSON doesn't work, results in a nullpointerexception.
https://hasteb.in/juroqeju.md

**To Reproduce**
Use this installcosts.json https://hasteb.in/boroxoqi.json

**Expected behavior**
The installcosts worked, and it didn't cause a nullpointerexception.

**Mod list**
Including versions, provided by crash report if game crashed:
Too many, but I have serious doubt as a developer that the other mods would cause this, as you can see from the exception.
Smallest sub-list that still produces issue, if any exclusion testing was done:

**Log files**
(Link to pastebin, gist, or other hosting site preferred, file attachment okay.)
Game log (make sure it's the log that was generated during the gameplay the issue occurred in):
Crash report (if issue caused game to crash):
Server log (if issue occurred on a server, make sure it's the log generated during the gameplay the issue occurred in):
Server crash report (if issue caused server to crash):
Log Files were included above :)

**Screenshots**

**Additional context**

**Comment by TerdyTheTerd** [comment]
Hastebins seems to be expired, did you make sure to validate the JSON first using an online validator? Hint: use [JSONLint](https://jsonlint.com/)

**Comment by lehjr** [comment]
1.12.2 is no longer supported
