### ISSUE TITLE
[Request] trying to enable old easy recipe for my player (1.12)

### ISSUE THREAD

**Issue by thib5** [MachineMuse/MachineMusePowersuits#976]
Hey noob here ! i’m trying to enable the easy recipe in server I setup for players 

I’m using ftb ultimated reload modpack

**Comment by TerdyTheTerd** [comment]
That pack includes CraftTweaker, look up the documentation for it. Recipe modifications are pretty simple with it. [CraftTweaker Docs](https://docs.blamejared.com/1.12/en/Vanilla/Recipes/Crafting/Recipes_Crafting_Table/)

**Comment by lehjr** [comment]
1.12.2 is no longer supported
