### ISSUE TITLE
ExtraPlanets Radiation Modules don't work. (1.12.2)

### ISSUE THREAD

**Issue by Starbimkrieg** [MachineMuse/MachineMusePowersuits#978]
**Version info**
Java version: 1.12.2
Minecraft Forge version: N/A

**Describe the bug**
Tier 4 Radiation Module (and it's predecessors) do not work. I have to equip an ExtraPlanets thermal set in order to protect myself from radiation on planets that need anything past the first tier of radiation shielding.

**Mod list**
Using the "1.12.2 Pack" - over 270 mods or something.

**Comment by lehjr** [comment]
1.12.2 is no longer supported
