### ISSUE TITLE
Salvage return percent ignored 1.12.2

### ISSUE THREAD

**Issue by vovannn012347** [MachineMuse/MachineMusePowersuits#979]
**Version info**
Java version: 1.8.1_131
Minecraft Forge version: 14.23.5.285

**Describe the bug**
Salvage return value in config is ignored entirely, no items are returned

**To Reproduce**
1. Go to power armor tinker table
2. Install any moule on any item
3. Click "salvage" in interface with selected the module
4. See no items returned

**Expected behavior**
4. items are returned in acordance to rnd and config return value 

**Mod list**
Optifine_1.12.2_HD_U_F4
ModularPowersuits-1.12.2-1.0.37

**Comment by vovannn012347** [comment]
Oh, seems this git is dead, still will leave issue here

**Comment by EzerArch** [comment]
> Oh, seems this git is dead, still will leave issue here

@vovannn012347, not exactly dead, the new developer @lehjr is maintaining the mod here: https://github.com/lehjr/ModularPowerArmor (1.14+ only)

**Comment by lehjr** [comment]
1.12.2 is no longer supported
