### ISSUE TITLE
Minecraft Mc Eternal - Powersuit crashes when ever going into water

### ISSUE THREAD

**Issue by uehlbran** [MachineMuse/MachineMusePowersuits#980]
**Version info**
Java version: 1.8
Minecraft Forge version:14.23.5.2847

**Describe the bug**

**To Reproduce**

1. Equip all four pieces of armor
2. Fully upgrade every single piece of armor with every option available
3. Hop into a large body of moving water
4. Crash

**Expected behavior**

You should not crash when entering water.

**Mod list**

Minecraft MC Eternal (version 1.3.7) no changes to the modpack

Smallest sub-list that still produces issue, if any exclusion testing was done:

**Log files**
https://pastebin.com/nXBCaNFE

**Comment by lehjr** [comment]
1.12.2 is no longer supported
