### ISSUE TITLE
(1.12.2) With Forestry Installed, Power Fist Behaves As If Grafter Is Installed When It Is Not.

### ISSUE THREAD

**Issue by TeetoKaziim** [MachineMuse/MachineMusePowersuits#983]
**Version info**
Java Version: 1.8.0_242, AdoptOpenJDK
Minecraft Forge version: 14.23.5.2854

**Describe the bug**
Even with no augments installed, and no power available, the Power Fist behaves as if it has a grafter installed

**To Reproduce**

Install Modular Powersuits, Numina, and Forestry.
Acquire Power Fist.
Apply no augments, acquire for it no source of power.
Break leaf blocks with it in survival mode.
You will get a sapling every time.

**Expected behavior**

Without the Grafter augment installed, I expected to get the relatively sparse default sapling drop rate.

**Mod list**

Just Enough Items: 4.16.1.302
Forestry: 5.8.2.422
Numina: 1.12.2-.10.38
MachineMuse's Modular Powersuits: 1.12.2-1.0.46

**Log files**

https://gist.github.com/TeetoKaziim/01ca2ede98e536ccb6f87663eb74889f

**Comment by EzerArch** [comment]
@TeetoKaziim MPS is dead and reborn as MPA: https://github.com/lehjr/ModularPowerArmor/
