### ISSUE TITLE
My game crashed and i wanted to report it

### ISSUE THREAD

**Issue by Slendher40** [MachineMuse/MachineMusePowersuits#984]
**Version info**
Java version: 1.12.2
Minecraft Forge version:

**Describe the bug**
The game crashed

**To Reproduce**

**Expected behavior**

**Mod list**
Including versions, provided by crash report if game crashed:

Smallest sub-list that still produces issue, if any exclusion testing was done:

**Log files**
(Link to pastebin, gist, or other hosting site preferred, file attachment okay.)
Game log (make sure it's the log that was generated during the gameplay the issue occurred in):
Crash report (if issue caused game to crash):

[crash-2020-11-26_20.48.14-server.txt](https://github.com/MachineMuse/MachineMusePowersuits/files/5605768/crash-2020-11-26_20.48.14-server.txt)

Server log (if issue occurred on a server, make sure it's the log generated during the gameplay the issue occurred in):
Server crash report (if issue caused server to crash):

**Screenshots**

**Additional context**

**Comment by EzerArch** [comment]
@Slendher40 MPS is dead and reborn as MPA: https://github.com/lehjr/ModularPowerArmor/
