### ISSUE TITLE
Armor not showing 1.12.2

### ISSUE THREAD

**Issue by Rutanamiku** [MachineMuse/MachineMusePowersuits#988]
**Version info**
Java version: build 1.8.0_281-b09
Minecraft Forge version: 14.23.5.2855

**Describe the bug**
Armor not showing on player model when equipped 

**To Reproduce**
Steps to reproduce the behavior: Equip armor and go third person view 

**Expected behavior**
Visible armour 

**Mod list**
Damage indicators
Applied energistics 2
AE2 stuff
Astral scorcery
Avaritia
Avaritia addons
Baubles
bdlib
Bewitchment
Binnie mods
Blood magic
Botania
BrandonsCore
CodeChikenLib
CoFHCore
Draconic Evolution
Dragon Mounts 2 
Electroblobs Wizardry
Electro Magic Tools
Forge Multipart
Gravestone
Gravitation Suite 
Guide API
Industrial Craft 2 
Iron Chest 
Just Enough Items
Mekanism
Mekanism Generators
Mekanism Tools
Mekanism JEI Fix
Modular powersuits
MrTJPCore
Numina
OptiFine
Patchouli

**Log files**

**Screenshots**
![image](https://user-images.githubusercontent.com/80691376/111163316-adfbf200-85a5-11eb-856d-cc515c532fa5.png)

**Additional context**
Already changed visual settings in tinker table

**Comment by CodyTheRed** [comment]
Figure out a fix for this yet?

**Comment by Fanservice5800** [comment]
Was having the same issue. I looked through the mods we have in common and ran the game without them one at a time. Looks like Wizardry is the culprit.

**Comment by EzerArch** [comment]
The mod is here now: https://github.com/lehjr/MachineMusePowersuits (by @lehjr)

**Comment by lehjr** [comment]
1.12.2 is no longer supported
