### ISSUE TITLE
1.16.5

### ISSUE THREAD

**Issue by oguh43** [MachineMuse/MachineMusePowersuits#989]
**Version info**
Java version:java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)
Minecraft Forge version: forge-1.16.5-36.0.54

**Describe the bug**

**To Reproduce**
1. Go to mc
2. Click on 'e'
3. Select powersuit/ infinity backpack

**Expected behavior**
negated step 4
**Mod list**
Including versions, provided by crash report if game crashed:
https://pastebin.com/FwXk41c1

**Log files**
(Link to pastebin, gist, or other hosting site preferred, file attachment okay.)

Server crash report (if issue caused server to crash):https://pastebin.com/FwXk41c1

**Comment by EzerArch** [comment]
The mod is here now: https://github.com/lehjr/MachineMusePowersuits (by @lehjr)

**Comment by lehjr** [comment]
fixed in current builds
