### ISSUE TITLE
Bug report : Crashing with other mods 

### ISSUE THREAD

**Issue by kirillka77734** [MachineMuse/MachineMusePowersuits#990]
**Version info**
Java version: 1.8.0_281
Minecraft Forge version: minecraftforge:36.0.48

**Describe the bug**
It's crashing with 2.0.3 
But if i download 2.0.2 it's will not crash ( at 2.0.2 version doesnt have recipes ) 

**To Reproduce**
1. Download 2.0.3 version
2. Start up my modpack with this version
3. Wait for load 

**Expected behavior**
it's just crashing . 

**Mod list**
https://imgur.com/a/c3Jt32u screenshot of all mods
**screenshot**

https://pastebin.com/TD5ERxHg crash report 

**Additional context**
https://imgur.com/a/c3Jt32u screenshot of all mods i using with this mod
[crash-2021-03-25_19.18.00-client.txt](https://github.com/MachineMuse/MachineMusePowersuits/files/6206341/crash-2021-03-25_19.18.00-client.txt)

**Comment by EzerArch** [comment]
MPS is here now: https://github.com/lehjr/MachineMusePowersuits (by @lehjr)

**Comment by kirillka77734** [comment]
> MPS is here now: https://github.com/lehjr/MachineMusePowersuits (by @lehjr)

Ok sorry about it , i will write in " https://github.com/lehjr/MachineMusePowersuits "
