### ISSUE TITLE
Crash between Dank Storage and Powersuits

### ISSUE THREAD

**Issue by CloWnicide** [MachineMuse/MachineMusePowersuits#991]
**Version info**
Java version: 1.8.0.281 (64bit)
Minecraft Forge version:36.1.2

**Describe the bug**
Used a dank storage in construction mode, instant crash

**To Reproduce**
Use dank storage in construction mode, profit

**Expected behavior**
No crash

Crash Log: https://gist.github.com/CloWnicide/0406e0eb78885877349361e82c8c0259

**Comment by lehjr** [comment]
should be fixed in alpha 4

**Comment by CloWnicide** [comment]
Sweet
