### ISSUE TITLE
server freezing after firing railgun

### ISSUE THREAD

**Issue by AngryCarrot789** [MachineMuse/MachineMusePowersuits#993]
**Version info**
Java version: 1.8
Minecraft Forge version: 9.11.1.965

when a player fired the railgun module in the end (world), it caused the server to completely freeze (and eventually the watchdog force stops the server and then it restarts).
i have a plugin that prints out the stacktrace the Server thread was executing, and this is what it was outputting for about  60 seconds:

```
net.minecraft.world.World.func_72869_a(World.java:1882)
net.machinemuse.powersuits.powermodule.weapon.RailgunModule.drawParticleStreamTo(RailgunModule.java:79)
net.machinemuse.powersuits.powermodule.weapon.RailgunModule.onRightClick(RailgunModule.java:107)
net.machinemuse.powersuits.item.ItemPowerFist$$anonfun$onItemRightClick$1.apply(ItemPowerFist.scala:153)
net.machinemuse.powersuits.item.ItemPowerFist$$anonfun$onItemRightClick$1.apply(ItemPowerFist.scala:151)
scala.collection.Iterator$class.foreach(Iterator.scala:727)
scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
scala.collection.AbstractIterable.foreach(Iterable.scala:54)
net.machinemuse.powersuits.item.ItemPowerFist.func_77659_a(ItemPowerFist.scala:151)
net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:305)
net.minecraft.item.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:429)
net.minecraft.network.NetServerHandler.func_72472_a(NetServerHandler.java:870)
net.minecraft.network.packet.Packet15Place.func_73279_a(SourceFile:58)
net.minecraft.network.TcpConnection.func_74428_b(TcpConnection.java:480)
net.minecraft.network.NetServerHandler.func_72570_d(NetServerHandler.java:234)
net.minecraft.network.NetworkListenThread.func_71747_b(NetworkListenThread.java:54)
net.minecraft.server.dedicated.DedicatedServerListenThread.func_71747_b(DedicatedServerListenThread.java:37)
net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:927)
net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:332)
net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782)
net.minecraft.server.MinecraftServer.run(MinecraftServer.java:665)
net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
Thread state: RUNNABLE
```

my guess is, based on the drawParticleStreamTo() function, they somehow fired a shot in such a perfect direction that it just looped forever... possibly

i suppose one fix would be to track how many particles have spawned (aka have an incrementor in the while loop, and if it exceeds something like 1000, then exit the while loop)
however... im not sure if its actually because of this "perfect shot", or if its the sending packets to the client. im assuming its the "perfect shot", because disabling the particles would be quite unfortunate

**Comment by lehjr** [comment]
Sorry, nobody is going to update the mod for an 8 year old version of Forge.

**Comment by AngryCarrot789** [comment]
oh right. i managed to fix it though, it was a function in the direction generation (i think) which had a while loop that checked the equality of a float (from what i remember), so i just modified it and added a counter to how many iterations it had done, and returned after 100

**Comment by AngryCarrot789** [comment]
https://github.com/MachineMuse/MachineMusePowersuits/blob/273d93291b86323a76cf19f9e9c45779da6e25a1/src/main/java/net/machinemuse/powersuits/powermodule/weapon/RailgunModule.java#L83
this to be percise
