### ISSUE TITLE
[Request] Silk Touch is not a tool, Please create a toggle on/off we can set keybind for. Silk touch is an enhancement for the pickaxe/shovel/axe tools, and should work when those tools are working.

### ISSUE THREAD

**Issue by iLLHunter** [MachineMuse/MachineMusePowersuits#996]
**Is your feature request related to a problem? Please describe.**
Silk touch is an enhancement, not a tool. In MPS terms, this means it should be a toggle on/off, not a separate tool to select on the power tool. 
The tools that use silk touch (axe, pickaxe, shovel ) do not need to be selected, they just work on appropriate blocks. Silk touch itself is not activated with right click like the other add-on tools, it works through those tools I just mentioned automatically. This makes it ideal for a toggle on/off.

The problem that is the cause for this feature request is that when mining, we should be able to select a defensive weapon on our power tool tool, something that requires rt click to operate, while mining with or without silk touch enhancement.

I should not have to decide between Railgun or "silk touch" like I do not have to choose between railgun or pickaxe. The pickaxe will just work when I left click, railgun when I right click. Since silk touch is not a tool, it is an enhancement for the pickaxe tool, it should just work when the pickaxe tool is working.

**Describe the solution you'd like**
Silk touch as a toggle we can set a keybind for on the tinker table(module)

**Describe alternatives you've considered**
There is none I can think of

**Comment by lehjr** [comment]
You have a tool at your disposal called the melee assist that can be used along with the mob repulsor. The pickaxe is always enabled as long as it is installed, so I’m not sure what you’re on about. Seems you’re looking for a solution to a problem that doesn’t exist.

**Comment by iLLHunter** [comment]
It is great when someone reads the report. When someone fails to read a report, we get responses like this. Instead of trying to create excuses why something is not a problem, listen to the problem that is being reported.

Your response highlights the problem. There are other "tools" we want to use like the railgun, but instead we have to select "silk touch" as a tool which prevents us from using a real tool. 
Silk touch is not a "tool" it is an enchant, an enhancement for a tool.
Instead of trying to make silk touch into something it is not, like a tool, it could be made into an enhancement for the tool. A toggle, or a tinker table setting, to turn it on or off. When it is on the real tool, pickaxe, has the enhancement. when it is off, the tool does not have the enhancement.
