### ISSUE TITLE
Server crash on startup Minecraft  1.16.5

### ISSUE THREAD

**Issue by Realever** [MachineMuse/MachineMusePowersuits#998]
**Version info**
Minecraft version: 1.16.5
Minecraft Forge version: 36.2.4
Modular Power suit version: ModularPowersuits-1.16.5-2.1.12
Numina: Numina-1.16.5-2.1.12
**Describe the bug**
The server crash on startup

**Mod list**
It is a private modpack and it has a lot of mods.

**Log files**
Server log (if issue occurred on a server, make sure it's the log generated during the gameplay the issue occurred in): This the the latest log file: https://pastebin.com/eJhnpHUv
Server crash report (if issue caused server to crash): https://pastebin.com/pEaKBmnm

**Comment by lehjr** [comment]
Fixed in beta 3
