### ISSUE TITLE
MC 1.16.5 Server Crashes when trying to find powersuits:tinkertable

### ISSUE THREAD

**Issue by avenplainstrider** [MachineMuse/MachineMusePowersuits#999]
**Version info**
Minecraft Forge version: 36.2.0
Modular Powersuits 2.1.12 for 1.16.5

**Describe the bug**
Crash on Server start due to Modular Powersuits having trouble finding powersuits:tinkertable

Crash report (if issue caused game to crash):
Server log (if issue occurred on a server, make sure it's the log generated during the gameplay the issue occurred in): https://pastebin.com/nqqUkNWx
Server crash report (if issue caused server to crash): https://pastebin.com/u7ekv5Gs

**Comment by CryoByte33** [comment]
I also have this, same versions and same error.

**Comment by lehjr** [comment]
Fixed in beta 3
